In [22]:
import pandas as pd

In [23]:
nb_games = "10"

In [24]:
data_type = {"gameId": str, "teamId": str, "W_CONFR_D" : int}
df_stat_last_perf = pd.read_csv('../dataset/team_stat_last_'+ nb_games +'.csv', dtype=data_type )
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,DIFF_W,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,...,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10,TOTAL_POINTS,teamName,W_CONFR_D
0,0021300001,1610612754,2013-10-29,IND vs. ORL,W,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97,Indiana Pacers,0
1,0021300001,1610612753,2013-10-29,ORL @ IND,L,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87,Orlando Magic,0
2,0021300002,1610612748,2013-10-29,MIA vs. CHI,W,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107,Miami Heat,0
3,0021300002,1610612741,2013-10-29,CHI @ MIA,L,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95,Chicago Bulls,0
4,0021300003,1610612747,2013-10-29,LAL vs. LAC,W,0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,Los Angeles Lakers,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301228,1610612758,2023-12-08,SAC @ PHX,W,3,0.6,0.4738,0.3759,0.7684,...,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814,114,Sacramento Kings,3
24078,0022301229,1610612749,2023-12-07,MIL vs. IND,L,9,0.8,0.5201,0.3984,0.7737,...,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446,119,Milwaukee Bucks,5
24079,0022301229,1610612754,2023-12-07,IND @ MIL,W,3,0.5,0.5218,0.3864,0.7809,...,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054,128,Indiana Pacers,2
24080,0022301230,1610612747,2023-12-07,LAL vs. NOP,W,4,0.7,0.4767,0.3244,0.7606,...,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255,133,Los Angeles Lakers,3
24081,0022301230,1610612740,2023-12-07,NOP @ LAL,L,2,0.6,0.5006,0.3545,0.7908,...,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425,89,New Orleans Pelicans,4

In [25]:
df_stat_last_perf['col'] = df_stat_last_perf.groupby('gameId').cumcount() + 1
df_stat_flatten = df_stat_last_perf.pivot_table(index='gameId', columns=df_stat_last_perf.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'DIFF_W', 'NB_WIN_L'+nb_games,
       'PCT_TIR_REUSSI_L'+nb_games, 'PCT_3PTS_L'+ nb_games, 'PCT_LANCER_FRANC_L'+ nb_games,
       'estimatedOffensiveRating_L'+ nb_games, 'offensiveRating_L'+ nb_games,
       'estimatedDefensiveRating_L'+ nb_games, 'defensiveRating_L'+ nb_games,
       'estimatedNetRating_L'+ nb_games, 'netRating_L'+ nb_games, 'assistPercentage_L'+ nb_games,
       'assistToTurnover_L'+ nb_games, 'assistRatio_L'+ nb_games,
       'estimatedTeamTurnoverPercentage_L'+ nb_games, 'turnoverRatio_L'+ nb_games,
       'effectiveFieldGoalPercentage_L'+ nb_games, 'trueShootingPercentage_L'+ nb_games,
       'estimatedPace_L'+ nb_games, 'pace_L'+ nb_games, 'pacePer40_L'+ nb_games, 'PIE_L'+ nb_games, 'TOTAL_POINTS', 'teamName', 'W_CONFR_D'], aggfunc='first')

df_stat_flatten.columns = [f'col{col[1]}' for col in df_stat_flatten.columns]


df_stat_flatten = df_stat_flatten.reset_index()
df_stat_flatten

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,0021300001,0,0,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0.0,0.0,NaN,...,NaN,NaN,1610612754,1610612753,Indiana Pacers,Orlando Magic,NaN,NaN,NaN,NaN
1,0021300002,0,0,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0.0,0.0,NaN,...,NaN,NaN,1610612748,1610612741,Miami Heat,Chicago Bulls,NaN,NaN,NaN,NaN
2,0021300003,0,0,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0.0,0.0,NaN,...,NaN,NaN,1610612747,1610612746,Los Angeles Lakers,Los Angeles Clippers,NaN,NaN,NaN,NaN
3,0021300004,0,0,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0.0,0.0,NaN,...,NaN,NaN,1610612739,1610612751,Cleveland Cavaliers,Brooklyn Nets,NaN,NaN,NaN,NaN
4,0021300005,0,1,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0.0,0.1,NaN,...,NaN,98.50,1610612755,1610612748,Philadelphia 76ers,Miami Heat,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12036,0022301226,-8,4,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,0.3,0.4,0.3744,...,97.259,99.80,1610612757,1610612742,Portland Trail Blazers,Dallas Mavericks,0.5395,0.5587,16.22,10.72
12037,0022301227,10,4,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,0.7,0.7,0.3545,...,98.631,96.75,1610612738,1610612752,Boston Celtics,New York Knicks,0.5876,0.5792,15.05,13.69
12038,0022301228,3,3,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,0.7,0.6,0.3954,...,96.250,102.40,1610612756,1610612758,Phoenix Suns,Sacramento Kings,0.6058,0.5941,14.64,13.14
12039,0022301229,9,3,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,0.8,0.5,0.3984,...,102.598,104.30,1610612749,1610612754,Milwaukee Bucks,Indiana Pacers,0.6296,0.6305,12.30,11.57
12040,0022301230,4,2,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,0.7,0.6,0.3244,...,100.750,98.95,1610612747,1610612740,Los Angeles Lakers,New Orleans Pelicans,0.5706,0.6015,14.62,13.51

In [26]:
df_stat_flatten.columns = ['gameId', 'H_DIFF_W', 'A_DIFF_W', 'H_DUEL', 'A_DUEL', 'H_GAME_DATE', 'A_GAME_DATE', 'H_NB_WIN_L'+nb_games, 'A_NB_WIN_L'+nb_games, 'H_PCT_3PT_L'+nb_games, 'A_PCT_3PT_L'+nb_games, 'H_PCT_LANCER_FRANC_L'+nb_games, 'A_PCT_LANCER_FRANC_L'+nb_games, 'H_PCT_TIR_REUSSI_L'+nb_games, 'A_PCT_TIR_REUSSI_L'+nb_games, 'H_PIE_L'+nb_games, 'A_PIE_L'+nb_games, 'H_POINTS', 'A_POINTS', 'H_WL', 'A_WL', 'H_W_CONFR_D', 'A_W_CONFR_D', 'H_assistPercentage_L'+nb_games, 'A_assistPercentage_L'+nb_games, 'H_assistRatio_L'+nb_games, 'A_assistRatio_L'+nb_games, 'H_assistToTurnover_L'+nb_games, 'A_assistToTurnover_L'+nb_games, 'H_defensiveRating_L'+nb_games, 'A_defensiveRating_L'+nb_games, 'H_effectiveFieldGoalPercentage_L'+nb_games, 'A_effectiveFieldGoalPercentage_L'+nb_games, 'H_estimatedDefensiveRating_L'+nb_games, 'A_estimatedDefensiveRating_L'+nb_games, 'H_estimatedNetRating_L'+nb_games, 'A_estimatedNetRating_L'+nb_games, 'H_estimatedOffensiveRating_L'+nb_games, 'A_estimatedOffensiveRating_L'+nb_games, 'H_estimatedPace_L'+nb_games, 'A_estimatedPace_L'+nb_games, 'H_estimatedTeamTurnoverPercentage_L'+nb_games, 'A_estimatedTeamTurnoverPercentage_L'+nb_games, 'H_netRating_L'+nb_games, 'A_netRating_L'+nb_games, 'H_offensiveRating_L'+nb_games, 'A_offensiveRating_L'+nb_games, 'H_pacePer40_L'+nb_games, 'A_pacePer40_L'+nb_games, 'H_pace_L'+nb_games, 'A_pace_L'+nb_games, 'H_teamId', 'A_teamId', 'H_teamName', 'A_teamName', 'H_trueShootingPercentage_L'+nb_games, 'A_trueShootingPercentage_L'+nb_games, 'H_turnoverRatio_L'+nb_games, 'A_turnoverRatio_L'+nb_games]
df_stat_flatten

,gameId,H_DIFF_W,A_DIFF_W,H_DUEL,A_DUEL,H_GAME_DATE,A_GAME_DATE,H_NB_WIN_L10,A_NB_WIN_L10,H_PCT_3PT_L10,...,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_teamName,A_teamName,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,0021300001,0,0,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0.0,0.0,NaN,...,NaN,NaN,1610612754,1610612753,Indiana Pacers,Orlando Magic,NaN,NaN,NaN,NaN
1,0021300002,0,0,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0.0,0.0,NaN,...,NaN,NaN,1610612748,1610612741,Miami Heat,Chicago Bulls,NaN,NaN,NaN,NaN
2,0021300003,0,0,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0.0,0.0,NaN,...,NaN,NaN,1610612747,1610612746,Los Angeles Lakers,Los Angeles Clippers,NaN,NaN,NaN,NaN
3,0021300004,0,0,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0.0,0.0,NaN,...,NaN,NaN,1610612739,1610612751,Cleveland Cavaliers,Brooklyn Nets,NaN,NaN,NaN,NaN
4,0021300005,0,1,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0.0,0.1,NaN,...,NaN,98.50,1610612755,1610612748,Philadelphia 76ers,Miami Heat,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12036,0022301226,-8,4,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,0.3,0.4,0.3744,...,97.259,99.80,1610612757,1610612742,Portland Trail Blazers,Dallas Mavericks,0.5395,0.5587,16.22,10.72
12037,0022301227,10,4,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,0.7,0.7,0.3545,...,98.631,96.75,1610612738,1610612752,Boston Celtics,New York Knicks,0.5876,0.5792,15.05,13.69
12038,0022301228,3,3,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,0.7,0.6,0.3954,...,96.250,102.40,1610612756,1610612758,Phoenix Suns,Sacramento Kings,0.6058,0.5941,14.64,13.14
12039,0022301229,9,3,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,0.8,0.5,0.3984,...,102.598,104.30,1610612749,1610612754,Milwaukee Bucks,Indiana Pacers,0.6296,0.6305,12.30,11.57
12040,0022301230,4,2,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,0.7,0.6,0.3244,...,100.750,98.95,1610612747,1610612740,Los Angeles Lakers,New Orleans Pelicans,0.5706,0.6015,14.62,13.51

In [27]:
df_stat_flatten = df_stat_flatten.drop('A_DUEL', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_GAME_DATE', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_WL', axis=1)
df_stat_flatten = df_stat_flatten.rename(columns={'H_DUEL': 'DUEL', 'H_GAME_DATE': 'GAME_DATE', 'H_WL': 'HOME_WON'})
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('W', 1)
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('L', 0)
df_stat_flatten

,gameId,H_DIFF_W,A_DIFF_W,DUEL,GAME_DATE,H_NB_WIN_L10,A_NB_WIN_L10,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,...,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_teamName,A_teamName,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,0021300001,0,0,IND vs. ORL,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,1610612754,1610612753,Indiana Pacers,Orlando Magic,NaN,NaN,NaN,NaN
1,0021300002,0,0,MIA vs. CHI,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,1610612748,1610612741,Miami Heat,Chicago Bulls,NaN,NaN,NaN,NaN
2,0021300003,0,0,LAL vs. LAC,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,1610612747,1610612746,Los Angeles Lakers,Los Angeles Clippers,NaN,NaN,NaN,NaN
3,0021300004,0,0,CLE vs. BKN,2013-10-30,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,1610612739,1610612751,Cleveland Cavaliers,Brooklyn Nets,NaN,NaN,NaN,NaN
4,0021300005,0,1,PHI vs. MIA,2013-10-30,0.0,0.1,NaN,0.5500,NaN,...,NaN,98.50,1610612755,1610612748,Philadelphia 76ers,Miami Heat,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12036,0022301226,-8,4,POR vs. DAL,2023-12-08,0.3,0.4,0.3744,0.3463,0.7976,...,97.259,99.80,1610612757,1610612742,Portland Trail Blazers,Dallas Mavericks,0.5395,0.5587,16.22,10.72
12037,0022301227,10,4,BOS vs. NYK,2023-12-08,0.7,0.7,0.3545,0.3853,0.7753,...,98.631,96.75,1610612738,1610612752,Boston Celtics,New York Knicks,0.5876,0.5792,15.05,13.69
12038,0022301228,3,3,PHX vs. SAC,2023-12-08,0.7,0.6,0.3954,0.3759,0.8557,...,96.250,102.40,1610612756,1610612758,Phoenix Suns,Sacramento Kings,0.6058,0.5941,14.64,13.14
12039,0022301229,9,3,MIL vs. IND,2023-12-07,0.8,0.5,0.3984,0.3864,0.7737,...,102.598,104.30,1610612749,1610612754,Milwaukee Bucks,Indiana Pacers,0.6296,0.6305,12.30,11.57
12040,0022301230,4,2,LAL vs. NOP,2023-12-07,0.7,0.6,0.3244,0.3545,0.7606,...,100.750,98.95,1610612747,1610612740,Los Angeles Lakers,New Orleans Pelicans,0.5706,0.6015,14.62,13.51

In [28]:
nba_elo = pd.read_csv('../dataset/nba_elo.csv', dtype=data_type )

In [29]:
nba_elo_copy= nba_elo.copy()
nba_elo_copy

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,elo1_post,elo2_post,score1,score2,is_home
0,1946-11-01,1947,0,NaN,TRH,NYK,1300.000000,1300.000000,0.640065,0.359935,1293.276700,1306.723300,66,68,1
1,1946-11-01,1947,0,NaN,NYK,TRH,1300.000000,1300.000000,0.359935,0.640065,1306.723300,1293.276700,68,66,0
2,1946-11-02,1947,0,NaN,PRO,BOS,1300.000000,1300.000000,0.640065,0.359935,1305.154200,1294.845800,59,53,1
3,1946-11-02,1947,0,NaN,STB,PIT,1300.000000,1300.000000,0.640065,0.359935,1304.690800,1295.309200,56,51,1
4,1946-11-02,1947,0,NaN,CHS,NYK,1300.000000,1306.723300,0.631101,0.368899,1309.652100,1297.071200,63,47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148933,2024-03-30,2024,0,NaN,MEM,ORL,1325.023208,1523.156879,0.152362,0.847638,1319.643511,1528.536576,88,118,0
148934,2024-03-30,2024,0,NaN,MIL,ATL,1586.179279,1493.120229,0.490012,0.509988,1596.162979,1483.136529,122,113,0
148935,2024-03-30,2024,0,NaN,NOP,BOS,1635.324867,1758.207851,0.467116,0.532884,1624.649366,1768.883352,92,104,1
148936,2024-03-30,2024,0,NaN,ORL,MEM,1523.156879,1325.023208,0.847638,0.152362,1528.536576,1319.643511,118,88,1
148937,2024-03-30,2024,0,NaN,ATL,MIL,1493.120229,1586.179279,0.509988,0.490012,1483.136529,1596.162979,113,122,1

In [30]:
columns_list = nba_elo_copy.columns.tolist()

In [31]:
columns_to_drop = ['season',  'neutral', 'playoff', 'team2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']  # Liste des noms des colonnes à supprimer
nba_elo_copy_drop= nba_elo_copy.drop(columns=columns_to_drop)

In [32]:
nba_elo_copy_drop

              date team1     elo1_pre     elo2_pre  elo_prob1  elo_prob2
0       1946-11-01   TRH  1300.000000  1300.000000   0.640065   0.359935
1       1946-11-01   NYK  1300.000000  1300.000000   0.359935   0.640065
2       1946-11-02   PRO  1300.000000  1300.000000   0.640065   0.359935
3       1946-11-02   STB  1300.000000  1300.000000   0.640065   0.359935
4       1946-11-02   CHS  1300.000000  1306.723300   0.631101   0.368899
...            ...   ...          ...          ...        ...        ...
148933  2024-03-30   MEM  1325.023208  1523.156879   0.152362   0.847638
148934  2024-03-30   MIL  1586.179279  1493.120229   0.490012   0.509988
148935  2024-03-30   NOP  1635.324867  1758.207851   0.467116   0.532884
148936  2024-03-30   ORL  1523.156879  1325.023208   0.847638   0.152362
148937  2024-03-30   ATL  1493.120229  1586.179279   0.509988   0.490012

[148938 rows x 6 columns]

In [33]:
nba_elo_copy_drop['team1'] = nba_elo_copy_drop['team1'].replace({'PHO': 'PHX', 'BRK': 'BKN', 'CHO': 'CHA'})

In [34]:
df_stat_flatten['team1'] = df_stat_flatten['DUEL'].str.split(' vs. ').str[0]
df_stat_flatten

,gameId,H_DIFF_W,A_DIFF_W,DUEL,GAME_DATE,H_NB_WIN_L10,A_NB_WIN_L10,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,...,A_pace_L10,H_teamId,A_teamId,H_teamName,A_teamName,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1
0,0021300001,0,0,IND vs. ORL,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,NaN,1610612754,1610612753,Indiana Pacers,Orlando Magic,NaN,NaN,NaN,NaN,IND
1,0021300002,0,0,MIA vs. CHI,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,NaN,1610612748,1610612741,Miami Heat,Chicago Bulls,NaN,NaN,NaN,NaN,MIA
2,0021300003,0,0,LAL vs. LAC,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,NaN,1610612747,1610612746,Los Angeles Lakers,Los Angeles Clippers,NaN,NaN,NaN,NaN,LAL
3,0021300004,0,0,CLE vs. BKN,2013-10-30,0.0,0.0,NaN,NaN,NaN,...,NaN,1610612739,1610612751,Cleveland Cavaliers,Brooklyn Nets,NaN,NaN,NaN,NaN,CLE
4,0021300005,0,1,PHI vs. MIA,2013-10-30,0.0,0.1,NaN,0.5500,NaN,...,98.50,1610612755,1610612748,Philadelphia 76ers,Miami Heat,NaN,0.6310,NaN,20.20,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12036,0022301226,-8,4,POR vs. DAL,2023-12-08,0.3,0.4,0.3744,0.3463,0.7976,...,99.80,1610612757,1610612742,Portland Trail Blazers,Dallas Mavericks,0.5395,0.5587,16.22,10.72,POR
12037,0022301227,10,4,BOS vs. NYK,2023-12-08,0.7,0.7,0.3545,0.3853,0.7753,...,96.75,1610612738,1610612752,Boston Celtics,New York Knicks,0.5876,0.5792,15.05,13.69,BOS
12038,0022301228,3,3,PHX vs. SAC,2023-12-08,0.7,0.6,0.3954,0.3759,0.8557,...,102.40,1610612756,1610612758,Phoenix Suns,Sacramento Kings,0.6058,0.5941,14.64,13.14,PHX
12039,0022301229,9,3,MIL vs. IND,2023-12-07,0.8,0.5,0.3984,0.3864,0.7737,...,104.30,1610612749,1610612754,Milwaukee Bucks,Indiana Pacers,0.6296,0.6305,12.30,11.57,MIL
12040,0022301230,4,2,LAL vs. NOP,2023-12-07,0.7,0.6,0.3244,0.3545,0.7606,...,98.95,1610612747,1610612740,Los Angeles Lakers,New Orleans Pelicans,0.5706,0.6015,14.62,13.51,LAL

In [35]:
new_column_names = {'date':'GAME_DATE' }
nba_elo_copy_drop_rename= nba_elo_copy_drop.rename(columns=new_column_names)
nba_elo_copy_drop_rename

         GAME_DATE team1     elo1_pre     elo2_pre  elo_prob1  elo_prob2
0       1946-11-01   TRH  1300.000000  1300.000000   0.640065   0.359935
1       1946-11-01   NYK  1300.000000  1300.000000   0.359935   0.640065
2       1946-11-02   PRO  1300.000000  1300.000000   0.640065   0.359935
3       1946-11-02   STB  1300.000000  1300.000000   0.640065   0.359935
4       1946-11-02   CHS  1300.000000  1306.723300   0.631101   0.368899
...            ...   ...          ...          ...        ...        ...
148933  2024-03-30   MEM  1325.023208  1523.156879   0.152362   0.847638
148934  2024-03-30   MIL  1586.179279  1493.120229   0.490012   0.509988
148935  2024-03-30   NOP  1635.324867  1758.207851   0.467116   0.532884
148936  2024-03-30   ORL  1523.156879  1325.023208   0.847638   0.152362
148937  2024-03-30   ATL  1493.120229  1586.179279   0.509988   0.490012

[148938 rows x 6 columns]

In [36]:
df_stat_flatten = pd.merge(df_stat_flatten, nba_elo_copy_drop_rename, on=['GAME_DATE', 'team1'])
df_stat_flatten

,gameId,H_DIFF_W,A_DIFF_W,DUEL,GAME_DATE,H_NB_WIN_L10,A_NB_WIN_L10,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,...,A_teamName,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1,elo1_pre,elo2_pre,elo_prob1,elo_prob2
0,0021300001,0,0,IND vs. ORL,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,Orlando Magic,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700,0.893961,0.106039
1,0021300002,0,0,MIA vs. CHI,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,Chicago Bulls,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400,0.827159,0.172841
2,0021300003,0,0,LAL vs. LAC,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,Los Angeles Clippers,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400,0.535102,0.464898
3,0021300004,0,0,CLE vs. BKN,2013-10-30,0.0,0.0,NaN,NaN,NaN,...,Brooklyn Nets,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500,0.388019,0.611981
4,0021300005,0,1,PHI vs. MIA,2013-10-30,0.0,0.1,NaN,0.5500,NaN,...,Miami Heat,NaN,0.6310,NaN,20.20,PHI,1459.690400,1695.193200,0.314316,0.685684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11911,0022301226,-8,4,POR vs. DAL,2023-12-08,0.3,0.4,0.3744,0.3463,0.7976,...,Dallas Mavericks,0.5395,0.5587,16.22,10.72,POR,1361.139964,1492.541584,0.454932,0.545068
11912,0022301227,10,4,BOS vs. NYK,2023-12-08,0.7,0.7,0.3545,0.3853,0.7753,...,New York Knicks,0.5876,0.5792,15.05,13.69,BOS,1662.122050,1591.374004,0.727684,0.272316
11913,0022301228,3,3,PHX vs. SAC,2023-12-08,0.7,0.6,0.3954,0.3759,0.8557,...,Sacramento Kings,0.6058,0.5941,14.64,13.14,PHX,1551.810711,1526.069995,0.673448,0.326552
11914,0022301229,9,3,MIL vs. IND,2023-12-07,0.8,0.5,0.3984,0.3864,0.7737,...,Indiana Pacers,0.6296,0.6305,12.30,11.57,MIL,1601.142185,1502.061541,0.638845,0.361155
11915,0022301230,4,2,LAL vs. NOP,2023-12-07,0.7,0.6,0.3244,0.3545,0.7606,...,New Orleans Pelicans,0.5706,0.6015,14.62,13.51,LAL,1541.467385,1543.760516,0.496700,0.503300

In [37]:
new_column_names = {'elo1_pre':'H_ELO' , 'elo2_pre': 'A_ELO', 'elo_prob1':'H_ELO_PROB', 'elo_prob2':'A_ELO_PROB'}
df_stat_flatten= df_stat_flatten.rename(columns=new_column_names)
df_stat_flatten

,gameId,H_DIFF_W,A_DIFF_W,DUEL,GAME_DATE,H_NB_WIN_L10,A_NB_WIN_L10,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,...,A_teamName,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1,H_ELO,A_ELO,H_ELO_PROB,A_ELO_PROB
0,0021300001,0,0,IND vs. ORL,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,Orlando Magic,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700,0.893961,0.106039
1,0021300002,0,0,MIA vs. CHI,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,Chicago Bulls,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400,0.827159,0.172841
2,0021300003,0,0,LAL vs. LAC,2013-10-29,0.0,0.0,NaN,NaN,NaN,...,Los Angeles Clippers,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400,0.535102,0.464898
3,0021300004,0,0,CLE vs. BKN,2013-10-30,0.0,0.0,NaN,NaN,NaN,...,Brooklyn Nets,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500,0.388019,0.611981
4,0021300005,0,1,PHI vs. MIA,2013-10-30,0.0,0.1,NaN,0.5500,NaN,...,Miami Heat,NaN,0.6310,NaN,20.20,PHI,1459.690400,1695.193200,0.314316,0.685684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11911,0022301226,-8,4,POR vs. DAL,2023-12-08,0.3,0.4,0.3744,0.3463,0.7976,...,Dallas Mavericks,0.5395,0.5587,16.22,10.72,POR,1361.139964,1492.541584,0.454932,0.545068
11912,0022301227,10,4,BOS vs. NYK,2023-12-08,0.7,0.7,0.3545,0.3853,0.7753,...,New York Knicks,0.5876,0.5792,15.05,13.69,BOS,1662.122050,1591.374004,0.727684,0.272316
11913,0022301228,3,3,PHX vs. SAC,2023-12-08,0.7,0.6,0.3954,0.3759,0.8557,...,Sacramento Kings,0.6058,0.5941,14.64,13.14,PHX,1551.810711,1526.069995,0.673448,0.326552
11914,0022301229,9,3,MIL vs. IND,2023-12-07,0.8,0.5,0.3984,0.3864,0.7737,...,Indiana Pacers,0.6296,0.6305,12.30,11.57,MIL,1601.142185,1502.061541,0.638845,0.361155
11915,0022301230,4,2,LAL vs. NOP,2023-12-07,0.7,0.6,0.3244,0.3545,0.7606,...,New Orleans Pelicans,0.5706,0.6015,14.62,13.51,LAL,1541.467385,1543.760516,0.496700,0.503300

In [38]:
new_order = ['gameId', 'DUEL','GAME_DATE','H_POINTS', 'A_POINTS','H_teamName', 'A_teamName', 'HOME_WON', 'H_DIFF_W', 'A_DIFF_W', 'H_ELO','A_ELO','H_ELO_PROB','A_ELO_PROB', 'H_W_CONFR_D', 'A_W_CONFR_D', 'H_NB_WIN_L'+nb_games,'A_NB_WIN_L'+nb_games, 'H_PCT_3PT_L'+ nb_games,
       'A_PCT_3PT_L'+ nb_games, 'H_PCT_LANCER_FRANC_L'+ nb_games, 'A_PCT_LANCER_FRANC_L'+ nb_games,
       'H_PCT_TIR_REUSSI_L'+ nb_games, 'A_PCT_TIR_REUSSI_L'+ nb_games, 'H_PIE_L'+ nb_games,
       'A_PIE_L'+ nb_games,  'H_assistPercentage_L'+ nb_games,
       'A_assistPercentage_L'+ nb_games, 'H_assistRatio_L'+ nb_games, 'A_assistRatio_L'+ nb_games,
       'H_assistToTurnover_L'+ nb_games, 'A_assistToTurnover_L'+ nb_games,
       'H_defensiveRating_L'+ nb_games, 'A_defensiveRating_L'+ nb_games,
       'H_effectiveFieldGoalPercentage_L'+ nb_games,
       'A_effectiveFieldGoalPercentage_L'+ nb_games, 'H_estimatedDefensiveRating_L'+ nb_games,
       'A_estimatedDefensiveRating_L'+ nb_games, 'H_estimatedNetRating_L'+ nb_games,
       'A_estimatedNetRating_L'+ nb_games, 'H_estimatedOffensiveRating_L'+ nb_games,
       'A_estimatedOffensiveRating_L'+ nb_games, 'H_estimatedPace_L'+ nb_games,
       'A_estimatedPace_L'+ nb_games, 'H_estimatedTeamTurnoverPercentage_L'+ nb_games,
       'A_estimatedTeamTurnoverPercentage_L'+ nb_games, 'H_netRating_L'+ nb_games,
       'A_netRating_L'+ nb_games, 'H_offensiveRating_L'+ nb_games, 'A_offensiveRating_L'+ nb_games,
       'H_pacePer40_L'+ nb_games, 'A_pacePer40_L'+ nb_games, 'H_pace_L'+ nb_games, 'A_pace_L'+ nb_games,
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L'+ nb_games,
       'A_trueShootingPercentage_L'+ nb_games, 'H_turnoverRatio_L'+ nb_games,
       'A_turnoverRatio_L'+ nb_games, 'team1']

# Réorganiser les colonnes
df_stat_flatten = df_stat_flatten.reindex(columns=new_order)
df_stat_flatten = df_stat_flatten.drop(columns=['team1'])
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_POINTS,A_POINTS,H_teamName,A_teamName,HOME_WON,H_DIFF_W,A_DIFF_W,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,0021300001,IND vs. ORL,2013-10-29,97,87,Indiana Pacers,Orlando Magic,1,0,0,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,0021300002,MIA vs. CHI,2013-10-29,107,95,Miami Heat,Chicago Bulls,1,0,0,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,0021300003,LAL vs. LAC,2013-10-29,116,103,Los Angeles Lakers,Los Angeles Clippers,1,0,0,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,0021300004,CLE vs. BKN,2013-10-30,98,94,Cleveland Cavaliers,Brooklyn Nets,1,0,0,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,0021300005,PHI vs. MIA,2013-10-30,114,110,Philadelphia 76ers,Miami Heat,1,0,1,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11911,0022301226,POR vs. DAL,2023-12-08,112,125,Portland Trail Blazers,Dallas Mavericks,0,-8,4,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
11912,0022301227,BOS vs. NYK,2023-12-08,133,123,Boston Celtics,New York Knicks,1,10,4,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
11913,0022301228,PHX vs. SAC,2023-12-08,106,114,Phoenix Suns,Sacramento Kings,0,3,3,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
11914,0022301229,MIL vs. IND,2023-12-07,119,128,Milwaukee Bucks,Indiana Pacers,0,9,3,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
11915,0022301230,LAL vs. NOP,2023-12-07,133,89,Los Angeles Lakers,New Orleans Pelicans,1,4,2,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [39]:
df_stat_flatten = df_stat_flatten.dropna()
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_POINTS,A_POINTS,H_teamName,A_teamName,HOME_WON,H_DIFF_W,A_DIFF_W,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
17,0021300018,CHI vs. NYK,2013-10-31,82,81,Chicago Bulls,New York Knicks,1,-1,1,...,82.080,78.330,98.500,94.00,1610612741,1610612752,0.5100,0.5730,19.40,23.40
18,0021300019,LAC vs. GSW,2013-10-31,126,115,Los Angeles Clippers,Golden State Warriors,1,-1,1,...,82.080,87.080,98.500,104.50,1610612746,1610612744,0.5530,0.6500,16.30,14.30
19,0021300020,CHA vs. CLE,2013-11-01,90,84,Charlotte Bobcats,Cleveland Cavaliers,1,-1,1,...,76.250,77.500,91.500,93.00,1610612766,1610612739,0.4200,0.4950,8.70,15.10
20,0021300021,ORL vs. NOP,2013-11-01,110,90,Orlando Magic,New Orleans Pelicans,1,-2,-1,...,81.620,76.670,97.945,92.00,1610612753,1610612740,0.4900,0.4780,18.05,16.30
21,0021300022,WAS vs. PHI,2013-11-01,102,109,Washington Wizards,Philadelphia 76ers,0,-1,1,...,81.670,84.580,98.000,101.50,1610612764,1610612755,0.5540,0.6290,17.30,17.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11911,0022301226,POR vs. DAL,2023-12-08,112,125,Portland Trail Blazers,Dallas Mavericks,0,-8,4,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
11912,0022301227,BOS vs. NYK,2023-12-08,133,123,Boston Celtics,New York Knicks,1,10,4,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
11913,0022301228,PHX vs. SAC,2023-12-08,106,114,Phoenix Suns,Sacramento Kings,0,3,3,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
11914,0022301229,MIL vs. IND,2023-12-07,119,128,Milwaukee Bucks,Indiana Pacers,0,9,3,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
11915,0022301230,LAL vs. NOP,2023-12-07,133,89,Los Angeles Lakers,New Orleans Pelicans,1,4,2,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [40]:
df_stat_flatten.columns

Index(['gameId', 'DUEL', 'GAME_DATE', 'H_POINTS', 'A_POINTS', 'H_teamName',
       'A_teamName', 'HOME_WON', 'H_DIFF_W', 'A_DIFF_W', 'H_ELO', 'A_ELO',
       'H_ELO_PROB', 'A_ELO_PROB', 'H_W_CONFR_D', 'A_W_CONFR_D',
       'H_NB_WIN_L10', 'A_NB_WIN_L10', 'H_PCT_3PT_L10', 'A_PCT_3PT_L10',
       'H_PCT_LANCER_FRANC_L10', 'A_PCT_LANCER_FRANC_L10',
       'H_PCT_TIR_REUSSI_L10', 'A_PCT_TIR_REUSSI_L10', 'H_PIE_L10',
       'A_PIE_L10', 'H_assistPercentage_L10', 'A_assistPercentage_L10',
       'H_assistRatio_L10', 'A_assistRatio_L10', 'H_assistToTurnover_L10',
       'A_assistToTurnover_L10', 'H_defensiveRating_L10',
       'A_defensiveRating_L10', 'H_effectiveFieldGoalPercentage_L10',
       'A_effectiveFieldGoalPercentage_L10', 'H_estimatedDefensiveRating_L10',
       'A_estimatedDefensiveRating_L10', 'H_estimatedNetRating_L10',
       'A_estimatedNetRating_L10', 'H_estimatedOffensiveRating_L10',
       'A_estimatedOffensiveRating_L10', 'H_estimatedPace_L10',
       'A_estimatedPace_L10', 'H_estimatedTeamTurnoverPercentage_L10',
       'A_estimatedTeamTurnoverPercentage_L10', 'H_netRating_L10',
       'A_netRating_L10', 'H_offensiveRating_L10', 'A_offensiveRating_L10',
       'H_pacePer40_L10', 'A_pacePer40_L10', 'H_pace_L10', 'A_pace_L10',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L10',
       'A_trueShootingPercentage_L10', 'H_turnoverRatio_L10',
       'A_turnoverRatio_L10'],
      dtype='object')

In [41]:
df_stat_flatten = df_stat_flatten.drop(columns=['DUEL'])
colonne_a_supprimer = df_stat_flatten.columns[7:].tolist()
# Boucle sur chaque paire de colonnes pour calculer la différence
i = 0 
for colonne in colonne_a_supprimer:
    
    
    if colonne != "H_teamId" and colonne != "A_teamId":
           # Extraire le préfixe de la colonne ('H_' ou 'A_')
           prefixe = colonne[0:2]
           # Extraire le nom de la colonne sans le préfixe
           nom_colonne = colonne[2:]
           # Créer une nouvelle colonne pour stocker la différence
           df_stat_flatten[f'{nom_colonne}'] = df_stat_flatten.apply(lambda row: row[f'H_{nom_colonne}'] - row[f'A_{nom_colonne}'], axis=1)
    i = i +1    
colonne_a_supprimer.remove("A_teamId")
colonne_a_supprimer.remove("H_teamId")
df_stat_flatten = df_stat_flatten.drop(columns=colonne_a_supprimer)
       
df_stat_flatten

,gameId,GAME_DATE,H_POINTS,A_POINTS,H_teamName,A_teamName,HOME_WON,H_teamId,A_teamId,DIFF_W,...,estimatedNetRating_L10,estimatedOffensiveRating_L10,estimatedPace_L10,estimatedTeamTurnoverPercentage_L10,netRating_L10,offensiveRating_L10,pacePer40_L10,pace_L10,trueShootingPercentage_L10,turnoverRatio_L10
17,0021300018,2013-10-31,82,81,Chicago Bulls,New York Knicks,1,1610612741,1610612752,-2,...,-24.10,-1.40,4.060,-4.4950,-18.50,1.20,3.750,4.500,-0.0630,-4.00
18,0021300019,2013-10-31,126,115,Los Angeles Clippers,Golden State Warriors,1,1610612746,1610612744,-2,...,-36.80,-16.20,-2.460,1.7360,-40.80,-13.90,-5.000,-6.000,-0.0970,2.00
19,0021300020,2013-11-01,90,84,Charlotte Bobcats,Cleveland Cavaliers,1,1610612766,1610612739,-2,...,-23.00,-13.50,-4.580,-6.0000,-19.60,-15.20,-1.250,-1.500,-0.0750,-6.40
20,0021300021,2013-11-01,110,90,Orlando Magic,New Orleans Pelicans,1,1610612753,1610612740,-1,...,-4.45,-2.05,6.745,1.3120,-2.60,-0.60,4.950,5.945,0.0120,1.75
21,0021300022,2013-11-01,102,109,Washington Wizards,Philadelphia 76ers,0,1610612764,1610612755,-2,...,-13.70,-7.20,-3.840,-0.2060,-14.10,-7.70,-2.910,-3.500,-0.0750,-0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11911,0022301226,2023-12-08,112,125,Portland Trail Blazers,Dallas Mavericks,0,1610612757,1610612742,-12,...,-6.61,-9.34,-1.915,5.2200,-6.22,-8.72,-2.117,-2.541,-0.0192,5.50
11912,0022301227,2023-12-08,133,123,Boston Celtics,New York Knicks,1,1610612738,1610612752,6,...,0.35,-3.46,1.574,1.4297,-0.36,-4.31,1.568,1.881,0.0084,1.36
11913,0022301228,2023-12-08,106,114,Phoenix Suns,Sacramento Kings,0,1610612756,1610612758,0,...,4.31,1.14,-4.722,1.2915,4.54,2.96,-5.125,-6.150,0.0117,1.50
11914,0022301229,2023-12-07,119,128,Milwaukee Bucks,Indiana Pacers,0,1610612749,1610612754,6,...,8.28,1.09,-3.265,0.9842,6.22,-1.94,-1.419,-1.702,-0.0009,0.73
11915,0022301230,2023-12-07,133,89,Los Angeles Lakers,New Orleans Pelicans,1,1610612747,1610612740,2,...,-8.47,-10.14,1.398,0.9580,-5.73,-9.31,1.500,1.800,-0.0309,1.11

In [42]:
df_stat_flatten.to_csv('../dataset/final_dataset.csv', index=False)