In [222]:
import numpy as np
import pandas as pd

In [223]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
nb_games = "10"
df_stat

,teamId,gameId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,1610612748,0021300002,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
1,1610612747,0021300003,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
2,1610612746,0021300003,2013-10-29,LAC @ LAL,L,0,1,0.000,240,41,...,16.3,0.542,0.553,1.0,0.200,102.72,98.5,82.08,98.0,0.497
3,1610612754,0021300001,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
4,1610612741,0021300002,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,1610612739,0022301187,2024-04-14,CLE vs. CHA,L,48,34,0.585,240,44,...,14.4,0.559,0.567,1.0,0.196,97.40,97.0,80.83,97.0,0.427
24078,1610612761,0022301189,2024-04-14,TOR @ MIA,L,25,57,0.305,240,38,...,19.2,0.472,0.519,1.0,0.198,103.30,100.0,83.33,99.0,0.369
24079,1610612742,0022301196,2024-04-14,DAL @ OKC,L,50,32,0.610,240,32,...,14.3,0.371,0.412,1.0,0.199,107.76,105.5,87.92,105.0,0.246
24080,1610612754,0022301188,2024-04-14,IND vs. ATL,W,47,35,0.573,240,65,...,15.0,0.745,0.752,1.0,0.193,108.64,107.0,89.17,107.0,0.649
24081,1610612766,0022301187,2024-04-14,CHA @ CLE,W,21,61,0.256,240,46,...,10.3,0.610,0.626,1.0,0.198,97.40,97.0,80.83,97.0,0.573

In [224]:
df_game_info = df_stat[["TOTAL_POINTS", "DUEL",'GAME_DATE']].copy()
df_game_info.loc[:,'teamName'] = df_stat['teamCity'] + " " + df_stat['teamName']
df_game_info

       TOTAL_POINTS         DUEL   GAME_DATE              teamName
0               107  MIA vs. CHI  2013-10-29            Miami Heat
1               116  LAL vs. LAC  2013-10-29    Los Angeles Lakers
2               103    LAC @ LAL  2013-10-29  Los Angeles Clippers
3                97  IND vs. ORL  2013-10-29        Indiana Pacers
4                95    CHI @ MIA  2013-10-29         Chicago Bulls
...             ...          ...         ...                   ...
24077           110  CLE vs. CHA  2024-04-14   Cleveland Cavaliers
24078           103    TOR @ MIA  2024-04-14       Toronto Raptors
24079            86    DAL @ OKC  2024-04-14      Dallas Mavericks
24080           157  IND vs. ATL  2024-04-14        Indiana Pacers
24081           120    CHA @ CLE  2024-04-14     Charlotte Hornets

[24082 rows x 4 columns]

In [225]:
df_stat_last_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L'+nb_games, 'PCT_TIR_REUSSI_L'+nb_games,'PCT_3PTS_L'+nb_games, 
                           'PCT_LANCER_FRANC_L'+nb_games,'estimatedOffensiveRating_L'+nb_games, 'offensiveRating_L'+nb_games,
                           'estimatedDefensiveRating_L'+nb_games,
                           'defensiveRating_L'+nb_games,'estimatedNetRating_L'+nb_games, 'netRating_L'+nb_games, 'assistPercentage_L'+nb_games,
                           'assistToTurnover_L'+nb_games, 'assistRatio_L'+nb_games,'estimatedTeamTurnoverPercentage_L'+nb_games, 'turnoverRatio_L'+nb_games,
                           'effectiveFieldGoalPercentage_L'+nb_games,'trueShootingPercentage_L'+nb_games, 'estimatedPace_L'+nb_games, 'pace_L'+nb_games,
                           'pacePer40_L'+nb_games, 'PIE_L'+nb_games])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_10_games = team_stats.iloc[max(0, index - int(nb_games)):index]
        df_last_10_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L"+nb_games : (df_last_10_games['WL'] == 'W').sum() / int(nb_games),
                   "PCT_TIR_REUSSI_L"+nb_games : df_last_10_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L"+nb_games : df_last_10_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L"+nb_games : df_last_10_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L"+nb_games : df_last_10_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L"+nb_games : df_last_10_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L"+nb_games : df_last_10_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L"+nb_games : df_last_10_games['defensiveRating'].mean(),
                   "estimatedNetRating_L"+nb_games : df_last_10_games['estimatedNetRating'].mean(),
                   "netRating_L"+nb_games : df_last_10_games['netRating'].mean(),
                   "assistPercentage_L"+nb_games : df_last_10_games['assistPercentage'].mean(),
                   "assistToTurnover_L"+nb_games : df_last_10_games['assistToTurnover'].mean(),
                   "assistRatio_L"+nb_games : df_last_10_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L"+nb_games : df_last_10_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L"+nb_games : df_last_10_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L"+nb_games : df_last_10_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L"+nb_games : df_last_10_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L"+nb_games : df_last_10_games['estimatedPace'].mean(),
                   "pace_L"+nb_games : df_last_10_games['pace'].mean(),
                   "pacePer40_L"+nb_games : df_last_10_games['pacePer40'].mean(),
                   "PIE_L"+nb_games : df_last_10_games['PIE'].mean()}
        df_stat_last_perf.loc[len(df_stat_last_perf)] = new_row
        index += 1
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,0021300015,1610612757,2013-10-30,POR @ PHX,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0021300029,1610612757,2013-11-01,POR @ DEN,W,0.0,0.407000,0.30800,0.708000,96.200000,...,1.360000,15.30,14.805000,14.900000,0.4570,0.4970,94.740000,95.000000,79.170,0.410000
2,0021300039,1610612757,2013-11-02,POR vs. SAS,W,0.1,0.417000,0.47200,0.720500,104.250000,...,2.465000,16.50,10.881500,11.050000,0.4760,0.5065,97.260000,95.750000,79.795,0.503500
3,0021300058,1610612757,2013-11-05,POR vs. HOU,L,0.2,0.463333,0.44800,0.778667,108.466667,...,2.246667,18.20,12.676667,12.866667,0.5190,0.5520,97.486667,96.333333,80.280,0.535667
4,0021300084,1610612757,2013-11-08,POR vs. SAC,W,0.2,0.451000,0.41675,0.747750,105.925000,...,2.077500,17.70,12.913500,13.175000,0.5070,0.5405,98.455000,97.000000,80.835,0.494750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301138,1610612756,2024-04-07,PHX vs. NOP,L,0.7,0.509400,0.43390,0.808600,117.230000,...,2.062000,22.20,16.042000,16.180000,0.5985,0.6254,99.010000,97.650000,81.375,0.537100
24078,0022301156,1610612756,2024-04-09,PHX vs. LAC,L,0.7,0.495600,0.42740,0.814800,114.890000,...,1.993000,21.85,16.247700,16.420000,0.5847,0.6129,98.898000,97.300000,81.084,0.535500
24079,0022301165,1610612756,2024-04-10,PHX @ LAC,W,0.6,0.479300,0.40160,0.825500,112.750000,...,2.058000,20.94,14.793800,14.920000,0.5623,0.5968,98.934000,97.450000,81.209,0.521500
24080,0022301185,1610612756,2024-04-12,PHX @ SAC,W,0.6,0.472300,0.38390,0.829900,111.140000,...,2.116000,20.82,14.251900,14.390000,0.5499,0.5833,99.452000,98.250000,81.875,0.520000
24081,0022301194,1610612756,2024-04-14,PHX @ MIN,W,0.6,0.465300,0.37560,0.844000,109.410000,...,1.868000,20.18,15.235000,15.400000,0.5450,0.5814,98.902000,97.750000,81.458,0.511500

In [226]:
#df_stat_last_perf['POINTS'] = df_game_info
df_stat_last_perf = pd.merge(df_stat_last_perf, df_game_info, on=['DUEL', 'GAME_DATE'])
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10,TOTAL_POINTS,teamName
0,0021300015,1610612757,2013-10-30,POR @ PHX,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,Portland Trail Blazers
1,0021300029,1610612757,2013-11-01,POR @ DEN,W,0.0,0.407000,0.30800,0.708000,96.200000,...,14.805000,14.900000,0.4570,0.4970,94.740000,95.000000,79.170,0.410000,113,Portland Trail Blazers
2,0021300039,1610612757,2013-11-02,POR vs. SAS,W,0.1,0.417000,0.47200,0.720500,104.250000,...,10.881500,11.050000,0.4760,0.5065,97.260000,95.750000,79.795,0.503500,115,Portland Trail Blazers
3,0021300058,1610612757,2013-11-05,POR vs. HOU,L,0.2,0.463333,0.44800,0.778667,108.466667,...,12.676667,12.866667,0.5190,0.5520,97.486667,96.333333,80.280,0.535667,101,Portland Trail Blazers
4,0021300084,1610612757,2013-11-08,POR vs. SAC,W,0.2,0.451000,0.41675,0.747750,105.925000,...,12.913500,13.175000,0.5070,0.5405,98.455000,97.000000,80.835,0.494750,104,Portland Trail Blazers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301138,1610612756,2024-04-07,PHX vs. NOP,L,0.7,0.509400,0.43390,0.808600,117.230000,...,16.042000,16.180000,0.5985,0.6254,99.010000,97.650000,81.375,0.537100,105,Phoenix Suns
24078,0022301156,1610612756,2024-04-09,PHX vs. LAC,L,0.7,0.495600,0.42740,0.814800,114.890000,...,16.247700,16.420000,0.5847,0.6129,98.898000,97.300000,81.084,0.535500,92,Phoenix Suns
24079,0022301165,1610612756,2024-04-10,PHX @ LAC,W,0.6,0.479300,0.40160,0.825500,112.750000,...,14.793800,14.920000,0.5623,0.5968,98.934000,97.450000,81.209,0.521500,124,Phoenix Suns
24080,0022301185,1610612756,2024-04-12,PHX @ SAC,W,0.6,0.472300,0.38390,0.829900,111.140000,...,14.251900,14.390000,0.5499,0.5833,99.452000,98.250000,81.875,0.520000,108,Phoenix Suns
24081,0022301194,1610612756,2024-04-14,PHX @ MIN,W,0.6,0.465300,0.37560,0.844000,109.410000,...,15.235000,15.400000,0.5450,0.5814,98.902000,97.750000,81.458,0.511500,125,Phoenix Suns

In [227]:
df_stat_last_perf['W_CONFR_D'] = np.nan
df_stat_last_perf['GAME_DATE'] = pd.to_datetime(df_stat_last_perf['GAME_DATE'])
for team in list(set(df_stat['teamId'].tolist())):
    game_list_one_year_before = df_stat_last_perf[df_stat_last_perf['teamId'] == team].reset_index()
    for index, game in game_list_one_year_before.iterrows():
        adv = game['DUEL'].split()[2]
        game_list_against_adv = game_list_one_year_before[(game_list_one_year_before['GAME_DATE'] < game['GAME_DATE']) & (game_list_one_year_before['GAME_DATE'] > (game['GAME_DATE'] - pd.DateOffset(years=2))) & (game_list_one_year_before['DUEL'].str.contains(adv))]
        df_stat_last_perf.loc[game['index'], 'W_CONFR_D'] = (game_list_against_adv['WL'] == "W").sum()

In [228]:
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10,TOTAL_POINTS,teamName,W_CONFR_D
0,0021300015,1610612757,2013-10-30,POR @ PHX,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91,Portland Trail Blazers,0.0
1,0021300029,1610612757,2013-11-01,POR @ DEN,W,0.0,0.407000,0.30800,0.708000,96.200000,...,14.900000,0.4570,0.4970,94.740000,95.000000,79.170,0.410000,113,Portland Trail Blazers,0.0
2,0021300039,1610612757,2013-11-02,POR vs. SAS,W,0.1,0.417000,0.47200,0.720500,104.250000,...,11.050000,0.4760,0.5065,97.260000,95.750000,79.795,0.503500,115,Portland Trail Blazers,0.0
3,0021300058,1610612757,2013-11-05,POR vs. HOU,L,0.2,0.463333,0.44800,0.778667,108.466667,...,12.866667,0.5190,0.5520,97.486667,96.333333,80.280,0.535667,101,Portland Trail Blazers,0.0
4,0021300084,1610612757,2013-11-08,POR vs. SAC,W,0.2,0.451000,0.41675,0.747750,105.925000,...,13.175000,0.5070,0.5405,98.455000,97.000000,80.835,0.494750,104,Portland Trail Blazers,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301138,1610612756,2024-04-07,PHX vs. NOP,L,0.7,0.509400,0.43390,0.808600,117.230000,...,16.180000,0.5985,0.6254,99.010000,97.650000,81.375,0.537100,105,Phoenix Suns,4.0
24078,0022301156,1610612756,2024-04-09,PHX vs. LAC,L,0.7,0.495600,0.42740,0.814800,114.890000,...,16.420000,0.5847,0.6129,98.898000,97.300000,81.084,0.535500,92,Phoenix Suns,2.0
24079,0022301165,1610612756,2024-04-10,PHX @ LAC,W,0.6,0.479300,0.40160,0.825500,112.750000,...,14.920000,0.5623,0.5968,98.934000,97.450000,81.209,0.521500,124,Phoenix Suns,2.0
24080,0022301185,1610612756,2024-04-12,PHX @ SAC,W,0.6,0.472300,0.38390,0.829900,111.140000,...,14.390000,0.5499,0.5833,99.452000,98.250000,81.875,0.520000,108,Phoenix Suns,4.0
24081,0022301194,1610612756,2024-04-14,PHX @ MIN,W,0.6,0.465300,0.37560,0.844000,109.410000,...,15.400000,0.5450,0.5814,98.902000,97.750000,81.458,0.511500,125,Phoenix Suns,5.0

In [229]:
df_stat_last_perf = df_stat_last_perf.sort_values(by='gameId')
df_stat_last_perf.reset_index(drop=True, inplace=True)
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10,TOTAL_POINTS,teamName,W_CONFR_D
0,0021300001,1610612753,2013-10-29,ORL @ IND,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87,Orlando Magic,0.0
1,0021300001,1610612754,2013-10-29,IND vs. ORL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97,Indiana Pacers,0.0
2,0021300002,1610612748,2013-10-29,MIA vs. CHI,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107,Miami Heat,0.0
3,0021300002,1610612741,2013-10-29,CHI @ MIA,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95,Chicago Bulls,0.0
4,0021300003,1610612747,2013-10-29,LAL vs. LAC,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,Los Angeles Lakers,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301228,1610612756,2023-12-08,PHX vs. SAC,L,0.7,0.4796,0.3954,0.8557,116.10,...,14.64,0.5493,0.6058,99.228,96.250,80.209,0.5458,106,Phoenix Suns,3.0
24078,0022301229,1610612754,2023-12-07,IND @ MIL,W,0.5,0.5218,0.3864,0.7809,121.79,...,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054,128,Indiana Pacers,2.0
24079,0022301229,1610612749,2023-12-07,MIL vs. IND,L,0.8,0.5201,0.3984,0.7737,122.88,...,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446,119,Milwaukee Bucks,5.0
24080,0022301230,1610612740,2023-12-07,NOP @ LAL,L,0.6,0.5006,0.3545,0.7908,118.61,...,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425,89,New Orleans Pelicans,4.0
24081,0022301230,1610612747,2023-12-07,LAL vs. NOP,W,0.7,0.4767,0.3244,0.7606,108.47,...,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255,133,Los Angeles Lakers,3.0

In [230]:
for game_id in list(set(df_stat_last_perf['gameId'].tolist())):
    df_game = df_stat_last_perf[df_stat_last_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10,TOTAL_POINTS,teamName,W_CONFR_D
0,0021300001,1610612754,2013-10-29,IND vs. ORL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97,Indiana Pacers,0.0
1,0021300001,1610612753,2013-10-29,ORL @ IND,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87,Orlando Magic,0.0
2,0021300002,1610612748,2013-10-29,MIA vs. CHI,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107,Miami Heat,0.0
3,0021300002,1610612741,2013-10-29,CHI @ MIA,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95,Chicago Bulls,0.0
4,0021300003,1610612747,2013-10-29,LAL vs. LAC,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116,Los Angeles Lakers,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301228,1610612758,2023-12-08,SAC @ PHX,W,0.6,0.4738,0.3759,0.7684,114.96,...,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814,114,Sacramento Kings,3.0
24078,0022301229,1610612749,2023-12-07,MIL vs. IND,L,0.8,0.5201,0.3984,0.7737,122.88,...,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446,119,Milwaukee Bucks,5.0
24079,0022301229,1610612754,2023-12-07,IND @ MIL,W,0.5,0.5218,0.3864,0.7809,121.79,...,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054,128,Indiana Pacers,2.0
24080,0022301230,1610612747,2023-12-07,LAL vs. NOP,W,0.7,0.4767,0.3244,0.7606,108.47,...,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255,133,Los Angeles Lakers,3.0
24081,0022301230,1610612740,2023-12-07,NOP @ LAL,L,0.6,0.5006,0.3545,0.7908,118.61,...,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425,89,New Orleans Pelicans,4.0

In [231]:
df_stat_last_perf.to_csv('../dataset/team_stat_last_'+ nb_games +'.csv', index=False)