In [16]:
import pandas as pd

In [17]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
nb_games = "10"
df_stat

,teamId,gameId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,1610612748,0021300002,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
1,1610612747,0021300003,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
2,1610612746,0021300003,2013-10-29,LAC @ LAL,L,0,1,0.000,240,41,...,16.3,0.542,0.553,1.0,0.200,102.72,98.5,82.08,98.0,0.497
3,1610612754,0021300001,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
4,1610612741,0021300002,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,1610612739,0022301187,2024-04-14,CLE vs. CHA,L,48,34,0.585,240,44,...,14.4,0.559,0.567,1.0,0.196,97.40,97.0,80.83,97.0,0.427
24078,1610612761,0022301189,2024-04-14,TOR @ MIA,L,25,57,0.305,240,38,...,19.2,0.472,0.519,1.0,0.198,103.30,100.0,83.33,99.0,0.369
24079,1610612742,0022301196,2024-04-14,DAL @ OKC,L,50,32,0.610,240,32,...,14.3,0.371,0.412,1.0,0.199,107.76,105.5,87.92,105.0,0.246
24080,1610612754,0022301188,2024-04-14,IND vs. ATL,W,47,35,0.573,240,65,...,15.0,0.745,0.752,1.0,0.193,108.64,107.0,89.17,107.0,0.649
24081,1610612766,0022301187,2024-04-14,CHA @ CLE,W,21,61,0.256,240,46,...,10.3,0.610,0.626,1.0,0.198,97.40,97.0,80.83,97.0,0.573

In [19]:
df_stat_last_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L'+nb_games, 'PCT_TIR_REUSSI_L'+nb_games,'PCT_3PTS_L'+nb_games, 
                           'PCT_LANCER_FRANC_L'+nb_games,'estimatedOffensiveRating_L'+nb_games, 'offensiveRating_L'+nb_games,
                           'estimatedDefensiveRating_L'+nb_games,
                           'defensiveRating_L'+nb_games,'estimatedNetRating_L'+nb_games, 'netRating_L'+nb_games, 'assistPercentage_L'+nb_games,
                           'assistToTurnover_L'+nb_games, 'assistRatio_L'+nb_games,'estimatedTeamTurnoverPercentage_L'+nb_games, 'turnoverRatio_L'+nb_games,
                           'effectiveFieldGoalPercentage_L'+nb_games,'trueShootingPercentage_L'+nb_games, 'estimatedPace_L'+nb_games, 'pace_L'+nb_games,
                           'pacePer40_L'+nb_games, 'PIE_L'+nb_games])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_10_games = team_stats.iloc[max(0, index - int(nb_games)):index]
        df_last_10_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L"+nb_games : (df_last_10_games['WL'] == 'W').sum() / int(nb_games),
                   "PCT_TIR_REUSSI_L"+nb_games : df_last_10_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L"+nb_games : df_last_10_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L"+nb_games : df_last_10_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L"+nb_games : df_last_10_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L"+nb_games : df_last_10_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L"+nb_games : df_last_10_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L"+nb_games : df_last_10_games['defensiveRating'].mean(),
                   "estimatedNetRating_L"+nb_games : df_last_10_games['estimatedNetRating'].mean(),
                   "netRating_L"+nb_games : df_last_10_games['netRating'].mean(),
                   "assistPercentage_L"+nb_games : df_last_10_games['assistPercentage'].mean(),
                   "assistToTurnover_L"+nb_games : df_last_10_games['assistToTurnover'].mean(),
                   "assistRatio_L"+nb_games : df_last_10_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L"+nb_games : df_last_10_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L"+nb_games : df_last_10_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L"+nb_games : df_last_10_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L"+nb_games : df_last_10_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L"+nb_games : df_last_10_games['estimatedPace'].mean(),
                   "pace_L"+nb_games : df_last_10_games['pace'].mean(),
                   "pacePer40_L"+nb_games : df_last_10_games['pacePer40'].mean(),
                   "PIE_L"+nb_games : df_last_10_games['PIE'].mean()}
        df_stat_last_perf.loc[len(df_stat_last_perf)] = new_row
        index += 1
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,0021300012,1610612737,2013-10-30,ATL @ DAL,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0021300023,1610612737,2013-11-01,ATL vs. TOR,W,0.0,0.487000,0.333000,0.771000,105.400000,...,1.590000,19.900000,16.441000,16.300,0.539000,0.596000,101.980000,103.500000,86.250000,0.46700
2,0021300046,1610612737,2013-11-03,ATL @ LAL,L,0.1,0.477500,0.384000,0.708000,105.450000,...,1.720000,19.350000,14.946500,15.000,0.535500,0.579500,99.190000,99.250000,82.710000,0.52700
3,0021300059,1610612737,2013-11-05,ATL @ SAC,W,0.1,0.466333,0.392333,0.651333,103.166667,...,1.813333,19.066667,14.113333,14.100,0.521667,0.555667,101.293333,101.333333,84.446667,0.51000
4,0021300071,1610612737,2013-11-07,ATL @ DEN,L,0.2,0.470000,0.385250,0.671250,104.325000,...,1.825000,19.200000,14.177000,14.225,0.524000,0.558750,100.305000,100.125000,83.440000,0.52225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301130,1610612743,2024-04-06,DEN vs. ATL,W,0.6,0.475700,0.386000,0.800100,113.260000,...,2.483000,20.950000,12.717900,12.870,0.542200,0.576500,98.660000,96.600000,80.499000,0.52930
24078,0022301154,1610612743,2024-04-09,DEN @ UTA,W,0.7,0.491900,0.399200,0.795000,115.680000,...,2.382000,21.440000,13.485000,13.660,0.564300,0.595200,99.454000,97.550000,81.291000,0.53910
24079,0022301164,1610612743,2024-04-10,DEN vs. MIN,W,0.7,0.488900,0.385100,0.763200,115.370000,...,2.529000,21.660000,12.770000,12.960,0.560200,0.588000,99.592000,97.300000,81.083000,0.54890
24080,0022301180,1610612743,2024-04-12,DEN @ SAS,L,0.7,0.490700,0.399100,0.734700,115.390000,...,2.440000,21.580000,13.160400,13.400,0.565100,0.589400,99.696000,97.400000,81.166000,0.54780
24081,0022301193,1610612743,2024-04-14,DEN @ MEM,W,0.6,0.496100,0.401900,0.752000,115.540000,...,2.605000,22.040000,12.629700,12.900,0.572800,0.594600,99.872000,97.500000,81.250000,0.54510

In [21]:
df_stat_last_perf = df_stat_last_perf.sort_values(by='gameId')
df_stat_last_perf.reset_index(drop=True, inplace=True)
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,0021300001,1610612754,2013-10-29,IND vs. ORL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0021300001,1610612753,2013-10-29,ORL @ IND,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0021300002,1610612748,2013-10-29,MIA vs. CHI,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0021300002,1610612741,2013-10-29,CHI @ MIA,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0021300003,1610612747,2013-10-29,LAL vs. LAC,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301228,1610612756,2023-12-08,PHX vs. SAC,L,0.7,0.4796,0.3954,0.8557,116.10,...,1.974,19.04,14.2232,14.64,0.5493,0.6058,99.228,96.250,80.209,0.5458
24078,0022301229,1610612754,2023-12-07,IND @ MIL,W,0.5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
24079,0022301229,1610612749,2023-12-07,MIL vs. IND,L,0.8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
24080,0022301230,1610612747,2023-12-07,LAL vs. NOP,W,0.7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
24081,0022301230,1610612740,2023-12-07,NOP @ LAL,L,0.6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [23]:
for game_id in list(set(df_stat_last_perf['gameId'].tolist())):
    df_game = df_stat_last_perf[df_stat_last_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,0021300001,1610612754,2013-10-29,IND vs. ORL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0021300001,1610612753,2013-10-29,ORL @ IND,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0021300002,1610612748,2013-10-29,MIA vs. CHI,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0021300002,1610612741,2013-10-29,CHI @ MIA,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0021300003,1610612747,2013-10-29,LAL vs. LAC,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24077,0022301228,1610612758,2023-12-08,SAC @ PHX,W,0.6,0.4738,0.3759,0.7684,114.96,...,2.129,19.61,12.9317,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814
24078,0022301229,1610612749,2023-12-07,MIL vs. IND,L,0.8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
24079,0022301229,1610612754,2023-12-07,IND @ MIL,W,0.5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
24080,0022301230,1610612747,2023-12-07,LAL vs. NOP,W,0.7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
24081,0022301230,1610612740,2023-12-07,NOP @ LAL,L,0.6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [24]:
df_stat_last_perf.to_csv('../dataset/team_stat_last_'+ nb_games +'.csv', index=False)