In [1]:
import pandas as pd

In [2]:
team_adv_stats = pd.read_csv('../dataset/team_adv_stats.csv', dtype={'teamId': str, 'gameId': str})
team_stat = pd.read_csv('../dataset/team_stat.csv',dtype={'Team_ID': str, 'Game_ID': str})

In [3]:
team_stat = team_stat.rename(columns={'Team_ID': 'teamId', 'Game_ID': 'gameId'})
team_stat

,teamId,gameId,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1610612747,0021301221,"APR 16, 2014",LAL @ SAS,W,27,55,0.329,240,45,...,0.706,6,44,50,29,4,2,9,17,113
1,1610612747,0021301211,"APR 14, 2014",LAL @ UTA,W,26,55,0.321,240,45,...,0.864,9,27,36,31,11,6,13,16,119
2,1610612747,0021301203,"APR 13, 2014",LAL vs. MEM,L,25,55,0.313,240,35,...,0.818,5,27,32,29,9,5,15,15,90
3,1610612747,0021301188,"APR 11, 2014",LAL vs. GSW,L,25,54,0.316,240,35,...,0.800,8,34,42,23,10,2,15,12,95
4,1610612747,0021301161,"APR 08, 2014",LAL vs. HOU,L,25,53,0.321,240,44,...,0.800,5,28,33,38,8,7,11,20,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26413,1610612759,0022300131,"NOV 02, 2023",SAS @ PHX,W,3,2,0.600,240,51,...,0.923,9,32,41,37,7,5,8,21,132
26414,1610612759,0022300113,"OCT 31, 2023",SAS @ PHX,W,2,2,0.500,240,43,...,0.750,8,29,37,25,10,9,12,17,115
26415,1610612759,0022300099,"OCT 29, 2023",SAS @ LAC,L,1,2,0.333,240,30,...,0.750,6,31,37,21,9,6,25,23,83
26416,1610612759,0022300083,"OCT 27, 2023",SAS vs. HOU,W,1,1,0.500,265,46,...,0.750,12,31,43,32,11,4,18,17,126
26417,1610612759,0022300073,"OCT 25, 2023",SAS vs. DAL,L,0,1,0.000,240,46,...,0.727,9,36,45,33,8,5,19,23,119

In [4]:
team_stat.columns= ['teamId', 'gameId', 'GAME_DATE', 'DUEL', 'WL', 'NB_VICTOIRE',
       'NB_DEFAITE', 'PCT_VICTOIRE', 'DUREE_MATCH', 'TIR REUSSI', 'TIR TENTE',
       'PCT_TIR_REUSSI', '3PTS_REUSSI', '3PTS_TENTE', 'PCT_3PTS',
       'LANCER_FRANC_REUSSI', 'LANCER_FRANC_TENTE', 'PCT_LANCER_FRANC',
       'REBOND_OFF', 'REBOND_DEF', 'REBOND', 'PASSE_D', 'INTERCEPTION',
       'TIR_CONTRE', 'BALLON_PERDU', 'FAUTES', 'TOTAL_POINTS']
team_stat

,teamId,gameId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,PCT_LANCER_FRANC,REBOND_OFF,REBOND_DEF,REBOND,PASSE_D,INTERCEPTION,TIR_CONTRE,BALLON_PERDU,FAUTES,TOTAL_POINTS
0,1610612747,0021301221,"APR 16, 2014",LAL @ SAS,W,27,55,0.329,240,45,...,0.706,6,44,50,29,4,2,9,17,113
1,1610612747,0021301211,"APR 14, 2014",LAL @ UTA,W,26,55,0.321,240,45,...,0.864,9,27,36,31,11,6,13,16,119
2,1610612747,0021301203,"APR 13, 2014",LAL vs. MEM,L,25,55,0.313,240,35,...,0.818,5,27,32,29,9,5,15,15,90
3,1610612747,0021301188,"APR 11, 2014",LAL vs. GSW,L,25,54,0.316,240,35,...,0.800,8,34,42,23,10,2,15,12,95
4,1610612747,0021301161,"APR 08, 2014",LAL vs. HOU,L,25,53,0.321,240,44,...,0.800,5,28,33,38,8,7,11,20,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26413,1610612759,0022300131,"NOV 02, 2023",SAS @ PHX,W,3,2,0.600,240,51,...,0.923,9,32,41,37,7,5,8,21,132
26414,1610612759,0022300113,"OCT 31, 2023",SAS @ PHX,W,2,2,0.500,240,43,...,0.750,8,29,37,25,10,9,12,17,115
26415,1610612759,0022300099,"OCT 29, 2023",SAS @ LAC,L,1,2,0.333,240,30,...,0.750,6,31,37,21,9,6,25,23,83
26416,1610612759,0022300083,"OCT 27, 2023",SAS vs. HOU,W,1,1,0.500,265,46,...,0.750,12,31,43,32,11,4,18,17,126
26417,1610612759,0022300073,"OCT 25, 2023",SAS vs. DAL,L,0,1,0.000,240,46,...,0.727,9,36,45,33,8,5,19,23,119

In [5]:
merged_df = pd.merge(team_stat, team_adv_stats, on=['gameId', 'teamId'])
merged_df

,teamId,gameId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,1610612747,0021301221,"APR 16, 2014",LAL @ SAS,W,27,55,0.329,240,45,...,8.7,0.555,0.574,1.0,0.199,102.44,102.50,85.42,103.0,0.576
1,1610612747,0021301211,"APR 14, 2014",LAL @ UTA,W,26,55,0.321,240,45,...,13.7,0.610,0.649,1.0,0.201,97.24,95.50,79.58,95.0,0.586
2,1610612747,0021301203,"APR 13, 2014",LAL vs. MEM,L,25,55,0.313,240,35,...,18.3,0.506,0.530,1.0,0.194,95.78,93.50,77.92,93.0,0.423
3,1610612747,0021301188,"APR 11, 2014",LAL vs. GSW,L,25,54,0.316,240,35,...,14.3,0.444,0.486,1.0,0.202,104.26,105.00,87.50,105.0,0.409
4,1610612747,0021301161,"APR 08, 2014",LAL vs. HOU,L,25,53,0.321,240,44,...,9.7,0.537,0.589,1.0,0.199,113.86,113.00,94.17,113.0,0.431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26413,1610612759,0022300131,"NOV 02, 2023",SAS @ PHX,W,3,2,0.600,240,51,...,7.9,0.612,0.636,1.0,0.199,101.58,100.00,83.33,101.0,0.551
26414,1610612759,0022300113,"OCT 31, 2023",SAS @ PHX,W,2,2,0.500,240,43,...,11.9,0.543,0.570,1.0,0.197,103.70,100.50,83.75,101.0,0.479
26415,1610612759,0022300099,"OCT 29, 2023",SAS @ LAC,L,1,2,0.333,240,30,...,24.0,0.444,0.477,1.0,0.200,106.64,103.50,86.25,104.0,0.281
26416,1610612759,0022300083,"OCT 27, 2023",SAS vs. HOU,W,1,1,0.500,265,46,...,16.2,0.559,0.593,1.0,0.198,103.30,100.53,83.77,111.0,0.553
26417,1610612759,0022300073,"OCT 25, 2023",SAS vs. DAL,L,0,1,0.000,240,46,...,17.8,0.579,0.603,1.0,0.199,108.40,107.00,89.17,107.0,0.507

In [6]:
# Convertir la colonne 'GAME_DATE' en format de date
merged_df['GAME_DATE'] = pd.to_datetime(merged_df['GAME_DATE'], format='%b %d, %Y')

# Trier le DataFrame en fonction de la colonne 'GAME_DATE'
df_sorted = merged_df.sort_values(by='GAME_DATE')

In [7]:
df_sorted = df_sorted.loc[(df_sorted["GAME_DATE"] < pd.to_datetime('2020-05-01')) | (df_sorted["GAME_DATE"] > pd.to_datetime('2021-09-01'))]
#df_sorted = df_sorted.loc[(df_sorted["GAME_DATE"] < pd.to_datetime('2022-05-01')) | (df_sorted["GAME_DATE"] > pd.to_datetime('2023-09-01'))]
df_sorted.to_csv('../dataset/merged_team_stats.csv', index=False)
df_sorted

,teamId,gameId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
6236,1610612748,0021300002,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
81,1610612747,0021300003,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
17673,1610612746,0021300003,2013-10-29,LAC @ LAL,L,0,1,0.000,240,41,...,16.3,0.542,0.553,1.0,0.200,102.72,98.5,82.08,98.0,0.497
8002,1610612754,0021300001,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
8885,1610612741,0021300002,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3431,1610612739,0022301187,2024-04-14,CLE vs. CHA,L,48,34,0.585,240,44,...,14.4,0.559,0.567,1.0,0.196,97.40,97.0,80.83,97.0,0.427
12238,1610612761,0022301189,2024-04-14,TOR @ MIA,L,25,57,0.305,240,38,...,19.2,0.472,0.519,1.0,0.198,103.30,100.0,83.33,99.0,0.369
21924,1610612742,0022301196,2024-04-14,DAL @ OKC,L,50,32,0.610,240,32,...,14.3,0.371,0.412,1.0,0.199,107.76,105.5,87.92,105.0,0.246
8722,1610612754,0022301188,2024-04-14,IND vs. ATL,W,47,35,0.573,240,65,...,15.0,0.745,0.752,1.0,0.193,108.64,107.0,89.17,107.0,0.649
13113,1610612766,0022301187,2024-04-14,CHA @ CLE,W,21,61,0.256,240,46,...,10.3,0.610,0.626,1.0,0.198,97.40,97.0,80.83,97.0,0.573