In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat_last_30 = pd.read_csv('../dataset/team_stat_last_30.csv', dtype=data_type )
df_stat_last_30

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L30,PCT_TIR_REUSSI_L30,PCT_3PTS_L30,PCT_LANCER_FRANC_L30,estimatedOffensiveRating_L30,...,assistToTurnover_L30,assistRatio_L30,estimatedTeamTurnoverPercentage_L30,turnoverRatio_L30,effectiveFieldGoalPercentage_L30,trueShootingPercentage_L30,estimatedPace_L30,pace_L30,pacePer40_L30,PIE_L30
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,16,0.468467,0.347433,0.745500,114.113333,...,2.368000,19.383333,12.439667,12.626667,0.547867,0.579700,101.856333,100.078333,83.399000,0.488067
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,20,0.496033,0.380133,0.770367,116.750000,...,2.038667,18.640000,13.339200,13.526667,0.577367,0.607833,103.455667,101.882667,84.902000,0.506533
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,14,0.501800,0.386333,0.789500,116.856667,...,2.352000,20.170000,13.160267,13.536667,0.576800,0.608933,106.488667,103.900000,86.583333,0.491767
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,19,0.489467,0.344633,0.762233,111.460000,...,2.003667,18.933333,13.940133,14.146667,0.549833,0.586500,102.511000,100.783000,83.986000,0.521200
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,17,0.483767,0.369100,0.776800,113.220000,...,1.988667,18.690000,13.575633,13.790000,0.546167,0.585400,101.506000,99.751000,83.126000,0.519500

In [3]:
df_stat_last_30['col'] = df_stat_last_30.groupby('gameId').cumcount() + 1
df_stat_flatten = df_stat_last_30.pivot_table(index='gameId', columns=df_stat_last_30.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L30',
       'PCT_TIR_REUSSI_L30', 'PCT_3PTS_L30', 'PCT_LANCER_FRANC_L30',
       'estimatedOffensiveRating_L30', 'offensiveRating_L30',
       'estimatedDefensiveRating_L30', 'defensiveRating_L30',
       'estimatedNetRating_L30', 'netRating_L30', 'assistPercentage_L30',
       'assistToTurnover_L30', 'assistRatio_L30',
       'estimatedTeamTurnoverPercentage_L30', 'turnoverRatio_L30',
       'effectiveFieldGoalPercentage_L30', 'trueShootingPercentage_L30',
       'estimatedPace_L30', 'pace_L30', 'pacePer40_L30', 'PIE_L30'], aggfunc='first')

df_stat_flatten.columns = [f'col{col[1]}' for col in df_stat_flatten.columns]


df_stat_flatten = df_stat_flatten.reset_index()
#df_stat_flatten

In [4]:
df_stat_flatten

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.080000,NaN,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,7,14,0.336967,0.372667,0.781567,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,23,17,0.368067,0.381700,0.774233,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,19,16,0.377867,0.347433,0.828667,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,20,14,0.380133,0.386333,0.770367,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,19,17,0.344633,0.369100,0.762233,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000

In [5]:
print(len(['DUEL', 'GAME_DATE', 'NB_WIN_L30', 'PCT_3PT_L30', 'PCT_LANCER_FRANC_L30', 'PCT_TIR_REUSSI_L30', 'PIE_L30', 'WL', 'assistPercentage_L30', 'assistRatio_L30', 'assistToTurnover_L30', 'defensiveRating_L30', 'effectiveFieldGoalPercentage_L30', 'estimatedDefensiveRating_L30', 'estimatedNetRating_L30', 'estimatedOffensiveRating_L30', 'estimatedPace_L30', 'estimatedTeamTurnoverPercentage_L30', 'netRating_L30', 'offensiveRating_L30','pacePer40_L30', 'pace_L30','teamId', 'trueShootingPercentage_L30', 'turnoverRatio_L30']))

25

In [6]:
df_stat_flatten.columns = ['gameId', 'H_DUEL', 'A_DUEL', 'H_GAME_DATE', 'A_GAME_DATE', 'H_NB_WIN_L30', 'A_NB_WIN_L30', 'H_PCT_3PT_L30', 'A_PCT_3PT_L30', 'H_PCT_LANCER_FRANC_L30', 'A_PCT_LANCER_FRANC_L30', 'H_PCT_TIR_REUSSI_L30', 'A_PCT_TIR_REUSSI_L30', 'H_PIE_L30', 'A_PIE_L30', 'H_WL', 'A_WL', 'H_assistPercentage_L30', 'A_assistPercentage_L30', 'H_assistRatio_L30', 'A_assistRatio_L30', 'H_assistToTurnover_L30', 'A_assistToTurnover_L30', 'H_defensiveRating_L30', 'A_defensiveRating_L30', 'H_effectiveFieldGoalPercentage_L30', 'A_effectiveFieldGoalPercentage_L30', 'H_estimatedDefensiveRating_L30', 'A_estimatedDefensiveRating_L30', 'H_estimatedNetRating_L30', 'A_estimatedNetRating_L30', 'H_estimatedOffensiveRating_L30', 'A_estimatedOffensiveRating_L30', 'H_estimatedPace_L30', 'A_estimatedPace_L30', 'H_estimatedTeamTurnoverPercentage_L30', 'A_estimatedTeamTurnoverPercentage_L30', 'H_netRating_L30', 'A_netRating_L30', 'H_offensiveRating_L30', 'A_offensiveRating_L30', 'H_pacePer40_L30', 'A_pacePer40_L30', 'H_pace_L30', 'A_pace_L30', 'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L30', 'A_trueShootingPercentage_L30', 'H_turnoverRatio_L30', 'A_turnoverRatio_L30']
df_stat_flatten

,gameId,H_DUEL,A_DUEL,H_GAME_DATE,A_GAME_DATE,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,H_PCT_LANCER_FRANC_L30,...,H_pacePer40_L30,A_pacePer40_L30,H_pace_L30,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.080000,NaN,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,7,14,0.336967,0.372667,0.781567,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,23,17,0.368067,0.381700,0.774233,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,19,16,0.377867,0.347433,0.828667,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,20,14,0.380133,0.386333,0.770367,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,19,17,0.344633,0.369100,0.762233,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000

In [7]:
df_stat_flatten = df_stat_flatten.drop('A_DUEL', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_GAME_DATE', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_WL', axis=1)
df_stat_flatten = df_stat_flatten.rename(columns={'H_DUEL': 'DUEL', 'H_GAME_DATE': 'GAME_DATE', 'H_WL': 'HOME_WON'})
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('W', 1)
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('L', 0)
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,H_PCT_LANCER_FRANC_L30,A_PCT_LANCER_FRANC_L30,H_PCT_TIR_REUSSI_L30,...,H_pacePer40_L30,A_pacePer40_L30,H_pace_L30,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,NaN,82.080000,NaN,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,7,14,0.336967,0.372667,0.781567,0.751033,0.438500,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12970,22301227,BOS vs. NYK,2023-12-08,23,17,0.368067,0.381700,0.774233,0.742067,0.480233,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12971,22301228,PHX vs. SAC,2023-12-08,19,16,0.377867,0.347433,0.828667,0.745500,0.470700,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12972,22301229,MIL vs. IND,2023-12-07,20,14,0.380133,0.386333,0.770367,0.789500,0.496033,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12973,22301230,LAL vs. NOP,2023-12-07,19,17,0.344633,0.369100,0.762233,0.776800,0.489467,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000

In [8]:
df_stat_flatten.to_csv('../dataset/team_stat_flatten_L30.csv', index=False)

In [9]:
nba_elo = pd.read_csv('../dataset/nba_elo.csv', dtype=data_type )

In [10]:
nba_elo_copy= nba_elo.copy()
nba_elo_copy

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,elo1_post,elo2_post,score1,score2,is_home
0,1946-11-01,1947,0,NaN,TRH,NYK,1300.000000,1300.000000,0.640065,0.359935,1293.276700,1306.723300,66,68,1
1,1946-11-01,1947,0,NaN,NYK,TRH,1300.000000,1300.000000,0.359935,0.640065,1306.723300,1293.276700,68,66,0
2,1946-11-02,1947,0,NaN,PRO,BOS,1300.000000,1300.000000,0.640065,0.359935,1305.154200,1294.845800,59,53,1
3,1946-11-02,1947,0,NaN,STB,PIT,1300.000000,1300.000000,0.640065,0.359935,1304.690800,1295.309200,56,51,1
4,1946-11-02,1947,0,NaN,CHS,NYK,1300.000000,1306.723300,0.631101,0.368899,1309.652100,1297.071200,63,47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148933,2024-03-30,2024,0,NaN,MEM,ORL,1325.023208,1523.156879,0.152362,0.847638,1319.643511,1528.536576,88,118,0
148934,2024-03-30,2024,0,NaN,MIL,ATL,1586.179279,1493.120229,0.490012,0.509988,1596.162979,1483.136529,122,113,0
148935,2024-03-30,2024,0,NaN,NOP,BOS,1635.324867,1758.207851,0.467116,0.532884,1624.649366,1768.883352,92,104,1
148936,2024-03-30,2024,0,NaN,ORL,MEM,1523.156879,1325.023208,0.847638,0.152362,1528.536576,1319.643511,118,88,1
148937,2024-03-30,2024,0,NaN,ATL,MIL,1493.120229,1586.179279,0.509988,0.490012,1483.136529,1596.162979,113,122,1

In [11]:
columns_list = nba_elo_copy.columns.tolist()

print(columns_list)

['date', 'season', 'neutral', 'playoff', 'team1', 'team2', 'elo1_pre', 'elo2_pre', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']

In [12]:
columns_to_drop = ['season',  'neutral', 'playoff', 'team2', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']  # Liste des noms des colonnes à supprimer
nba_elo_copy_drop= nba_elo_copy.drop(columns=columns_to_drop)

In [13]:
nba_elo_copy_drop

              date team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [14]:
nba_elo_copy_drop['team1'] = nba_elo_copy_drop['team1'].replace({'PHO': 'PHX', 'BRK': 'BKN', 'CHO': 'CHA'})

In [15]:
df_stat_flatten['team1'] = df_stat_flatten['DUEL'].str.split(' vs. ').str[0]

In [16]:
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,H_PCT_LANCER_FRANC_L30,A_PCT_LANCER_FRANC_L30,H_PCT_TIR_REUSSI_L30,...,A_pacePer40_L30,H_pace_L30,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30,team1
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,82.080000,NaN,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,7,14,0.336967,0.372667,0.781567,0.751033,0.438500,...,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333,POR
12970,22301227,BOS vs. NYK,2023-12-08,23,17,0.368067,0.381700,0.774233,0.742067,0.480233,...,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667,BOS
12971,22301228,PHX vs. SAC,2023-12-08,19,16,0.377867,0.347433,0.828667,0.745500,0.470700,...,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667,PHX
12972,22301229,MIL vs. IND,2023-12-07,20,14,0.380133,0.386333,0.770367,0.789500,0.496033,...,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667,MIL
12973,22301230,LAL vs. NOP,2023-12-07,19,17,0.344633,0.369100,0.762233,0.776800,0.489467,...,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000,LAL

In [17]:
new_column_names = {'date':'GAME_DATE' }
nba_elo_copy_drop_rename= nba_elo_copy_drop.rename(columns=new_column_names)
nba_elo_copy_drop_rename

         GAME_DATE team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [18]:
result = pd.merge(df_stat_flatten, nba_elo_copy_drop_rename, on=['GAME_DATE', 'team1'])

In [19]:
result

,gameId,DUEL,GAME_DATE,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,H_PCT_LANCER_FRANC_L30,A_PCT_LANCER_FRANC_L30,H_PCT_TIR_REUSSI_L30,...,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30,team1,elo1_pre,elo2_pre
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,7,14,0.336967,0.372667,0.781567,0.751033,0.438500,...,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,23,17,0.368067,0.381700,0.774233,0.742067,0.480233,...,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,19,16,0.377867,0.347433,0.828667,0.745500,0.470700,...,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,20,14,0.380133,0.386333,0.770367,0.789500,0.496033,...,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,19,17,0.344633,0.369100,0.762233,0.776800,0.489467,...,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000,LAL,1541.467385,1543.760516

In [20]:
new_column_names = {'elo1_pre':'A_ELO' , 'elo2_pre': 'H_ELO'}
result= result.rename(columns=new_column_names)
result

,gameId,DUEL,GAME_DATE,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,H_PCT_LANCER_FRANC_L30,A_PCT_LANCER_FRANC_L30,H_PCT_TIR_REUSSI_L30,...,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30,team1,A_ELO,H_ELO
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,7,14,0.336967,0.372667,0.781567,0.751033,0.438500,...,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,23,17,0.368067,0.381700,0.774233,0.742067,0.480233,...,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,19,16,0.377867,0.347433,0.828667,0.745500,0.470700,...,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,20,14,0.380133,0.386333,0.770367,0.789500,0.496033,...,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,19,17,0.344633,0.369100,0.762233,0.776800,0.489467,...,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000,LAL,1541.467385,1543.760516

In [21]:
new_order = ['gameId', 'DUEL','GAME_DATE','HOME_WON','H_ELO','A_ELO','H_NB_WIN_L30','A_NB_WIN_L30', 'H_PCT_3PT_L30',
       'A_PCT_3PT_L30', 'H_PCT_LANCER_FRANC_L30', 'A_PCT_LANCER_FRANC_L30',
       'H_PCT_TIR_REUSSI_L30', 'A_PCT_TIR_REUSSI_L30', 'H_PIE_L30',
       'A_PIE_L30',  'H_assistPercentage_L30',
       'A_assistPercentage_L30', 'H_assistRatio_L30', 'A_assistRatio_L30',
       'H_assistToTurnover_L30', 'A_assistToTurnover_L30',
       'H_defensiveRating_L30', 'A_defensiveRating_L30',
       'H_effectiveFieldGoalPercentage_L30',
       'A_effectiveFieldGoalPercentage_L30', 'H_estimatedDefensiveRating_L30',
       'A_estimatedDefensiveRating_L30', 'H_estimatedNetRating_L30',
       'A_estimatedNetRating_L30', 'H_estimatedOffensiveRating_L30',
       'A_estimatedOffensiveRating_L30', 'H_estimatedPace_L30',
       'A_estimatedPace_L30', 'H_estimatedTeamTurnoverPercentage_L30',
       'A_estimatedTeamTurnoverPercentage_L30', 'H_netRating_L30',
       'A_netRating_L30', 'H_offensiveRating_L30', 'A_offensiveRating_L30',
       'H_pacePer40_L30', 'A_pacePer40_L30', 'H_pace_L30', 'A_pace_L30',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L30',
       'A_trueShootingPercentage_L30', 'H_turnoverRatio_L30',
       'A_turnoverRatio_L30', 'team1']

# Réorganiser les colonnes
result = result.reindex(columns=new_order)

In [22]:
result = result.drop(columns=['team1'])

In [23]:
result = result.dropna()

In [24]:
result.to_csv('../dataset/team_stat_flatten_L30.csv', index=False)
result

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,...,H_pacePer40_L30,A_pacePer40_L30,H_pace_L30,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30
17,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.269000,0.231000,...,82.080000,78.330000,98.500000,94.000000,1610612741,1610612752,0.510000,0.573000,19.400000,23.400000
18,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.381000,0.556000,...,82.080000,87.080000,98.500000,104.500000,1610612746,1610612744,0.553000,0.650000,16.300000,14.300000
19,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.400000,0.333000,...,76.250000,77.500000,91.500000,93.000000,1610612766,1610612739,0.420000,0.495000,8.700000,15.100000
20,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.422000,0.455000,...,81.620000,76.670000,97.945000,92.000000,1610612753,1610612740,0.490000,0.478000,18.050000,16.300000
21,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.400000,0.381000,...,81.670000,84.580000,98.000000,101.500000,1610612764,1610612755,0.554000,0.629000,17.300000,17.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,7,14,0.336967,0.372667,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12970,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,23,17,0.368067,0.381700,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12971,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,19,16,0.377867,0.347433,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12972,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,20,14,0.380133,0.386333,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12973,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,19,17,0.344633,0.369100,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000

In [25]:
data_type = {"gameId": str, "teamId": str}
team_stat_flatten = pd.read_csv('../dataset/team_stat_flatten_L30.csv', dtype=data_type )
team_stat_flatten

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN_L30,A_NB_WIN_L30,H_PCT_3PT_L30,A_PCT_3PT_L30,...,H_pacePer40_L30,A_pacePer40_L30,H_pace_L30,A_pace_L30,H_teamId,A_teamId,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_turnoverRatio_L30,A_turnoverRatio_L30
0,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.269000,0.231000,...,82.080000,78.330000,98.500000,94.000000,1610612741,1610612752,0.510000,0.573000,19.400000,23.400000
1,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.381000,0.556000,...,82.080000,87.080000,98.500000,104.500000,1610612746,1610612744,0.553000,0.650000,16.300000,14.300000
2,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.400000,0.333000,...,76.250000,77.500000,91.500000,93.000000,1610612766,1610612739,0.420000,0.495000,8.700000,15.100000
3,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.422000,0.455000,...,81.620000,76.670000,97.945000,92.000000,1610612753,1610612740,0.490000,0.478000,18.050000,16.300000
4,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.400000,0.381000,...,81.670000,84.580000,98.000000,101.500000,1610612764,1610612755,0.554000,0.629000,17.300000,17.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,7,14,0.336967,0.372667,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12953,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,23,17,0.368067,0.381700,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12954,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,19,16,0.377867,0.347433,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12955,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,20,14,0.380133,0.386333,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12956,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,19,17,0.344633,0.369100,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000

In [26]:
team_stat_flatten.columns

Index(['gameId', 'DUEL', 'GAME_DATE', 'HOME_WON', 'H_ELO', 'A_ELO',
       'H_NB_WIN_L30', 'A_NB_WIN_L30', 'H_PCT_3PT_L30', 'A_PCT_3PT_L30',
       'H_PCT_LANCER_FRANC_L30', 'A_PCT_LANCER_FRANC_L30',
       'H_PCT_TIR_REUSSI_L30', 'A_PCT_TIR_REUSSI_L30', 'H_PIE_L30',
       'A_PIE_L30', 'H_assistPercentage_L30', 'A_assistPercentage_L30',
       'H_assistRatio_L30', 'A_assistRatio_L30', 'H_assistToTurnover_L30',
       'A_assistToTurnover_L30', 'H_defensiveRating_L30',
       'A_defensiveRating_L30', 'H_effectiveFieldGoalPercentage_L30',
       'A_effectiveFieldGoalPercentage_L30', 'H_estimatedDefensiveRating_L30',
       'A_estimatedDefensiveRating_L30', 'H_estimatedNetRating_L30',
       'A_estimatedNetRating_L30', 'H_estimatedOffensiveRating_L30',
       'A_estimatedOffensiveRating_L30', 'H_estimatedPace_L30',
       'A_estimatedPace_L30', 'H_estimatedTeamTurnoverPercentage_L30',
       'A_estimatedTeamTurnoverPercentage_L30', 'H_netRating_L30',
       'A_netRating_L30', 'H_offensiveRating_L30', 'A_offensiveRating_L30',
       'H_pacePer40_L30', 'A_pacePer40_L30', 'H_pace_L30', 'A_pace_L30',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L30',
       'A_trueShootingPercentage_L30', 'H_turnoverRatio_L30',
       'A_turnoverRatio_L30'],
      dtype='object')

In [27]:
team_stat_flatten = team_stat_flatten.drop(columns=['DUEL', 'GAME_DATE','H_teamId', 'A_teamId'])
colonne_a_supprimer = team_stat_flatten.columns[2:]
# Boucle sur chaque paire de colonnes pour calculer la différence
for colonne in colonne_a_supprimer:
    # Extraire le préfixe de la colonne ('H_' ou 'A_')
    prefixe = colonne[0:2]
    # Extraire le nom de la colonne sans le préfixe
    nom_colonne = colonne[2:]
    # Créer une nouvelle colonne pour stocker la différence
    team_stat_flatten[f'{nom_colonne}'] = team_stat_flatten.apply(lambda row: row[f'H_{nom_colonne}'] - row[f'A_{nom_colonne}'], axis=1)

team_stat_flatten = team_stat_flatten.drop(columns=colonne_a_supprimer)
       
team_stat_flatten

,gameId,HOME_WON,ELO,NB_WIN_L30,PCT_3PT_L30,PCT_LANCER_FRANC_L30,PCT_TIR_REUSSI_L30,PIE_L30,assistPercentage_L30,assistRatio_L30,...,estimatedNetRating_L30,estimatedOffensiveRating_L30,estimatedPace_L30,estimatedTeamTurnoverPercentage_L30,netRating_L30,offensiveRating_L30,pacePer40_L30,pace_L30,trueShootingPercentage_L30,turnoverRatio_L30
0,21300018,1,65.524500,-1,0.038000,-0.099000,-0.085000,-0.188000,0.185000,2.500000,...,-24.100000,-1.400000,4.060000,-4.495000,-18.500000,1.200000,3.750000,4.500000,-0.0630,-4.000000
1,21300019,1,-0.516500,-1,-0.175000,-0.218000,-0.041000,-0.206000,-0.080000,-3.600000,...,-36.800000,-16.200000,-2.460000,1.736000,-40.800000,-13.900000,-5.000000,-6.000000,-0.0970,2.000000
2,21300020,1,28.044400,-1,0.067000,-0.026000,-0.050000,-0.168000,-0.176000,-4.100000,...,-23.000000,-13.500000,-4.580000,-6.000000,-19.600000,-15.200000,-1.250000,-1.500000,-0.0750,-6.400000
3,21300021,1,112.602600,0,-0.033000,-0.204500,0.028500,-0.003500,-0.040500,0.000000,...,-4.450000,-2.050000,6.745000,1.312000,-2.600000,-0.600000,4.950000,5.945000,0.0120,1.750000
4,21300022,0,16.701200,-1,0.019000,-0.083000,-0.102000,-0.154000,0.118000,-0.700000,...,-13.700000,-7.200000,-3.840000,-0.206000,-14.100000,-7.700000,-2.910000,-3.500000,-0.0750,-0.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,0,131.401620,-7,-0.035700,0.030533,-0.036700,-0.068133,-0.018600,-1.946667,...,-12.630000,-13.510000,-0.594333,3.833167,-11.703333,-12.970000,-0.723000,-0.867667,-0.0575,4.030000
12953,22301227,1,-70.748046,6,-0.013633,0.032167,0.012433,0.043067,0.028633,1.240000,...,8.346667,1.593333,1.056333,0.148500,6.910000,0.933333,0.772667,0.928000,0.0229,0.073333
12954,22301228,0,-25.740716,3,0.030433,0.083167,0.002233,0.044533,-0.002567,-0.340000,...,3.826667,0.040000,-1.635333,1.121233,4.260000,1.000000,-1.851333,-2.221000,0.0070,1.253333
12955,22301229,0,-99.080644,6,-0.006200,-0.019133,-0.005767,0.014767,-0.048467,-1.530000,...,3.183333,-0.106667,-3.033000,0.178933,1.806667,-2.046667,-1.681333,-2.017333,-0.0011,-0.010000
12956,22301230,1,2.293131,2,-0.024467,-0.014567,0.005700,0.001700,0.007133,0.243333,...,-1.383333,-1.760000,1.005000,0.364500,-1.090000,-1.630000,0.860000,1.032000,0.0011,0.356667

In [28]:
team_stat_flatten.to_csv('../dataset/final_dataset_diff_L30.csv', index=False)