In [91]:
import pandas as pd

In [92]:
data_type = {"gameId": str, "teamId": str}
df_stat_last_10 = pd.read_csv('../dataset/team_stat_last_10.csv', dtype=data_type )
df_stat_last_10

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,6,0.4738,0.3759,0.7684,114.96,...,2.129,19.61,12.9317,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [93]:
df_stat_last_10['col'] = df_stat_last_10.groupby('gameId').cumcount() + 1
df_stat_flatten = df_stat_last_10.pivot_table(index='gameId', columns=df_stat_last_10.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN',
       'PCT_TIR_REUSSI_L10', 'PCT_3PTS_L10', 'PCT_LANCER_FRANC_L10',
       'estimatedOffensiveRating_L10', 'offensiveRating_L10',
       'estimatedDefensiveRating_L10', 'defensiveRating_L10',
       'estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10',
       'assistToTurnover_L10', 'assistRatio_L10',
       'estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10',
       'effectiveFieldGoalPercentage_L10', 'trueShootingPercentage_L10',
       'estimatedPace_L10', 'pace_L10', 'pacePer40_L10', 'PIE_L10'], aggfunc='first')

df_stat_flatten.columns = [f'col{col[1]}' for col in df_stat_flatten.columns]


df_stat_flatten = df_stat_flatten.reset_index()
#df_stat_flatten

In [94]:
df_stat_flatten

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,3,4,0.3744,0.3463,0.7976,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,7,7,0.3545,0.3853,0.7753,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,7,6,0.3954,0.3759,0.8557,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,8,5,0.3984,0.3864,0.7737,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,7,6,0.3244,0.3545,0.7606,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [95]:
print(len(['DUEL', 'GAME_DATE', 'NB_WIN', 'PCT_3PT_L10', 'PCT_LANCER_FRANC_L10', 'PCT_TIR_REUSSI_L10', 'PIE_L10', 'WL', 'assistPercentage_L10', 'assistRatio_L10', 'assistToTurnover_L10', 'defensiveRating_L10', 'effectiveFieldGoalPercentage_L10', 'estimatedDefensiveRating_L10', 'estimatedNetRating_L10', 'estimatedOffensiveRating_L10', 'estimatedPace_L10', 'estimatedTeamTurnoverPercentage_L10', 'netRating_L10', 'offensiveRating_L10','pacePer40_L10', 'pace_L10','teamId', 'trueShootingPercentage_L10', 'turnoverRatio_L10']))

25

In [96]:
df_stat_flatten.columns = ['gameId', 'H_DUEL', 'A_DUEL', 'H_GAME_DATE', 'A_GAME_DATE', 'H_NB_WIN', 'A_NB_WIN', 'H_PCT_3PT_L10', 'A_PCT_3PT_L10', 'H_PCT_LANCER_FRANC_L10', 'A_PCT_LANCER_FRANC_L10', 'H_PCT_TIR_REUSSI_L10', 'A_PCT_TIR_REUSSI_L10', 'H_PIE_L10', 'A_PIE_L10', 'H_WL', 'A_WL', 'H_assistPercentage_L10', 'A_assistPercentage_L10', 'H_assistRatio_L10', 'A_assistRatio_L10', 'H_assistToTurnover_L10', 'A_assistToTurnover_L10', 'H_defensiveRating_L10', 'A_defensiveRating_L10', 'H_effectiveFieldGoalPercentage_L10', 'A_effectiveFieldGoalPercentage_L10', 'H_estimatedDefensiveRating_L10', 'A_estimatedDefensiveRating_L10', 'H_estimatedNetRating_L10', 'A_estimatedNetRating_L10', 'H_estimatedOffensiveRating_L10', 'A_estimatedOffensiveRating_L10', 'H_estimatedPace_L10', 'A_estimatedPace_L10', 'H_estimatedTeamTurnoverPercentage_L10', 'A_estimatedTeamTurnoverPercentage_L10', 'H_netRating_L10', 'A_netRating_L10', 'H_offensiveRating_L10', 'A_offensiveRating_L10', 'H_pacePer40_L10', 'A_pacePer40_L10', 'H_pace_L10', 'A_pace_L10', 'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L10', 'A_trueShootingPercentage_L10', 'H_turnoverRatio_L10', 'A_turnoverRatio_L10']
df_stat_flatten

,gameId,H_DUEL,A_DUEL,H_GAME_DATE,A_GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,3,4,0.3744,0.3463,0.7976,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,7,7,0.3545,0.3853,0.7753,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,7,6,0.3954,0.3759,0.8557,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,8,5,0.3984,0.3864,0.7737,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,7,6,0.3244,0.3545,0.7606,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [97]:
df_stat_flatten = df_stat_flatten.drop('A_DUEL', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_GAME_DATE', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_WL', axis=1)
df_stat_flatten = df_stat_flatten.rename(columns={'H_DUEL': 'DUEL', 'H_GAME_DATE': 'GAME_DATE', 'H_WL': 'HOME_WON'})
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('W', 1)
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('L', 0)
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,A_PCT_LANCER_FRANC_L10,H_PCT_TIR_REUSSI_L10,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.7590,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,3,4,0.3744,0.3463,0.7976,0.7192,0.4321,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,2023-12-08,7,7,0.3545,0.3853,0.7753,0.7832,0.4698,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,2023-12-08,7,6,0.3954,0.3759,0.8557,0.7684,0.4796,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,2023-12-07,8,5,0.3984,0.3864,0.7737,0.7809,0.5201,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,2023-12-07,7,6,0.3244,0.3545,0.7606,0.7908,0.4767,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [98]:
df_stat_flatten.to_csv('../dataset/df_stat_flatten.csv', index=False)