In [2]:
import pandas as pd

In [209]:
data_type = {"gameId": str, "teamId": str}
df_stat_last_10 = pd.read_csv('../dataset/team_stat_last_10.csv', dtype=data_type )
df_stat_last_10

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,6,0.4738,0.3759,0.7684,114.96,...,2.129,19.61,12.9317,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [210]:
df_stat_last_10['col'] = df_stat_last_10.groupby('gameId').cumcount() + 1
df_stat_flatten = df_stat_last_10.pivot_table(index='gameId', columns=df_stat_last_10.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN',
       'PCT_TIR_REUSSI_L10', 'PCT_3PTS_L10', 'PCT_LANCER_FRANC_L10',
       'estimatedOffensiveRating_L10', 'offensiveRating_L10',
       'estimatedDefensiveRating_L10', 'defensiveRating_L10',
       'estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10',
       'assistToTurnover_L10', 'assistRatio_L10',
       'estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10',
       'effectiveFieldGoalPercentage_L10', 'trueShootingPercentage_L10',
       'estimatedPace_L10', 'pace_L10', 'pacePer40_L10', 'PIE_L10'], aggfunc='first')

df_stat_flatten.columns = [f'col{col[1]}' for col in df_stat_flatten.columns]


df_stat_flatten = df_stat_flatten.reset_index()
#df_stat_flatten

In [211]:
df_stat_flatten

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,3,4,0.3744,0.3463,0.7976,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,7,7,0.3545,0.3853,0.7753,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,7,6,0.3954,0.3759,0.8557,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,8,5,0.3984,0.3864,0.7737,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,7,6,0.3244,0.3545,0.7606,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [212]:
print(len(['DUEL', 'GAME_DATE', 'NB_WIN', 'PCT_3PT_L10', 'PCT_LANCER_FRANC_L10', 'PCT_TIR_REUSSI_L10', 'PIE_L10', 'WL', 'assistPercentage_L10', 'assistRatio_L10', 'assistToTurnover_L10', 'defensiveRating_L10', 'effectiveFieldGoalPercentage_L10', 'estimatedDefensiveRating_L10', 'estimatedNetRating_L10', 'estimatedOffensiveRating_L10', 'estimatedPace_L10', 'estimatedTeamTurnoverPercentage_L10', 'netRating_L10', 'offensiveRating_L10','pacePer40_L10', 'pace_L10','teamId', 'trueShootingPercentage_L10', 'turnoverRatio_L10']))

25

In [213]:
df_stat_flatten.columns = ['gameId', 'H_DUEL', 'A_DUEL', 'H_GAME_DATE', 'A_GAME_DATE', 'H_NB_WIN', 'A_NB_WIN', 'H_PCT_3PT_L10', 'A_PCT_3PT_L10', 'H_PCT_LANCER_FRANC_L10', 'A_PCT_LANCER_FRANC_L10', 'H_PCT_TIR_REUSSI_L10', 'A_PCT_TIR_REUSSI_L10', 'H_PIE_L10', 'A_PIE_L10', 'H_WL', 'A_WL', 'H_assistPercentage_L10', 'A_assistPercentage_L10', 'H_assistRatio_L10', 'A_assistRatio_L10', 'H_assistToTurnover_L10', 'A_assistToTurnover_L10', 'H_defensiveRating_L10', 'A_defensiveRating_L10', 'H_effectiveFieldGoalPercentage_L10', 'A_effectiveFieldGoalPercentage_L10', 'H_estimatedDefensiveRating_L10', 'A_estimatedDefensiveRating_L10', 'H_estimatedNetRating_L10', 'A_estimatedNetRating_L10', 'H_estimatedOffensiveRating_L10', 'A_estimatedOffensiveRating_L10', 'H_estimatedPace_L10', 'A_estimatedPace_L10', 'H_estimatedTeamTurnoverPercentage_L10', 'A_estimatedTeamTurnoverPercentage_L10', 'H_netRating_L10', 'A_netRating_L10', 'H_offensiveRating_L10', 'A_offensiveRating_L10', 'H_pacePer40_L10', 'A_pacePer40_L10', 'H_pace_L10', 'A_pace_L10', 'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L10', 'A_trueShootingPercentage_L10', 'H_turnoverRatio_L10', 'A_turnoverRatio_L10']
df_stat_flatten

,gameId,H_DUEL,A_DUEL,H_GAME_DATE,A_GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,3,4,0.3744,0.3463,0.7976,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,7,7,0.3545,0.3853,0.7753,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,7,6,0.3954,0.3759,0.8557,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,8,5,0.3984,0.3864,0.7737,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,7,6,0.3244,0.3545,0.7606,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [214]:
df_stat_flatten = df_stat_flatten.drop('A_DUEL', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_GAME_DATE', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_WL', axis=1)
df_stat_flatten = df_stat_flatten.rename(columns={'H_DUEL': 'DUEL', 'H_GAME_DATE': 'GAME_DATE', 'H_WL': 'HOME_WON'})
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('W', 1)
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('L', 0)
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,A_PCT_LANCER_FRANC_L10,H_PCT_TIR_REUSSI_L10,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.7590,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,3,4,0.3744,0.3463,0.7976,0.7192,0.4321,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,2023-12-08,7,7,0.3545,0.3853,0.7753,0.7832,0.4698,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,2023-12-08,7,6,0.3954,0.3759,0.8557,0.7684,0.4796,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,2023-12-07,8,5,0.3984,0.3864,0.7737,0.7809,0.5201,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,2023-12-07,7,6,0.3244,0.3545,0.7606,0.7908,0.4767,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [215]:
df_stat_flatten.to_csv('../dataset/team_stat_flatten.csv', index=False)

In [216]:
nba_elo = pd.read_csv('../dataset/nba_elo.csv', dtype=data_type )

In [217]:
nba_elo_copy= nba_elo.copy()
nba_elo_copy

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,elo1_post,elo2_post,score1,score2,is_home
0,1946-11-01,1947,0,NaN,TRH,NYK,1300.000000,1300.000000,0.640065,0.359935,1293.276700,1306.723300,66,68,1
1,1946-11-01,1947,0,NaN,NYK,TRH,1300.000000,1300.000000,0.359935,0.640065,1306.723300,1293.276700,68,66,0
2,1946-11-02,1947,0,NaN,PRO,BOS,1300.000000,1300.000000,0.640065,0.359935,1305.154200,1294.845800,59,53,1
3,1946-11-02,1947,0,NaN,STB,PIT,1300.000000,1300.000000,0.640065,0.359935,1304.690800,1295.309200,56,51,1
4,1946-11-02,1947,0,NaN,CHS,NYK,1300.000000,1306.723300,0.631101,0.368899,1309.652100,1297.071200,63,47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148933,2024-03-30,2024,0,NaN,MEM,ORL,1325.023208,1523.156879,0.152362,0.847638,1319.643511,1528.536576,88,118,0
148934,2024-03-30,2024,0,NaN,MIL,ATL,1586.179279,1493.120229,0.490012,0.509988,1596.162979,1483.136529,122,113,0
148935,2024-03-30,2024,0,NaN,NOP,BOS,1635.324867,1758.207851,0.467116,0.532884,1624.649366,1768.883352,92,104,1
148936,2024-03-30,2024,0,NaN,ORL,MEM,1523.156879,1325.023208,0.847638,0.152362,1528.536576,1319.643511,118,88,1
148937,2024-03-30,2024,0,NaN,ATL,MIL,1493.120229,1586.179279,0.509988,0.490012,1483.136529,1596.162979,113,122,1

In [218]:
columns_list = nba_elo_copy.columns.tolist()

print(columns_list)

['date', 'season', 'neutral', 'playoff', 'team1', 'team2', 'elo1_pre', 'elo2_pre', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']

In [219]:
columns_to_drop = ['season',  'neutral', 'playoff', 'team2', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']  # Liste des noms des colonnes à supprimer
nba_elo_copy_drop= nba_elo_copy.drop(columns=columns_to_drop)

In [220]:
nba_elo_copy_drop

              date team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [221]:
nba_elo_copy_drop['team1'] = nba_elo_copy_drop['team1'].replace({'PHO': 'PHX', 'BRK': 'BKN', 'CHO': 'CHA'})

In [222]:
df_stat_flatten['team1'] = df_stat_flatten['DUEL'].str.split(' vs. ').str[0]

In [223]:
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,A_PCT_LANCER_FRANC_L10,H_PCT_TIR_REUSSI_L10,...,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.7590,NaN,...,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,3,4,0.3744,0.3463,0.7976,0.7192,0.4321,...,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72,POR
12970,22301227,BOS vs. NYK,2023-12-08,7,7,0.3545,0.3853,0.7753,0.7832,0.4698,...,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69,BOS
12971,22301228,PHX vs. SAC,2023-12-08,7,6,0.3954,0.3759,0.8557,0.7684,0.4796,...,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14,PHX
12972,22301229,MIL vs. IND,2023-12-07,8,5,0.3984,0.3864,0.7737,0.7809,0.5201,...,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57,MIL
12973,22301230,LAL vs. NOP,2023-12-07,7,6,0.3244,0.3545,0.7606,0.7908,0.4767,...,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51,LAL

In [224]:
new_column_names = {'date':'GAME_DATE' }
nba_elo_copy_drop_rename= nba_elo_copy_drop.rename(columns=new_column_names)
nba_elo_copy_drop_rename

         GAME_DATE team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [225]:
result = pd.merge(df_stat_flatten, nba_elo_copy_drop_rename, on=['GAME_DATE', 'team1'])

In [226]:
result

,gameId,DUEL,GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,A_PCT_LANCER_FRANC_L10,H_PCT_TIR_REUSSI_L10,...,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1,elo1_pre,elo2_pre
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.7590,NaN,...,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,3,4,0.3744,0.3463,0.7976,0.7192,0.4321,...,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,7,7,0.3545,0.3853,0.7753,0.7832,0.4698,...,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,7,6,0.3954,0.3759,0.8557,0.7684,0.4796,...,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,8,5,0.3984,0.3864,0.7737,0.7809,0.5201,...,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,7,6,0.3244,0.3545,0.7606,0.7908,0.4767,...,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51,LAL,1541.467385,1543.760516

In [227]:
new_column_names = {'elo1_pre':'A_ELO' , 'elo2_pre': 'H_ELO'}
result= result.rename(columns=new_column_names)
result

,gameId,DUEL,GAME_DATE,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,A_PCT_LANCER_FRANC_L10,H_PCT_TIR_REUSSI_L10,...,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1,A_ELO,H_ELO
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.7590,NaN,...,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,3,4,0.3744,0.3463,0.7976,0.7192,0.4321,...,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,7,7,0.3545,0.3853,0.7753,0.7832,0.4698,...,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,7,6,0.3954,0.3759,0.8557,0.7684,0.4796,...,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,8,5,0.3984,0.3864,0.7737,0.7809,0.5201,...,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,7,6,0.3244,0.3545,0.7606,0.7908,0.4767,...,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51,LAL,1541.467385,1543.760516

In [228]:
new_order = ['gameId', 'DUEL','GAME_DATE','HOME_WON','H_ELO','A_ELO','H_NB_WIN','A_NB_WIN', 'H_PCT_3PT_L10',
       'A_PCT_3PT_L10', 'H_PCT_LANCER_FRANC_L10', 'A_PCT_LANCER_FRANC_L10',
       'H_PCT_TIR_REUSSI_L10', 'A_PCT_TIR_REUSSI_L10', 'H_PIE_L10',
       'A_PIE_L10',  'H_assistPercentage_L10',
       'A_assistPercentage_L10', 'H_assistRatio_L10', 'A_assistRatio_L10',
       'H_assistToTurnover_L10', 'A_assistToTurnover_L10',
       'H_defensiveRating_L10', 'A_defensiveRating_L10',
       'H_effectiveFieldGoalPercentage_L10',
       'A_effectiveFieldGoalPercentage_L10', 'H_estimatedDefensiveRating_L10',
       'A_estimatedDefensiveRating_L10', 'H_estimatedNetRating_L10',
       'A_estimatedNetRating_L10', 'H_estimatedOffensiveRating_L10',
       'A_estimatedOffensiveRating_L10', 'H_estimatedPace_L10',
       'A_estimatedPace_L10', 'H_estimatedTeamTurnoverPercentage_L10',
       'A_estimatedTeamTurnoverPercentage_L10', 'H_netRating_L10',
       'A_netRating_L10', 'H_offensiveRating_L10', 'A_offensiveRating_L10',
       'H_pacePer40_L10', 'A_pacePer40_L10', 'H_pace_L10', 'A_pace_L10',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L10',
       'A_trueShootingPercentage_L10', 'H_turnoverRatio_L10',
       'A_turnoverRatio_L10', 'team1']

# Réorganiser les colonnes
result = result.reindex(columns=new_order)

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,...,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10,team1
0,21300001,IND vs. ORL,2013-10-29,1,1313.231700,1583.572100,0,0,NaN,NaN,...,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND
1,21300002,MIA vs. CHI,2013-10-29,1,1519.912400,1691.889600,0,0,NaN,NaN,...,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA
2,21300003,LAL vs. LAC,2013-10-29,1,1586.588400,1511.020000,0,0,NaN,NaN,...,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL
3,21300004,CLE vs. BKN,2013-10-30,1,1548.436500,1369.282300,0,0,NaN,NaN,...,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE
4,21300005,PHI vs. MIA,2013-10-30,1,1695.193200,1459.690400,0,1,NaN,0.5500,...,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,3,4,0.3744,0.3463,...,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72,POR
12970,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,7,7,0.3545,0.3853,...,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69,BOS
12971,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,7,6,0.3954,0.3759,...,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14,PHX
12972,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,8,5,0.3984,0.3864,...,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57,MIL
12973,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,7,6,0.3244,0.3545,...,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51,LAL

In [229]:
result = result.drop(columns=['team1'])

In [230]:
result = result.dropna()

In [1]:
result.to_csv('../dataset/team_stat_flatten.csv', index=False)
result

NameError: name 'result' is not defined

In [5]:
data_type = {"gameId": str, "teamId": str}
team_stat_flatten = pd.read_csv('../dataset/team_stat_flatten.csv', dtype=data_type )
team_stat_flatten

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,...,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_teamId,A_teamId,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.2690,0.2310,...,82.080,78.330,98.500,94.00,1610612741,1610612752,0.5100,0.5730,19.40,23.40
1,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.3810,0.5560,...,82.080,87.080,98.500,104.50,1610612746,1610612744,0.5530,0.6500,16.30,14.30
2,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.4000,0.3330,...,76.250,77.500,91.500,93.00,1610612766,1610612739,0.4200,0.4950,8.70,15.10
3,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.4220,0.4550,...,81.620,76.670,97.945,92.00,1610612753,1610612740,0.4900,0.4780,18.05,16.30
4,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.4000,0.3810,...,81.670,84.580,98.000,101.50,1610612764,1610612755,0.5540,0.6290,17.30,17.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,3,4,0.3744,0.3463,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12953,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,7,7,0.3545,0.3853,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12954,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,7,6,0.3954,0.3759,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12955,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,8,5,0.3984,0.3864,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12956,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,7,6,0.3244,0.3545,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [6]:
team_stat_flatten = team_stat_flatten.drop(columns=['gameId', 'DUEL', 'GAME_DATE','H_teamId', 'A_teamId'])
team_stat_flatten.to_csv('../dataset/final_dataset.csv', index=False)
team_stat_flatten

,HOME_WON,H_ELO,A_ELO,H_NB_WIN,A_NB_WIN,H_PCT_3PT_L10,A_PCT_3PT_L10,H_PCT_LANCER_FRANC_L10,A_PCT_LANCER_FRANC_L10,H_PCT_TIR_REUSSI_L10,...,H_offensiveRating_L10,A_offensiveRating_L10,H_pacePer40_L10,A_pacePer40_L10,H_pace_L10,A_pace_L10,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_turnoverRatio_L10,A_turnoverRatio_L10
0,1,1582.133300,1516.608800,0,1,0.2690,0.2310,0.7830,0.8820,0.4220,...,96.90,95.70,82.080,78.330,98.500,94.00,0.5100,0.5730,19.40,23.40
1,1,1574.897700,1575.414200,0,1,0.3810,0.5560,0.5650,0.7830,0.4940,...,105.10,119.00,82.080,87.080,98.500,104.50,0.5530,0.6500,16.30,14.30
2,1,1377.546500,1349.502100,0,1,0.4000,0.3330,0.6500,0.6760,0.3670,...,90.20,105.40,76.250,77.500,91.500,93.00,0.4200,0.4950,8.70,15.10
3,1,1422.004600,1309.402000,0,0,0.4220,0.4550,0.6055,0.8100,0.4285,...,97.20,97.80,81.620,76.670,97.945,92.00,0.4900,0.4780,18.05,16.30
4,0,1469.418000,1452.716800,0,1,0.4000,0.3810,0.7500,0.8330,0.4360,...,104.10,111.80,81.670,84.580,98.000,101.50,0.5540,0.6290,17.30,17.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,0,1492.541584,1361.139964,3,4,0.3744,0.3463,0.7976,0.7192,0.4321,...,106.40,115.12,81.051,83.168,97.259,99.80,0.5395,0.5587,16.22,10.72
12953,1,1591.374004,1662.122050,7,7,0.3545,0.3853,0.7753,0.7832,0.4698,...,114.00,118.31,82.192,80.624,98.631,96.75,0.5876,0.5792,15.05,13.69
12954,0,1526.069995,1551.810711,7,6,0.3954,0.3759,0.8557,0.7684,0.4796,...,119.77,116.81,80.209,85.334,96.250,102.40,0.6058,0.5941,14.64,13.14
12955,0,1502.061541,1601.142185,8,5,0.3984,0.3864,0.7737,0.7809,0.5201,...,123.69,125.63,85.498,86.917,102.598,104.30,0.6296,0.6305,12.30,11.57
12956,1,1543.760516,1541.467385,7,6,0.3244,0.3545,0.7606,0.7908,0.4767,...,110.41,119.72,83.959,82.459,100.750,98.95,0.5706,0.6015,14.62,13.51