In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat_last_20 = pd.read_csv('../dataset/team_stat_last_20.csv', dtype=data_type )
df_stat_last_20

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L20,PCT_TIR_REUSSI_L20,PCT_3PTS_L20,PCT_LANCER_FRANC_L20,estimatedOffensiveRating_L20,...,assistToTurnover_L20,assistRatio_L20,estimatedTeamTurnoverPercentage_L20,turnoverRatio_L20,effectiveFieldGoalPercentage_L20,trueShootingPercentage_L20,estimatedPace_L20,pace_L20,pacePer40_L20,PIE_L20
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,11,0.46220,0.35120,0.74020,111.640,...,2.0595,19.190,13.34245,13.565,0.54345,0.57510,102.2440,100.555,83.7965,0.47590
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,14,0.49980,0.38360,0.77305,117.830,...,2.0560,18.375,13.18170,13.410,0.58235,0.61465,103.8145,101.974,84.9780,0.51615
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,12,0.50955,0.39560,0.79430,119.950,...,2.5980,20.585,11.85740,12.265,0.59190,0.62130,107.2720,104.400,86.9995,0.50915
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,12,0.48650,0.33675,0.76650,109.490,...,1.8970,19.050,14.27760,14.500,0.54555,0.58340,102.5400,100.523,83.7695,0.51855
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,10,0.48330,0.36040,0.76325,114.255,...,2.0885,19.000,13.24720,13.420,0.54530,0.58375,101.9380,100.250,83.5420,0.50685

In [3]:
df_stat_last_20['col'] = df_stat_last_20.groupby('gameId').cumcount() + 1
df_stat_flatten = df_stat_last_20.pivot_table(index='gameId', columns=df_stat_last_20.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L20',
       'PCT_TIR_REUSSI_L20', 'PCT_3PTS_L20', 'PCT_LANCER_FRANC_L20',
       'estimatedOffensiveRating_L20', 'offensiveRating_L20',
       'estimatedDefensiveRating_L20', 'defensiveRating_L20',
       'estimatedNetRating_L20', 'netRating_L20', 'assistPercentage_L20',
       'assistToTurnover_L20', 'assistRatio_L20',
       'estimatedTeamTurnoverPercentage_L20', 'turnoverRatio_L20',
       'effectiveFieldGoalPercentage_L20', 'trueShootingPercentage_L20',
       'estimatedPace_L20', 'pace_L20', 'pacePer40_L20', 'PIE_L20'], aggfunc='first')

df_stat_flatten.columns = [f'col{col[1]}' for col in df_stat_flatten.columns]


df_stat_flatten = df_stat_flatten.reset_index()
#df_stat_flatten

In [4]:
df_stat_flatten

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.0800,NaN,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,6,12,0.34245,0.3731,0.79475,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,15,12,0.36370,0.3713,0.78435,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,11,11,0.38865,0.3512,0.84340,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,14,12,0.38360,0.3956,0.77305,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,12,10,0.33675,0.3604,0.76650,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420

In [5]:
print(len(['DUEL', 'GAME_DATE', 'NB_WIN_L20', 'PCT_3PT_L20', 'PCT_LANCER_FRANC_L20', 'PCT_TIR_REUSSI_L20', 'PIE_L20', 'WL', 'assistPercentage_L20', 'assistRatio_L20', 'assistToTurnover_L20', 'defensiveRating_L20', 'effectiveFieldGoalPercentage_L20', 'estimatedDefensiveRating_L20', 'estimatedNetRating_L20', 'estimatedOffensiveRating_L20', 'estimatedPace_L20', 'estimatedTeamTurnoverPercentage_L20', 'netRating_L20', 'offensiveRating_L20','pacePer40_L20', 'pace_L20','teamId', 'trueShootingPercentage_L20', 'turnoverRatio_L20']))

25

In [6]:
df_stat_flatten.columns = ['gameId', 'H_DUEL', 'A_DUEL', 'H_GAME_DATE', 'A_GAME_DATE', 'H_NB_WIN_L20', 'A_NB_WIN_L20', 'H_PCT_3PT_L20', 'A_PCT_3PT_L20', 'H_PCT_LANCER_FRANC_L20', 'A_PCT_LANCER_FRANC_L20', 'H_PCT_TIR_REUSSI_L20', 'A_PCT_TIR_REUSSI_L20', 'H_PIE_L20', 'A_PIE_L20', 'H_WL', 'A_WL', 'H_assistPercentage_L20', 'A_assistPercentage_L20', 'H_assistRatio_L20', 'A_assistRatio_L20', 'H_assistToTurnover_L20', 'A_assistToTurnover_L20', 'H_defensiveRating_L20', 'A_defensiveRating_L20', 'H_effectiveFieldGoalPercentage_L20', 'A_effectiveFieldGoalPercentage_L20', 'H_estimatedDefensiveRating_L20', 'A_estimatedDefensiveRating_L20', 'H_estimatedNetRating_L20', 'A_estimatedNetRating_L20', 'H_estimatedOffensiveRating_L20', 'A_estimatedOffensiveRating_L20', 'H_estimatedPace_L20', 'A_estimatedPace_L20', 'H_estimatedTeamTurnoverPercentage_L20', 'A_estimatedTeamTurnoverPercentage_L20', 'H_netRating_L20', 'A_netRating_L20', 'H_offensiveRating_L20', 'A_offensiveRating_L20', 'H_pacePer40_L20', 'A_pacePer40_L20', 'H_pace_L20', 'A_pace_L20', 'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L20', 'A_trueShootingPercentage_L20', 'H_turnoverRatio_L20', 'A_turnoverRatio_L20']
df_stat_flatten

,gameId,H_DUEL,A_DUEL,H_GAME_DATE,A_GAME_DATE,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,H_PCT_LANCER_FRANC_L20,...,H_pacePer40_L20,A_pacePer40_L20,H_pace_L20,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.0800,NaN,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,6,12,0.34245,0.3731,0.79475,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,15,12,0.36370,0.3713,0.78435,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,11,11,0.38865,0.3512,0.84340,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,14,12,0.38360,0.3956,0.77305,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,12,10,0.33675,0.3604,0.76650,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420

In [7]:
df_stat_flatten = df_stat_flatten.drop('A_DUEL', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_GAME_DATE', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_WL', axis=1)
df_stat_flatten = df_stat_flatten.rename(columns={'H_DUEL': 'DUEL', 'H_GAME_DATE': 'GAME_DATE', 'H_WL': 'HOME_WON'})
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('W', 1)
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('L', 0)
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,H_PCT_LANCER_FRANC_L20,A_PCT_LANCER_FRANC_L20,H_PCT_TIR_REUSSI_L20,...,H_pacePer40_L20,A_pacePer40_L20,H_pace_L20,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.75900,NaN,...,NaN,82.0800,NaN,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,6,12,0.34245,0.3731,0.79475,0.73935,0.43560,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12970,22301227,BOS vs. NYK,2023-12-08,15,12,0.36370,0.3713,0.78435,0.75450,0.47375,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12971,22301228,PHX vs. SAC,2023-12-08,11,11,0.38865,0.3512,0.84340,0.74020,0.47520,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12972,22301229,MIL vs. IND,2023-12-07,14,12,0.38360,0.3956,0.77305,0.79430,0.49980,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12973,22301230,LAL vs. NOP,2023-12-07,12,10,0.33675,0.3604,0.76650,0.76325,0.48650,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420

In [8]:
df_stat_flatten.to_csv('../dataset/team_stat_flatten_L20.csv', index=False)

In [9]:
nba_elo = pd.read_csv('../dataset/nba_elo.csv', dtype=data_type )

In [10]:
nba_elo_copy= nba_elo.copy()
nba_elo_copy

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,elo1_post,elo2_post,score1,score2,is_home
0,1946-11-01,1947,0,NaN,TRH,NYK,1300.000000,1300.000000,0.640065,0.359935,1293.276700,1306.723300,66,68,1
1,1946-11-01,1947,0,NaN,NYK,TRH,1300.000000,1300.000000,0.359935,0.640065,1306.723300,1293.276700,68,66,0
2,1946-11-02,1947,0,NaN,PRO,BOS,1300.000000,1300.000000,0.640065,0.359935,1305.154200,1294.845800,59,53,1
3,1946-11-02,1947,0,NaN,STB,PIT,1300.000000,1300.000000,0.640065,0.359935,1304.690800,1295.309200,56,51,1
4,1946-11-02,1947,0,NaN,CHS,NYK,1300.000000,1306.723300,0.631101,0.368899,1309.652100,1297.071200,63,47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148933,2024-03-30,2024,0,NaN,MEM,ORL,1325.023208,1523.156879,0.152362,0.847638,1319.643511,1528.536576,88,118,0
148934,2024-03-30,2024,0,NaN,MIL,ATL,1586.179279,1493.120229,0.490012,0.509988,1596.162979,1483.136529,122,113,0
148935,2024-03-30,2024,0,NaN,NOP,BOS,1635.324867,1758.207851,0.467116,0.532884,1624.649366,1768.883352,92,104,1
148936,2024-03-30,2024,0,NaN,ORL,MEM,1523.156879,1325.023208,0.847638,0.152362,1528.536576,1319.643511,118,88,1
148937,2024-03-30,2024,0,NaN,ATL,MIL,1493.120229,1586.179279,0.509988,0.490012,1483.136529,1596.162979,113,122,1

In [11]:
columns_list = nba_elo_copy.columns.tolist()

print(columns_list)

['date', 'season', 'neutral', 'playoff', 'team1', 'team2', 'elo1_pre', 'elo2_pre', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']

In [12]:
columns_to_drop = ['season',  'neutral', 'playoff', 'team2', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']  # Liste des noms des colonnes à supprimer
nba_elo_copy_drop= nba_elo_copy.drop(columns=columns_to_drop)

In [13]:
nba_elo_copy_drop

              date team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [14]:
nba_elo_copy_drop['team1'] = nba_elo_copy_drop['team1'].replace({'PHO': 'PHX', 'BRK': 'BKN', 'CHO': 'CHA'})

In [15]:
df_stat_flatten['team1'] = df_stat_flatten['DUEL'].str.split(' vs. ').str[0]

In [16]:
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,H_PCT_LANCER_FRANC_L20,A_PCT_LANCER_FRANC_L20,H_PCT_TIR_REUSSI_L20,...,A_pacePer40_L20,H_pace_L20,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20,team1
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.75900,NaN,...,82.0800,NaN,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,6,12,0.34245,0.3731,0.79475,0.73935,0.43560,...,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435,POR
12970,22301227,BOS vs. NYK,2023-12-08,15,12,0.36370,0.3713,0.78435,0.75450,0.47375,...,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545,BOS
12971,22301228,PHX vs. SAC,2023-12-08,11,11,0.38865,0.3512,0.84340,0.74020,0.47520,...,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565,PHX
12972,22301229,MIL vs. IND,2023-12-07,14,12,0.38360,0.3956,0.77305,0.79430,0.49980,...,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265,MIL
12973,22301230,LAL vs. NOP,2023-12-07,12,10,0.33675,0.3604,0.76650,0.76325,0.48650,...,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420,LAL

In [17]:
new_column_names = {'date':'GAME_DATE' }
nba_elo_copy_drop_rename= nba_elo_copy_drop.rename(columns=new_column_names)
nba_elo_copy_drop_rename

         GAME_DATE team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [18]:
result = pd.merge(df_stat_flatten, nba_elo_copy_drop_rename, on=['GAME_DATE', 'team1'])

In [19]:
result

,gameId,DUEL,GAME_DATE,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,H_PCT_LANCER_FRANC_L20,A_PCT_LANCER_FRANC_L20,H_PCT_TIR_REUSSI_L20,...,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20,team1,elo1_pre,elo2_pre
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.75900,NaN,...,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,6,12,0.34245,0.3731,0.79475,0.73935,0.43560,...,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,15,12,0.36370,0.3713,0.78435,0.75450,0.47375,...,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,11,11,0.38865,0.3512,0.84340,0.74020,0.47520,...,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,14,12,0.38360,0.3956,0.77305,0.79430,0.49980,...,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,12,10,0.33675,0.3604,0.76650,0.76325,0.48650,...,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420,LAL,1541.467385,1543.760516

In [20]:
new_column_names = {'elo1_pre':'A_ELO' , 'elo2_pre': 'H_ELO'}
result= result.rename(columns=new_column_names)
result

,gameId,DUEL,GAME_DATE,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,H_PCT_LANCER_FRANC_L20,A_PCT_LANCER_FRANC_L20,H_PCT_TIR_REUSSI_L20,...,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20,team1,A_ELO,H_ELO
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.5500,NaN,0.75900,NaN,...,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,6,12,0.34245,0.3731,0.79475,0.73935,0.43560,...,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,15,12,0.36370,0.3713,0.78435,0.75450,0.47375,...,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,11,11,0.38865,0.3512,0.84340,0.74020,0.47520,...,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,14,12,0.38360,0.3956,0.77305,0.79430,0.49980,...,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,12,10,0.33675,0.3604,0.76650,0.76325,0.48650,...,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420,LAL,1541.467385,1543.760516

In [21]:
new_order = ['gameId', 'DUEL','GAME_DATE','HOME_WON','H_ELO','A_ELO','H_NB_WIN_L20','A_NB_WIN_L20', 'H_PCT_3PT_L20',
       'A_PCT_3PT_L20', 'H_PCT_LANCER_FRANC_L20', 'A_PCT_LANCER_FRANC_L20',
       'H_PCT_TIR_REUSSI_L20', 'A_PCT_TIR_REUSSI_L20', 'H_PIE_L20',
       'A_PIE_L20',  'H_assistPercentage_L20',
       'A_assistPercentage_L20', 'H_assistRatio_L20', 'A_assistRatio_L20',
       'H_assistToTurnover_L20', 'A_assistToTurnover_L20',
       'H_defensiveRating_L20', 'A_defensiveRating_L20',
       'H_effectiveFieldGoalPercentage_L20',
       'A_effectiveFieldGoalPercentage_L20', 'H_estimatedDefensiveRating_L20',
       'A_estimatedDefensiveRating_L20', 'H_estimatedNetRating_L20',
       'A_estimatedNetRating_L20', 'H_estimatedOffensiveRating_L20',
       'A_estimatedOffensiveRating_L20', 'H_estimatedPace_L20',
       'A_estimatedPace_L20', 'H_estimatedTeamTurnoverPercentage_L20',
       'A_estimatedTeamTurnoverPercentage_L20', 'H_netRating_L20',
       'A_netRating_L20', 'H_offensiveRating_L20', 'A_offensiveRating_L20',
       'H_pacePer40_L20', 'A_pacePer40_L20', 'H_pace_L20', 'A_pace_L20',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L20',
       'A_trueShootingPercentage_L20', 'H_turnoverRatio_L20',
       'A_turnoverRatio_L20', 'team1']

# Réorganiser les colonnes
result = result.reindex(columns=new_order)

In [22]:
result = result.drop(columns=['team1'])

In [23]:
result = result.dropna()

In [24]:
result.to_csv('../dataset/team_stat_flatten_L20.csv', index=False)
result

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,...,H_pacePer40_L20,A_pacePer40_L20,H_pace_L20,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20
17,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.26900,0.2310,...,82.0800,78.3300,98.500,94.000,1610612741,1610612752,0.51000,0.57300,19.400,23.400
18,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.38100,0.5560,...,82.0800,87.0800,98.500,104.500,1610612746,1610612744,0.55300,0.65000,16.300,14.300
19,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.40000,0.3330,...,76.2500,77.5000,91.500,93.000,1610612766,1610612739,0.42000,0.49500,8.700,15.100
20,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.42200,0.4550,...,81.6200,76.6700,97.945,92.000,1610612753,1610612740,0.49000,0.47800,18.050,16.300
21,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.40000,0.3810,...,81.6700,84.5800,98.000,101.500,1610612764,1610612755,0.55400,0.62900,17.300,17.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,6,12,0.34245,0.3731,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12970,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,15,12,0.36370,0.3713,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12971,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,11,11,0.38865,0.3512,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12972,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,14,12,0.38360,0.3956,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12973,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,12,10,0.33675,0.3604,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420

In [25]:
data_type = {"gameId": str, "teamId": str}
team_stat_flatten = pd.read_csv('../dataset/team_stat_flatten_L20.csv', dtype=data_type )
team_stat_flatten

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN_L20,A_NB_WIN_L20,H_PCT_3PT_L20,A_PCT_3PT_L20,...,H_pacePer40_L20,A_pacePer40_L20,H_pace_L20,A_pace_L20,H_teamId,A_teamId,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_turnoverRatio_L20,A_turnoverRatio_L20
0,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.26900,0.2310,...,82.0800,78.3300,98.500,94.000,1610612741,1610612752,0.51000,0.57300,19.400,23.400
1,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.38100,0.5560,...,82.0800,87.0800,98.500,104.500,1610612746,1610612744,0.55300,0.65000,16.300,14.300
2,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.40000,0.3330,...,76.2500,77.5000,91.500,93.000,1610612766,1610612739,0.42000,0.49500,8.700,15.100
3,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.42200,0.4550,...,81.6200,76.6700,97.945,92.000,1610612753,1610612740,0.49000,0.47800,18.050,16.300
4,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.40000,0.3810,...,81.6700,84.5800,98.000,101.500,1610612764,1610612755,0.55400,0.62900,17.300,17.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,6,12,0.34245,0.3731,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12953,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,15,12,0.36370,0.3713,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12954,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,11,11,0.38865,0.3512,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12955,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,14,12,0.38360,0.3956,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12956,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,12,10,0.33675,0.3604,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420

In [26]:
team_stat_flatten.columns

Index(['gameId', 'DUEL', 'GAME_DATE', 'HOME_WON', 'H_ELO', 'A_ELO',
       'H_NB_WIN_L20', 'A_NB_WIN_L20', 'H_PCT_3PT_L20', 'A_PCT_3PT_L20',
       'H_PCT_LANCER_FRANC_L20', 'A_PCT_LANCER_FRANC_L20',
       'H_PCT_TIR_REUSSI_L20', 'A_PCT_TIR_REUSSI_L20', 'H_PIE_L20',
       'A_PIE_L20', 'H_assistPercentage_L20', 'A_assistPercentage_L20',
       'H_assistRatio_L20', 'A_assistRatio_L20', 'H_assistToTurnover_L20',
       'A_assistToTurnover_L20', 'H_defensiveRating_L20',
       'A_defensiveRating_L20', 'H_effectiveFieldGoalPercentage_L20',
       'A_effectiveFieldGoalPercentage_L20', 'H_estimatedDefensiveRating_L20',
       'A_estimatedDefensiveRating_L20', 'H_estimatedNetRating_L20',
       'A_estimatedNetRating_L20', 'H_estimatedOffensiveRating_L20',
       'A_estimatedOffensiveRating_L20', 'H_estimatedPace_L20',
       'A_estimatedPace_L20', 'H_estimatedTeamTurnoverPercentage_L20',
       'A_estimatedTeamTurnoverPercentage_L20', 'H_netRating_L20',
       'A_netRating_L20', 'H_offensiveRating_L20', 'A_offensiveRating_L20',
       'H_pacePer40_L20', 'A_pacePer40_L20', 'H_pace_L20', 'A_pace_L20',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L20',
       'A_trueShootingPercentage_L20', 'H_turnoverRatio_L20',
       'A_turnoverRatio_L20'],
      dtype='object')

In [27]:
team_stat_flatten = team_stat_flatten.drop(columns=['DUEL', 'GAME_DATE','H_teamId', 'A_teamId'])
colonne_a_supprimer = team_stat_flatten.columns[2:]
# Boucle sur chaque paire de colonnes pour calculer la différence
for colonne in colonne_a_supprimer:
    # Extraire le préfixe de la colonne ('H_' ou 'A_')
    prefixe = colonne[0:2]
    # Extraire le nom de la colonne sans le préfixe
    nom_colonne = colonne[2:]
    # Créer une nouvelle colonne pour stocker la différence
    team_stat_flatten[f'{nom_colonne}'] = team_stat_flatten.apply(lambda row: row[f'H_{nom_colonne}'] - row[f'A_{nom_colonne}'], axis=1)

team_stat_flatten = team_stat_flatten.drop(columns=colonne_a_supprimer)
       
team_stat_flatten

,gameId,HOME_WON,ELO,NB_WIN_L20,PCT_3PT_L20,PCT_LANCER_FRANC_L20,PCT_TIR_REUSSI_L20,PIE_L20,assistPercentage_L20,assistRatio_L20,...,estimatedNetRating_L20,estimatedOffensiveRating_L20,estimatedPace_L20,estimatedTeamTurnoverPercentage_L20,netRating_L20,offensiveRating_L20,pacePer40_L20,pace_L20,trueShootingPercentage_L20,turnoverRatio_L20
0,21300018,1,65.524500,-1,0.03800,-0.09900,-0.08500,-0.18800,0.18500,2.500,...,-24.100,-1.400,4.0600,-4.4950,-18.500,1.200,3.7500,4.500,-0.06300,-4.000
1,21300019,1,-0.516500,-1,-0.17500,-0.21800,-0.04100,-0.20600,-0.08000,-3.600,...,-36.800,-16.200,-2.4600,1.7360,-40.800,-13.900,-5.0000,-6.000,-0.09700,2.000
2,21300020,1,28.044400,-1,0.06700,-0.02600,-0.05000,-0.16800,-0.17600,-4.100,...,-23.000,-13.500,-4.5800,-6.0000,-19.600,-15.200,-1.2500,-1.500,-0.07500,-6.400
3,21300021,1,112.602600,0,-0.03300,-0.20450,0.02850,-0.00350,-0.04050,0.000,...,-4.450,-2.050,6.7450,1.3120,-2.600,-0.600,4.9500,5.945,0.01200,1.750
4,21300022,0,16.701200,-1,0.01900,-0.08300,-0.10200,-0.15400,0.11800,-0.700,...,-13.700,-7.200,-3.8400,-0.2060,-14.100,-7.700,-2.9100,-3.500,-0.07500,-0.300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,0,131.401620,-6,-0.03065,0.05540,-0.03295,-0.05840,-0.03575,-2.275,...,-9.380,-13.200,-2.3190,4.5103,-9.205,-13.085,-2.1140,-2.537,-0.04980,4.690
12953,22301227,1,-70.748046,3,-0.00760,0.02985,0.02510,0.03465,0.01875,1.190,...,6.270,2.830,1.8345,0.6981,4.245,1.685,1.5550,1.867,0.03695,0.580
12954,22301228,0,-25.740716,0,0.03745,0.10320,0.01300,0.05010,-0.01060,-0.360,...,4.280,2.735,-2.3315,1.4842,4.450,3.770,-2.5170,-3.019,0.02435,1.610
12955,22301229,0,-99.080644,2,-0.01200,-0.02125,-0.00975,0.00700,-0.05950,-2.210,...,2.145,-2.120,-3.4575,1.3243,0.450,-4.310,-2.0215,-2.426,-0.00665,1.145
12956,22301230,1,2.293131,2,-0.02365,0.00325,0.00320,0.01170,0.00705,0.050,...,-1.640,-4.765,0.6020,1.0304,-1.370,-4.290,0.2275,0.273,-0.00035,1.080

In [28]:
team_stat_flatten.to_csv('../dataset/final_dataset_diff_L20.csv', index=False)