In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat_last_40 = pd.read_csv('../dataset/team_stat_last_40.csv', dtype=data_type )
df_stat_last_40

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L40,PCT_TIR_REUSSI_L40,PCT_3PTS_L40,PCT_LANCER_FRANC_L40,estimatedOffensiveRating_L40,...,assistToTurnover_L40,assistRatio_L40,estimatedTeamTurnoverPercentage_L40,turnoverRatio_L40,effectiveFieldGoalPercentage_L40,trueShootingPercentage_L40,estimatedPace_L40,pace_L40,pacePer40_L40,PIE_L40
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,23,0.475150,0.363350,0.749525,115.8900,...,2.50525,19.5525,12.027375,12.1950,0.557275,0.589900,101.81925,100.24625,83.53875,0.493575
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,28,0.499350,0.381350,0.766050,117.2375,...,2.07550,19.1550,13.317450,13.4550,0.582800,0.612025,103.97350,102.47950,85.39950,0.519975
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,20,0.501400,0.382275,0.785175,117.1750,...,2.39550,20.1000,12.776800,13.0950,0.576075,0.607525,105.57125,103.16200,85.96850,0.496175
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,26,0.487175,0.347000,0.768000,111.9800,...,1.98200,18.7525,13.842300,14.0575,0.548725,0.587575,102.20775,100.34975,83.62525,0.527625
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,23,0.485550,0.380600,0.789775,113.4400,...,2.01725,19.1500,13.705075,13.9275,0.551425,0.589200,101.23600,99.53825,82.94875,0.523350

In [3]:
df_stat_last_40['col'] = df_stat_last_40.groupby('gameId').cumcount() + 1
df_stat_flatten = df_stat_last_40.pivot_table(index='gameId', columns=df_stat_last_40.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L40',
       'PCT_TIR_REUSSI_L40', 'PCT_3PTS_L40', 'PCT_LANCER_FRANC_L40',
       'estimatedOffensiveRating_L40', 'offensiveRating_L40',
       'estimatedDefensiveRating_L40', 'defensiveRating_L40',
       'estimatedNetRating_L40', 'netRating_L40', 'assistPercentage_L40',
       'assistToTurnover_L40', 'assistRatio_L40',
       'estimatedTeamTurnoverPercentage_L40', 'turnoverRatio_L40',
       'effectiveFieldGoalPercentage_L40', 'trueShootingPercentage_L40',
       'estimatedPace_L40', 'pace_L40', 'pacePer40_L40', 'PIE_L40'], aggfunc='first')

df_stat_flatten.columns = [f'col{col[1]}' for col in df_stat_flatten.columns]


df_stat_flatten = df_stat_flatten.reset_index()
#df_stat_flatten

In [4]:
df_stat_flatten

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.08000,NaN,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,10,18,0.337725,0.377300,0.781725,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,28,24,0.368950,0.373950,0.775000,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,23,23,0.372450,0.363350,0.825300,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,28,20,0.381350,0.382275,0.766050,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,26,23,0.347000,0.380600,0.768000,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275

In [5]:
print(len(['DUEL', 'GAME_DATE', 'NB_WIN_L40', 'PCT_3PT_L40', 'PCT_LANCER_FRANC_L40', 'PCT_TIR_REUSSI_L40', 'PIE_L40', 'WL', 'assistPercentage_L40', 'assistRatio_L40', 'assistToTurnover_L40', 'defensiveRating_L40', 'effectiveFieldGoalPercentage_L40', 'estimatedDefensiveRating_L40', 'estimatedNetRating_L40', 'estimatedOffensiveRating_L40', 'estimatedPace_L40', 'estimatedTeamTurnoverPercentage_L40', 'netRating_L40', 'offensiveRating_L40','pacePer40_L40', 'pace_L40','teamId', 'trueShootingPercentage_L40', 'turnoverRatio_L40']))

25

In [6]:
df_stat_flatten.columns = ['gameId', 'H_DUEL', 'A_DUEL', 'H_GAME_DATE', 'A_GAME_DATE', 'H_NB_WIN_L40', 'A_NB_WIN_L40', 'H_PCT_3PT_L40', 'A_PCT_3PT_L40', 'H_PCT_LANCER_FRANC_L40', 'A_PCT_LANCER_FRANC_L40', 'H_PCT_TIR_REUSSI_L40', 'A_PCT_TIR_REUSSI_L40', 'H_PIE_L40', 'A_PIE_L40', 'H_WL', 'A_WL', 'H_assistPercentage_L40', 'A_assistPercentage_L40', 'H_assistRatio_L40', 'A_assistRatio_L40', 'H_assistToTurnover_L40', 'A_assistToTurnover_L40', 'H_defensiveRating_L40', 'A_defensiveRating_L40', 'H_effectiveFieldGoalPercentage_L40', 'A_effectiveFieldGoalPercentage_L40', 'H_estimatedDefensiveRating_L40', 'A_estimatedDefensiveRating_L40', 'H_estimatedNetRating_L40', 'A_estimatedNetRating_L40', 'H_estimatedOffensiveRating_L40', 'A_estimatedOffensiveRating_L40', 'H_estimatedPace_L40', 'A_estimatedPace_L40', 'H_estimatedTeamTurnoverPercentage_L40', 'A_estimatedTeamTurnoverPercentage_L40', 'H_netRating_L40', 'A_netRating_L40', 'H_offensiveRating_L40', 'A_offensiveRating_L40', 'H_pacePer40_L40', 'A_pacePer40_L40', 'H_pace_L40', 'A_pace_L40', 'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L40', 'A_trueShootingPercentage_L40', 'H_turnoverRatio_L40', 'A_turnoverRatio_L40']
df_stat_flatten

,gameId,H_DUEL,A_DUEL,H_GAME_DATE,A_GAME_DATE,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,H_PCT_LANCER_FRANC_L40,...,H_pacePer40_L40,A_pacePer40_L40,H_pace_L40,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.08000,NaN,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,10,18,0.337725,0.377300,0.781725,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,28,24,0.368950,0.373950,0.775000,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,23,23,0.372450,0.363350,0.825300,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,28,20,0.381350,0.382275,0.766050,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,26,23,0.347000,0.380600,0.768000,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275

In [7]:
df_stat_flatten = df_stat_flatten.drop('A_DUEL', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_GAME_DATE', axis=1)
df_stat_flatten = df_stat_flatten.drop('A_WL', axis=1)
df_stat_flatten = df_stat_flatten.rename(columns={'H_DUEL': 'DUEL', 'H_GAME_DATE': 'GAME_DATE', 'H_WL': 'HOME_WON'})
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('W', 1)
df_stat_flatten['HOME_WON'] = df_stat_flatten['HOME_WON'].replace('L', 0)
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,H_PCT_LANCER_FRANC_L40,A_PCT_LANCER_FRANC_L40,H_PCT_TIR_REUSSI_L40,...,H_pacePer40_L40,A_pacePer40_L40,H_pace_L40,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,NaN,82.08000,NaN,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,10,18,0.337725,0.377300,0.781725,0.756950,0.444075,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12970,22301227,BOS vs. NYK,2023-12-08,28,24,0.368950,0.373950,0.775000,0.740825,0.475750,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12971,22301228,PHX vs. SAC,2023-12-08,23,23,0.372450,0.363350,0.825300,0.749525,0.476625,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12972,22301229,MIL vs. IND,2023-12-07,28,20,0.381350,0.382275,0.766050,0.785175,0.499350,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12973,22301230,LAL vs. NOP,2023-12-07,26,23,0.347000,0.380600,0.768000,0.789775,0.487175,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275

In [8]:
df_stat_flatten.to_csv('../dataset/team_stat_flatten_L40.csv', index=False)

In [9]:
nba_elo = pd.read_csv('../dataset/nba_elo.csv', dtype=data_type )

In [10]:
nba_elo_copy= nba_elo.copy()
nba_elo_copy

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,elo1_post,elo2_post,score1,score2,is_home
0,1946-11-01,1947,0,NaN,TRH,NYK,1300.000000,1300.000000,0.640065,0.359935,1293.276700,1306.723300,66,68,1
1,1946-11-01,1947,0,NaN,NYK,TRH,1300.000000,1300.000000,0.359935,0.640065,1306.723300,1293.276700,68,66,0
2,1946-11-02,1947,0,NaN,PRO,BOS,1300.000000,1300.000000,0.640065,0.359935,1305.154200,1294.845800,59,53,1
3,1946-11-02,1947,0,NaN,STB,PIT,1300.000000,1300.000000,0.640065,0.359935,1304.690800,1295.309200,56,51,1
4,1946-11-02,1947,0,NaN,CHS,NYK,1300.000000,1306.723300,0.631101,0.368899,1309.652100,1297.071200,63,47,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148933,2024-03-30,2024,0,NaN,MEM,ORL,1325.023208,1523.156879,0.152362,0.847638,1319.643511,1528.536576,88,118,0
148934,2024-03-30,2024,0,NaN,MIL,ATL,1586.179279,1493.120229,0.490012,0.509988,1596.162979,1483.136529,122,113,0
148935,2024-03-30,2024,0,NaN,NOP,BOS,1635.324867,1758.207851,0.467116,0.532884,1624.649366,1768.883352,92,104,1
148936,2024-03-30,2024,0,NaN,ORL,MEM,1523.156879,1325.023208,0.847638,0.152362,1528.536576,1319.643511,118,88,1
148937,2024-03-30,2024,0,NaN,ATL,MIL,1493.120229,1586.179279,0.509988,0.490012,1483.136529,1596.162979,113,122,1

In [11]:
columns_list = nba_elo_copy.columns.tolist()

print(columns_list)

['date', 'season', 'neutral', 'playoff', 'team1', 'team2', 'elo1_pre', 'elo2_pre', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']

In [12]:
columns_to_drop = ['season',  'neutral', 'playoff', 'team2', 'elo_prob1', 'elo_prob2', 'elo1_post', 'elo2_post', 'score1', 'score2', 'is_home']  # Liste des noms des colonnes à supprimer
nba_elo_copy_drop= nba_elo_copy.drop(columns=columns_to_drop)

In [13]:
nba_elo_copy_drop

              date team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [14]:
nba_elo_copy_drop['team1'] = nba_elo_copy_drop['team1'].replace({'PHO': 'PHX', 'BRK': 'BKN', 'CHO': 'CHA'})

In [15]:
df_stat_flatten['team1'] = df_stat_flatten['DUEL'].str.split(' vs. ').str[0]

In [16]:
df_stat_flatten

,gameId,DUEL,GAME_DATE,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,H_PCT_LANCER_FRANC_L40,A_PCT_LANCER_FRANC_L40,H_PCT_TIR_REUSSI_L40,...,A_pacePer40_L40,H_pace_L40,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40,team1
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,82.08000,NaN,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000,PHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,10,18,0.337725,0.377300,0.781725,0.756950,0.444075,...,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550,POR
12970,22301227,BOS vs. NYK,2023-12-08,28,24,0.368950,0.373950,0.775000,0.740825,0.475750,...,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125,BOS
12971,22301228,PHX vs. SAC,2023-12-08,23,23,0.372450,0.363350,0.825300,0.749525,0.476625,...,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950,PHX
12972,22301229,MIL vs. IND,2023-12-07,28,20,0.381350,0.382275,0.766050,0.785175,0.499350,...,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950,MIL
12973,22301230,LAL vs. NOP,2023-12-07,26,23,0.347000,0.380600,0.768000,0.789775,0.487175,...,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275,LAL

In [17]:
new_column_names = {'date':'GAME_DATE' }
nba_elo_copy_drop_rename= nba_elo_copy_drop.rename(columns=new_column_names)
nba_elo_copy_drop_rename

         GAME_DATE team1     elo1_pre     elo2_pre
0       1946-11-01   TRH  1300.000000  1300.000000
1       1946-11-01   NYK  1300.000000  1300.000000
2       1946-11-02   PRO  1300.000000  1300.000000
3       1946-11-02   STB  1300.000000  1300.000000
4       1946-11-02   CHS  1300.000000  1306.723300
...            ...   ...          ...          ...
148933  2024-03-30   MEM  1325.023208  1523.156879
148934  2024-03-30   MIL  1586.179279  1493.120229
148935  2024-03-30   NOP  1635.324867  1758.207851
148936  2024-03-30   ORL  1523.156879  1325.023208
148937  2024-03-30   ATL  1493.120229  1586.179279

[148938 rows x 4 columns]

In [18]:
result = pd.merge(df_stat_flatten, nba_elo_copy_drop_rename, on=['GAME_DATE', 'team1'])

In [19]:
result

,gameId,DUEL,GAME_DATE,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,H_PCT_LANCER_FRANC_L40,A_PCT_LANCER_FRANC_L40,H_PCT_TIR_REUSSI_L40,...,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40,team1,elo1_pre,elo2_pre
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,10,18,0.337725,0.377300,0.781725,0.756950,0.444075,...,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,28,24,0.368950,0.373950,0.775000,0.740825,0.475750,...,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,23,23,0.372450,0.363350,0.825300,0.749525,0.476625,...,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,28,20,0.381350,0.382275,0.766050,0.785175,0.499350,...,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,26,23,0.347000,0.380600,0.768000,0.789775,0.487175,...,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275,LAL,1541.467385,1543.760516

In [20]:
new_column_names = {'elo1_pre':'A_ELO' , 'elo2_pre': 'H_ELO'}
result= result.rename(columns=new_column_names)
result

,gameId,DUEL,GAME_DATE,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,H_PCT_LANCER_FRANC_L40,A_PCT_LANCER_FRANC_L40,H_PCT_TIR_REUSSI_L40,...,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40,team1,A_ELO,H_ELO
0,21300001,IND vs. ORL,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN,IND,1583.572100,1313.231700
1,21300002,MIA vs. CHI,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN,MIA,1691.889600,1519.912400
2,21300003,LAL vs. LAC,2013-10-29,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN,LAL,1511.020000,1586.588400
3,21300004,CLE vs. BKN,2013-10-30,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN,CLE,1369.282300,1548.436500
4,21300005,PHI vs. MIA,2013-10-30,0,1,NaN,0.550000,NaN,0.759000,NaN,...,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000,PHI,1459.690400,1695.193200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,10,18,0.337725,0.377300,0.781725,0.756950,0.444075,...,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550,POR,1361.139964,1492.541584
12970,22301227,BOS vs. NYK,2023-12-08,28,24,0.368950,0.373950,0.775000,0.740825,0.475750,...,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125,BOS,1662.122050,1591.374004
12971,22301228,PHX vs. SAC,2023-12-08,23,23,0.372450,0.363350,0.825300,0.749525,0.476625,...,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950,PHX,1551.810711,1526.069995
12972,22301229,MIL vs. IND,2023-12-07,28,20,0.381350,0.382275,0.766050,0.785175,0.499350,...,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950,MIL,1601.142185,1502.061541
12973,22301230,LAL vs. NOP,2023-12-07,26,23,0.347000,0.380600,0.768000,0.789775,0.487175,...,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275,LAL,1541.467385,1543.760516

In [21]:
new_order = ['gameId', 'DUEL','GAME_DATE','HOME_WON','H_ELO','A_ELO','H_NB_WIN_L40','A_NB_WIN_L40', 'H_PCT_3PT_L40',
       'A_PCT_3PT_L40', 'H_PCT_LANCER_FRANC_L40', 'A_PCT_LANCER_FRANC_L40',
       'H_PCT_TIR_REUSSI_L40', 'A_PCT_TIR_REUSSI_L40', 'H_PIE_L40',
       'A_PIE_L40',  'H_assistPercentage_L40',
       'A_assistPercentage_L40', 'H_assistRatio_L40', 'A_assistRatio_L40',
       'H_assistToTurnover_L40', 'A_assistToTurnover_L40',
       'H_defensiveRating_L40', 'A_defensiveRating_L40',
       'H_effectiveFieldGoalPercentage_L40',
       'A_effectiveFieldGoalPercentage_L40', 'H_estimatedDefensiveRating_L40',
       'A_estimatedDefensiveRating_L40', 'H_estimatedNetRating_L40',
       'A_estimatedNetRating_L40', 'H_estimatedOffensiveRating_L40',
       'A_estimatedOffensiveRating_L40', 'H_estimatedPace_L40',
       'A_estimatedPace_L40', 'H_estimatedTeamTurnoverPercentage_L40',
       'A_estimatedTeamTurnoverPercentage_L40', 'H_netRating_L40',
       'A_netRating_L40', 'H_offensiveRating_L40', 'A_offensiveRating_L40',
       'H_pacePer40_L40', 'A_pacePer40_L40', 'H_pace_L40', 'A_pace_L40',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L40',
       'A_trueShootingPercentage_L40', 'H_turnoverRatio_L40',
       'A_turnoverRatio_L40', 'team1']

# Réorganiser les colonnes
result = result.reindex(columns=new_order)

In [22]:
result = result.drop(columns=['team1'])

In [23]:
result = result.dropna()

In [24]:
result.to_csv('../dataset/team_stat_flatten_L40.csv', index=False)
result

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,...,H_pacePer40_L40,A_pacePer40_L40,H_pace_L40,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40
17,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.269000,0.231000,...,82.08000,78.33000,98.50000,94.00000,1610612741,1610612752,0.510000,0.573000,19.4000,23.4000
18,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.381000,0.556000,...,82.08000,87.08000,98.50000,104.50000,1610612746,1610612744,0.553000,0.650000,16.3000,14.3000
19,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.400000,0.333000,...,76.25000,77.50000,91.50000,93.00000,1610612766,1610612739,0.420000,0.495000,8.7000,15.1000
20,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.422000,0.455000,...,81.62000,76.67000,97.94500,92.00000,1610612753,1610612740,0.490000,0.478000,18.0500,16.3000
21,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.400000,0.381000,...,81.67000,84.58000,98.00000,101.50000,1610612764,1610612755,0.554000,0.629000,17.3000,17.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,10,18,0.337725,0.377300,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12970,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,28,24,0.368950,0.373950,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12971,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,23,23,0.372450,0.363350,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12972,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,28,20,0.381350,0.382275,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12973,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,26,23,0.347000,0.380600,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275

In [25]:
data_type = {"gameId": str, "teamId": str}
team_stat_flatten = pd.read_csv('../dataset/team_stat_flatten_L40.csv', dtype=data_type )
team_stat_flatten

,gameId,DUEL,GAME_DATE,HOME_WON,H_ELO,A_ELO,H_NB_WIN_L40,A_NB_WIN_L40,H_PCT_3PT_L40,A_PCT_3PT_L40,...,H_pacePer40_L40,A_pacePer40_L40,H_pace_L40,A_pace_L40,H_teamId,A_teamId,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_turnoverRatio_L40,A_turnoverRatio_L40
0,21300018,CHI vs. NYK,2013-10-31,1,1582.133300,1516.608800,0,1,0.269000,0.231000,...,82.08000,78.33000,98.50000,94.00000,1610612741,1610612752,0.510000,0.573000,19.4000,23.4000
1,21300019,LAC vs. GSW,2013-10-31,1,1574.897700,1575.414200,0,1,0.381000,0.556000,...,82.08000,87.08000,98.50000,104.50000,1610612746,1610612744,0.553000,0.650000,16.3000,14.3000
2,21300020,CHA vs. CLE,2013-11-01,1,1377.546500,1349.502100,0,1,0.400000,0.333000,...,76.25000,77.50000,91.50000,93.00000,1610612766,1610612739,0.420000,0.495000,8.7000,15.1000
3,21300021,ORL vs. NOP,2013-11-01,1,1422.004600,1309.402000,0,0,0.422000,0.455000,...,81.62000,76.67000,97.94500,92.00000,1610612753,1610612740,0.490000,0.478000,18.0500,16.3000
4,21300022,WAS vs. PHI,2013-11-01,0,1469.418000,1452.716800,0,1,0.400000,0.381000,...,81.67000,84.58000,98.00000,101.50000,1610612764,1610612755,0.554000,0.629000,17.3000,17.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,POR vs. DAL,2023-12-08,0,1492.541584,1361.139964,10,18,0.337725,0.377300,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12953,22301227,BOS vs. NYK,2023-12-08,1,1591.374004,1662.122050,28,24,0.368950,0.373950,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12954,22301228,PHX vs. SAC,2023-12-08,0,1526.069995,1551.810711,23,23,0.372450,0.363350,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12955,22301229,MIL vs. IND,2023-12-07,0,1502.061541,1601.142185,28,20,0.381350,0.382275,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12956,22301230,LAL vs. NOP,2023-12-07,1,1543.760516,1541.467385,26,23,0.347000,0.380600,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275

In [26]:
team_stat_flatten.columns

Index(['gameId', 'DUEL', 'GAME_DATE', 'HOME_WON', 'H_ELO', 'A_ELO',
       'H_NB_WIN_L40', 'A_NB_WIN_L40', 'H_PCT_3PT_L40', 'A_PCT_3PT_L40',
       'H_PCT_LANCER_FRANC_L40', 'A_PCT_LANCER_FRANC_L40',
       'H_PCT_TIR_REUSSI_L40', 'A_PCT_TIR_REUSSI_L40', 'H_PIE_L40',
       'A_PIE_L40', 'H_assistPercentage_L40', 'A_assistPercentage_L40',
       'H_assistRatio_L40', 'A_assistRatio_L40', 'H_assistToTurnover_L40',
       'A_assistToTurnover_L40', 'H_defensiveRating_L40',
       'A_defensiveRating_L40', 'H_effectiveFieldGoalPercentage_L40',
       'A_effectiveFieldGoalPercentage_L40', 'H_estimatedDefensiveRating_L40',
       'A_estimatedDefensiveRating_L40', 'H_estimatedNetRating_L40',
       'A_estimatedNetRating_L40', 'H_estimatedOffensiveRating_L40',
       'A_estimatedOffensiveRating_L40', 'H_estimatedPace_L40',
       'A_estimatedPace_L40', 'H_estimatedTeamTurnoverPercentage_L40',
       'A_estimatedTeamTurnoverPercentage_L40', 'H_netRating_L40',
       'A_netRating_L40', 'H_offensiveRating_L40', 'A_offensiveRating_L40',
       'H_pacePer40_L40', 'A_pacePer40_L40', 'H_pace_L40', 'A_pace_L40',
       'H_teamId', 'A_teamId', 'H_trueShootingPercentage_L40',
       'A_trueShootingPercentage_L40', 'H_turnoverRatio_L40',
       'A_turnoverRatio_L40'],
      dtype='object')

In [27]:
team_stat_flatten = team_stat_flatten.drop(columns=['DUEL', 'GAME_DATE','H_teamId', 'A_teamId'])
colonne_a_supprimer = team_stat_flatten.columns[2:]
# Boucle sur chaque paire de colonnes pour calculer la différence
for colonne in colonne_a_supprimer:
    # Extraire le préfixe de la colonne ('H_' ou 'A_')
    prefixe = colonne[0:2]
    # Extraire le nom de la colonne sans le préfixe
    nom_colonne = colonne[2:]
    # Créer une nouvelle colonne pour stocker la différence
    team_stat_flatten[f'{nom_colonne}'] = team_stat_flatten.apply(lambda row: row[f'H_{nom_colonne}'] - row[f'A_{nom_colonne}'], axis=1)

team_stat_flatten = team_stat_flatten.drop(columns=colonne_a_supprimer)
       
team_stat_flatten

,gameId,HOME_WON,ELO,NB_WIN_L40,PCT_3PT_L40,PCT_LANCER_FRANC_L40,PCT_TIR_REUSSI_L40,PIE_L40,assistPercentage_L40,assistRatio_L40,...,estimatedNetRating_L40,estimatedOffensiveRating_L40,estimatedPace_L40,estimatedTeamTurnoverPercentage_L40,netRating_L40,offensiveRating_L40,pacePer40_L40,pace_L40,trueShootingPercentage_L40,turnoverRatio_L40
0,21300018,1,65.524500,-1,0.038000,-0.099000,-0.085000,-0.188000,0.185000,2.5000,...,-24.1000,-1.4000,4.06000,-4.495000,-18.5000,1.2000,3.75000,4.50000,-0.063000,-4.0000
1,21300019,1,-0.516500,-1,-0.175000,-0.218000,-0.041000,-0.206000,-0.080000,-3.6000,...,-36.8000,-16.2000,-2.46000,1.736000,-40.8000,-13.9000,-5.00000,-6.00000,-0.097000,2.0000
2,21300020,1,28.044400,-1,0.067000,-0.026000,-0.050000,-0.168000,-0.176000,-4.1000,...,-23.0000,-13.5000,-4.58000,-6.000000,-19.6000,-15.2000,-1.25000,-1.50000,-0.075000,-6.4000
3,21300021,1,112.602600,0,-0.033000,-0.204500,0.028500,-0.003500,-0.040500,0.0000,...,-4.4500,-2.0500,6.74500,1.312000,-2.6000,-0.6000,4.95000,5.94500,0.012000,1.7500
4,21300022,0,16.701200,-1,0.019000,-0.083000,-0.102000,-0.154000,0.118000,-0.7000,...,-13.7000,-7.2000,-3.84000,-0.206000,-14.1000,-7.7000,-2.91000,-3.50000,-0.075000,-0.3000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12952,22301226,0,131.401620,-8,-0.039575,0.024775,-0.031875,-0.056525,-0.007125,-1.5125,...,-11.3825,-11.6200,0.02350,3.303925,-10.0525,-11.1500,0.00675,0.00875,-0.049975,3.4625
12953,22301227,1,-70.748046,4,-0.005000,0.034175,0.003775,0.031275,0.048825,1.5825,...,5.4950,0.3050,1.11500,0.088050,4.9100,0.0400,0.86800,1.04250,0.015600,0.0500
12954,22301228,0,-25.740716,0,0.009100,0.075775,0.001475,0.030225,-0.007800,-0.3500,...,2.1225,-1.0300,-1.02350,1.333375,2.5300,0.0600,-1.44025,-1.72825,-0.000500,1.4675
12955,22301229,0,-99.080644,8,-0.000925,-0.019125,-0.002050,0.023800,-0.026950,-0.9450,...,5.1725,0.0625,-1.59775,0.540650,3.7400,-1.8275,-0.56900,-0.68250,0.004500,0.3600
12956,22301230,1,2.293131,3,-0.033600,-0.021775,0.001625,0.004275,-0.008000,-0.3975,...,-1.1275,-1.4600,0.97175,0.137225,-1.0950,-1.2725,0.67650,0.81150,-0.001625,0.1300

In [28]:
team_stat_flatten.to_csv('../dataset/final_dataset_diff_L40.csv', index=False)