In [1]:
import pandas as pd

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
25944,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
25945,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
25946,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
25947,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [3]:
df_stat_last_30_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L30', 'PCT_TIR_REUSSI_L30','PCT_3PTS_L30', 
                           'PCT_LANCER_FRANC_L30','estimatedOffensiveRating_L30', 'offensiveRating_L30',
                           'estimatedDefensiveRating_L30',
                           'defensiveRating_L30','estimatedNetRating_L30', 'netRating_L30', 'assistPercentage_L30',
                           'assistToTurnover_L30', 'assistRatio_L30','estimatedTeamTurnoverPercentage_L30', 'turnoverRatio_L30',
                           'effectiveFieldGoalPercentage_L30','trueShootingPercentage_L30', 'estimatedPace_L30', 'pace_L30',
                           'pacePer40_L30', 'PIE_L30'])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_30_games = team_stats.iloc[max(0, index - 30):index]
        df_last_30_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L30" : (df_last_30_games['WL'] == 'W').sum(),
                   "PCT_TIR_REUSSI_L30" : df_last_30_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L30" : df_last_30_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L30" : df_last_30_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L30" : df_last_30_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L30" : df_last_30_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L30" : df_last_30_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L30" : df_last_30_games['defensiveRating'].mean(),
                   "estimatedNetRating_L30" : df_last_30_games['estimatedNetRating'].mean(),
                   "netRating_L30" : df_last_30_games['netRating'].mean(),
                   "assistPercentage_L30" : df_last_30_games['assistPercentage'].mean(),
                   "assistToTurnover_L30" : df_last_30_games['assistToTurnover'].mean(),
                   "assistRatio_L30" : df_last_30_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L30" : df_last_30_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L30" : df_last_30_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L30" : df_last_30_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L30" : df_last_30_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L30" : df_last_30_games['estimatedPace'].mean(),
                   "pace_L30" : df_last_30_games['pace'].mean(),
                   "pacePer40_L30" : df_last_30_games['pacePer40'].mean(),
                   "PIE_L30" : df_last_30_games['PIE'].mean()}
        df_stat_last_30_perf.loc[len(df_stat_last_30_perf)] = new_row
        index += 1
df_stat_last_30_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L30,PCT_TIR_REUSSI_L30,PCT_3PTS_L30,PCT_LANCER_FRANC_L30,estimatedOffensiveRating_L30,...,assistToTurnover_L30,assistRatio_L30,estimatedTeamTurnoverPercentage_L30,turnoverRatio_L30,effectiveFieldGoalPercentage_L30,trueShootingPercentage_L30,estimatedPace_L30,pace_L30,pacePer40_L30,PIE_L30
0,21300003,1610612746,2013-10-29,LAC @ LAL,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300019,1610612746,2013-10-31,LAC vs. GSW,W,0,0.494000,0.381000,0.565000,103.900000,...,1.690000,19.800000,16.142000,16.300000,0.542000,0.553000,102.720000,98.500000,82.080000,0.497000
2,21300031,1610612746,2013-11-01,LAC @ SAC,W,1,0.494000,0.351000,0.612500,109.200000,...,1.555000,18.700000,16.707500,17.050000,0.544500,0.571000,105.240000,102.750000,85.625000,0.537000
3,21300050,1610612746,2013-11-04,LAC vs. HOU,W,2,0.496000,0.400667,0.683000,113.566667,...,1.613333,19.333333,16.696333,17.033333,0.558333,0.596333,100.666667,98.000000,81.666667,0.544000
4,21300062,1610612746,2013-11-06,LAC @ ORL,L,3,0.502250,0.399250,0.726500,116.500000,...,1.897500,19.950000,15.266500,15.625000,0.569000,0.608250,102.155000,99.750000,83.125000,0.550250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300889,1610612752,2024-03-05,NYK vs. ATL,L,19,0.463833,0.364000,0.800233,114.620000,...,1.997000,17.883333,13.569933,13.953333,0.540133,0.574667,96.958000,95.100000,79.248667,0.519433
25944,22300912,1610612752,2024-03-08,NYK vs. ORL,W,19,0.460833,0.358967,0.801000,114.026667,...,2.015000,17.960000,13.533867,13.910000,0.536867,0.571100,96.788667,94.883333,79.068333,0.518433
25945,22300927,1610612752,2024-03-10,NYK vs. PHI,L,19,0.462267,0.363367,0.799800,114.040000,...,2.005667,17.973333,13.644867,14.020000,0.539400,0.572467,96.426000,94.533333,78.776667,0.523667
25946,22300939,1610612752,2024-03-12,NYK vs. PHI,W,18,0.455867,0.357700,0.797533,112.690000,...,1.975333,17.776667,13.854667,14.266667,0.532067,0.565833,96.198000,94.266667,78.554667,0.519433
25947,22300960,1610612752,2024-03-14,NYK @ POR,W,18,0.456633,0.354733,0.792200,112.490000,...,1.988000,17.950000,13.917600,14.330000,0.532433,0.565133,95.794000,93.850000,78.207667,0.521400

In [4]:
df_stat_last_30_perf.to_csv('../dataset/team_stat_last_30.csv', index=False)

In [5]:
df_stat_last_30_perf = df_stat_last_30_perf.sort_values(by='gameId')
df_stat_last_30_perf.reset_index(drop=True, inplace=True)
df_stat_last_30_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L30,PCT_TIR_REUSSI_L30,PCT_3PTS_L30,PCT_LANCER_FRANC_L30,estimatedOffensiveRating_L30,...,assistToTurnover_L30,assistRatio_L30,estimatedTeamTurnoverPercentage_L30,turnoverRatio_L30,effectiveFieldGoalPercentage_L30,trueShootingPercentage_L30,estimatedPace_L30,pace_L30,pacePer40_L30,PIE_L30
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612756,2023-12-08,PHX vs. SAC,L,19,0.470700,0.377867,0.828667,114.153333,...,2.203667,19.043333,13.560900,13.880000,0.540567,0.586700,100.221000,97.857333,81.547667,0.532600
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,20,0.496033,0.380133,0.770367,116.750000,...,2.038667,18.640000,13.339200,13.526667,0.577367,0.607833,103.455667,101.882667,84.902000,0.506533
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,14,0.501800,0.386333,0.789500,116.856667,...,2.352000,20.170000,13.160267,13.536667,0.576800,0.608933,106.488667,103.900000,86.583333,0.491767
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,19,0.489467,0.344633,0.762233,111.460000,...,2.003667,18.933333,13.940133,14.146667,0.549833,0.586500,102.511000,100.783000,83.986000,0.521200
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,17,0.483767,0.369100,0.776800,113.220000,...,1.988667,18.690000,13.575633,13.790000,0.546167,0.585400,101.506000,99.751000,83.126000,0.519500

In [6]:
df_stat_last_30_perf.to_csv('../dataset/team_stat_last_30.csv', index=False)

In [7]:
a = df_stat_last_30_perf[df_stat_last_30_perf['gameId'] == '21300018']
a

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L30,PCT_TIR_REUSSI_L30,PCT_3PTS_L30,PCT_LANCER_FRANC_L30,estimatedOffensiveRating_L30,...,assistToTurnover_L30,assistRatio_L30,estimatedTeamTurnoverPercentage_L30,turnoverRatio_L30,effectiveFieldGoalPercentage_L30,trueShootingPercentage_L30,estimatedPace_L30,pace_L30,pacePer40_L30,PIE_L30
34,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,95.3,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589
35,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,93.9,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401

In [8]:
a.reset_index(inplace=True)
a

,index,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L30,PCT_TIR_REUSSI_L30,PCT_3PTS_L30,PCT_LANCER_FRANC_L30,...,assistToTurnover_L30,assistRatio_L30,estimatedTeamTurnoverPercentage_L30,turnoverRatio_L30,effectiveFieldGoalPercentage_L30,trueShootingPercentage_L30,estimatedPace_L30,pace_L30,pacePer40_L30,PIE_L30
0,34,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589
1,35,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401

In [9]:
for game_id in list(set(df_stat_last_30_perf['gameId'].tolist())):
    df_game = df_stat_last_30_perf[df_stat_last_30_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_30_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_30_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_30_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L30,PCT_TIR_REUSSI_L30,PCT_3PTS_L30,PCT_LANCER_FRANC_L30,estimatedOffensiveRating_L30,...,assistToTurnover_L30,assistRatio_L30,estimatedTeamTurnoverPercentage_L30,turnoverRatio_L30,effectiveFieldGoalPercentage_L30,trueShootingPercentage_L30,estimatedPace_L30,pace_L30,pacePer40_L30,PIE_L30
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,16,0.468467,0.347433,0.745500,114.113333,...,2.368000,19.383333,12.439667,12.626667,0.547867,0.579700,101.856333,100.078333,83.399000,0.488067
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,20,0.496033,0.380133,0.770367,116.750000,...,2.038667,18.640000,13.339200,13.526667,0.577367,0.607833,103.455667,101.882667,84.902000,0.506533
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,14,0.501800,0.386333,0.789500,116.856667,...,2.352000,20.170000,13.160267,13.536667,0.576800,0.608933,106.488667,103.900000,86.583333,0.491767
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,19,0.489467,0.344633,0.762233,111.460000,...,2.003667,18.933333,13.940133,14.146667,0.549833,0.586500,102.511000,100.783000,83.986000,0.521200
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,17,0.483767,0.369100,0.776800,113.220000,...,1.988667,18.690000,13.575633,13.790000,0.546167,0.585400,101.506000,99.751000,83.126000,0.519500

In [10]:
df_stat_last_30_perf.to_csv('../dataset/team_stat_last_30.csv', index=False)
print(df_stat_last_30_perf.columns)

Index(['gameId', 'teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L30',
       'PCT_TIR_REUSSI_L30', 'PCT_3PTS_L30', 'PCT_LANCER_FRANC_L30',
       'estimatedOffensiveRating_L30', 'offensiveRating_L30',
       'estimatedDefensiveRating_L30', 'defensiveRating_L30',
       'estimatedNetRating_L30', 'netRating_L30', 'assistPercentage_L30',
       'assistToTurnover_L30', 'assistRatio_L30',
       'estimatedTeamTurnoverPercentage_L30', 'turnoverRatio_L30',
       'effectiveFieldGoalPercentage_L30', 'trueShootingPercentage_L30',
       'estimatedPace_L30', 'pace_L30', 'pacePer40_L30', 'PIE_L30'],
      dtype='object')

In [11]:
df_stat_last_30_perf['col'] = df_stat_last_30_perf.groupby('gameId').cumcount() + 1
df_stat_last_30_perf = df_stat_last_30_perf.pivot_table(index='gameId', columns=df_stat_last_30_perf.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L30',
       'PCT_TIR_REUSSI_L30', 'PCT_3PTS_L30', 'PCT_LANCER_FRANC_L30',
       'estimatedOffensiveRating_L30', 'offensiveRating_L30',
       'estimatedDefensiveRating_L30', 'defensiveRating_L30',
       'estimatedNetRating_L30', 'netRating_L30', 'assistPercentage_L30',
       'assistToTurnover_L30', 'assistRatio_L30',
       'estimatedTeamTurnoverPercentage_L30', 'turnoverRatio_L30',
       'effectiveFieldGoalPercentage_L30', 'trueShootingPercentage_L30',
       'estimatedPace_L30', 'pace_L30', 'pacePer40_L30', 'PIE_L30'], aggfunc='first')
df_stat_last_30_perf.columns = [f'col{col[1]}' for col in df_stat_last_30_perf.columns]

df_stat_last_30_perf
df_applati = df_stat_last_30_perf.reset_index()
df_applati

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.080000,NaN,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,7,14,0.336967,0.372667,0.781567,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,23,17,0.368067,0.381700,0.774233,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,19,16,0.377867,0.347433,0.828667,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,20,14,0.380133,0.386333,0.770367,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,19,17,0.344633,0.369100,0.762233,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000

In [12]:
print(['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L30','PCT_TIR_REUSSI_L30', 'PCT_3PTS_L30', 'PCT_LANCER_FRANC_L30','estimatedOffensiveRating_L30', 'offensiveRating_L30','estimatedDefensiveRating_L30', 'defensiveRating_L30','estimatedNetRating_L30', 'netRating_L30', 'assistPercentage_L30','assistToTurnover_L30', 'assistRatio_L30','estimatedTeamTurnoverPercentage_L30', 'turnoverRatio_L30','effectiveFieldGoalPercentage_L30', 'trueShootingPercentage_L30','estimatedPace_L30', 'pace_L30', 'pacePer40_L30'])
liste_nom_colonnes = df_applati.columns
liste_nom_colonnes

['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L30', 'PCT_TIR_REUSSI_L30', 'PCT_3PTS_L30', 'PCT_LANCER_FRANC_L30', 'estimatedOffensiveRating_L30', 'offensiveRating_L30', 'estimatedDefensiveRating_L30', 'defensiveRating_L30', 'estimatedNetRating_L30', 'netRating_L30', 'assistPercentage_L30', 'assistToTurnover_L30', 'assistRatio_L30', 'estimatedTeamTurnoverPercentage_L30', 'turnoverRatio_L30', 'effectiveFieldGoalPercentage_L30', 'trueShootingPercentage_L30', 'estimatedPace_L30', 'pace_L30', 'pacePer40_L30']

Index(['gameId', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2'],
      dtype='object')

In [13]:
print(len(df_applati.columns))
df_applati.columns = ['game_id','H_TEAM_ID', 'A_TEAM_ID', 'H_GAME_DATE', 'A_GAME_DATE', 'H_DUEL', 'A_DUEL', 'H_WL', 'A_WL', 'H_NB_WIN_L30', 'A_NB_WIN_L30', 'H_PCT_TIR_REUSSI_L30', 'A_PCT_TIR_REUSSI_L30', 'H_PCT_3PTS_L30', 'A_PCT_3PTS_L30', 'H_PCT_LANCER_FRANC_L30', 'A_PCT_LANCER_FRANC_L30', 'H_estimatedOffensiveRating_L30', 'A_estimatedOffensiveRating_L30', 'H_offensiveRating_L30', 'A_offensiveRating_L30', 'H_estimatedDefensiveRating_L30', 'A_estimatedDefensiveRating_L30', 'H_defensiveRating_L30', 'A_defensiveRating_L30', 'H_estimatedNetRating_L30', 'A_estimatedNetRating_L30', 'H_netRating_L30', 'A_netRating_L30', 'H_assistPercentage_L30', 'A_assistPercentage_L30', 'H_assistToTurnover_L30', 'A_assistToTurnover_L30', 'H_assistRatio_L30', 'A_assistRatio_L30', 'H_estimatedTeamTurnoverPercentage_L30', 'A_estimatedTeamTurnoverPercentage_L30', 'H_turnoverRatio_L30', 'A_turnoverRatio_L30', 'H_effectiveFieldGoalPercentage_L30', 'A_effectiveFieldGoalPercentage_L30', 'H_trueShootingPercentage_L30', 'A_trueShootingPercentage_L30', 'H_estimatedPace_L30', 'A_estimatedPace_L30', 'H_pace_L30', 'A_pace_L30', 'H_pacePer40_L30', 'A_pacePer40_L30', 'H_PIE_L30', 'A_PIE_L30']

df_applati

51

,game_id,H_TEAM_ID,A_TEAM_ID,H_GAME_DATE,A_GAME_DATE,H_DUEL,A_DUEL,H_WL,A_WL,H_NB_WIN_L30,...,H_trueShootingPercentage_L30,A_trueShootingPercentage_L30,H_estimatedPace_L30,A_estimatedPace_L30,H_pace_L30,A_pace_L30,H_pacePer40_L30,A_pacePer40_L30,H_PIE_L30,A_PIE_L30
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.080000,NaN,98.500000,1610612755,1610612748,NaN,0.631000,NaN,20.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,7,14,0.336967,0.372667,0.781567,...,83.077333,83.800333,99.692000,100.559667,1610612757,1610612742,0.535867,0.593367,15.243333,11.213333
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,23,17,0.368067,0.381700,0.774233,...,82.453667,81.681000,98.944667,98.016667,1610612738,1610612752,0.599100,0.576200,13.720000,13.646667
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,19,16,0.377867,0.347433,0.828667,...,81.547667,83.399000,97.857333,100.078333,1610612756,1610612758,0.586700,0.579700,13.880000,12.626667
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,20,14,0.380133,0.386333,0.770367,...,84.902000,86.583333,101.882667,103.900000,1610612749,1610612754,0.607833,0.608933,13.526667,13.536667
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,19,17,0.344633,0.369100,0.762233,...,83.986000,83.126000,100.783000,99.751000,1610612747,1610612740,0.586500,0.585400,14.146667,13.790000