In [19]:
import pandas as pd

In [20]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23607,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
23608,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
23609,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
23610,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
23611,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [21]:
nb_games = "10"

In [22]:
df_stat_last_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L'+nb_games, 'PCT_TIR_REUSSI_L'+nb_games,'PCT_3PTS_L'+nb_games, 
                           'PCT_LANCER_FRANC_L'+nb_games,'estimatedOffensiveRating_L'+nb_games, 'offensiveRating_L'+nb_games,
                           'estimatedDefensiveRating_L'+nb_games,
                           'defensiveRating_L'+nb_games,'estimatedNetRating_L'+nb_games, 'netRating_L'+nb_games, 'assistPercentage_L'+nb_games,
                           'assistToTurnover_L'+nb_games, 'assistRatio_L'+nb_games,'estimatedTeamTurnoverPercentage_L'+nb_games, 'turnoverRatio_L'+nb_games,
                           'effectiveFieldGoalPercentage_L'+nb_games,'trueShootingPercentage_L'+nb_games, 'estimatedPace_L'+nb_games, 'pace_L'+nb_games,
                           'pacePer40_L'+nb_games, 'PIE_L'+nb_games])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_10_games = team_stats.iloc[max(0, index - int(nb_games)):index]
        df_last_10_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L"+nb_games : (df_last_10_games['WL'] == 'W').sum() / int(nb_games),
                   "PCT_TIR_REUSSI_L"+nb_games : df_last_10_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L"+nb_games : df_last_10_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L"+nb_games : df_last_10_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L"+nb_games : df_last_10_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L"+nb_games : df_last_10_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L"+nb_games : df_last_10_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L"+nb_games : df_last_10_games['defensiveRating'].mean(),
                   "estimatedNetRating_L"+nb_games : df_last_10_games['estimatedNetRating'].mean(),
                   "netRating_L"+nb_games : df_last_10_games['netRating'].mean(),
                   "assistPercentage_L"+nb_games : df_last_10_games['assistPercentage'].mean(),
                   "assistToTurnover_L"+nb_games : df_last_10_games['assistToTurnover'].mean(),
                   "assistRatio_L"+nb_games : df_last_10_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L"+nb_games : df_last_10_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L"+nb_games : df_last_10_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L"+nb_games : df_last_10_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L"+nb_games : df_last_10_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L"+nb_games : df_last_10_games['estimatedPace'].mean(),
                   "pace_L"+nb_games : df_last_10_games['pace'].mean(),
                   "pacePer40_L"+nb_games : df_last_10_games['pacePer40'].mean(),
                   "PIE_L"+nb_games : df_last_10_games['PIE'].mean()}
        df_stat_last_perf.loc[len(df_stat_last_perf)] = new_row
        index += 1
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300012,1610612742,2013-10-30,DAL vs. ATL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300025,1610612742,2013-11-01,DAL @ HOU,L,0.1,0.571000,0.458000,0.792000,117.300000,...,1.5500,22.40,19.889000,19.400000,0.6430,0.67400,101.980000,103.500,86.250,0.533000
2,21300036,1610612742,2013-11-02,DAL vs. MEM,W,0.1,0.475500,0.395500,0.796000,106.800000,...,1.4900,18.10,16.366500,16.300000,0.5340,0.57350,104.600000,104.500,87.085,0.457000
3,21300056,1610612742,2013-11-05,DAL vs. LAL,W,0.2,0.450333,0.386333,0.820667,109.266667,...,1.5400,16.70,14.681667,14.633333,0.5040,0.56700,102.513333,102.000,85.000,0.506667
4,21300069,1610612742,2013-11-06,DAL @ OKC,L,0.3,0.468000,0.410000,0.829750,112.050000,...,1.8625,18.35,13.947750,13.925000,0.5255,0.57875,102.380000,101.875,84.895,0.535500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23607,22300900,1610612760,2024-03-06,OKC @ POR,W,0.7,0.494600,0.405600,0.844200,117.010000,...,2.2250,17.92,11.255600,11.360000,0.5706,0.60380,104.410000,102.900,85.749,0.533100
23608,22300914,1610612760,2024-03-08,OKC vs. MIA,W,0.8,0.513900,0.410300,0.843100,118.990000,...,2.1230,18.02,12.067300,12.150000,0.5874,0.62220,104.074000,102.650,85.541,0.555100
23609,22300931,1610612760,2024-03-10,OKC vs. MEM,W,0.8,0.507000,0.393800,0.846200,117.950000,...,2.1610,17.97,11.948300,11.990000,0.5795,0.61320,103.176000,102.150,85.125,0.551300
23610,22300941,1610612760,2024-03-12,OKC vs. IND,L,0.8,0.504900,0.397900,0.854500,118.330000,...,2.2880,18.44,11.807100,11.840000,0.5810,0.61110,102.602000,101.550,84.625,0.561500
23611,22300959,1610612760,2024-03-14,OKC vs. DAL,W,0.7,0.492700,0.387100,0.857200,116.490000,...,2.3130,18.36,11.602500,11.600000,0.5665,0.59750,102.690000,101.800,84.834,0.543600

In [23]:
df_stat_last_perf.to_csv('../dataset/team_stat_last_'+ nb_games +'.csv', index=False)

In [24]:
df_stat_last_perf = df_stat_last_perf.sort_values(by='gameId')
df_stat_last_perf.reset_index(drop=True, inplace=True)
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23607,22301228,1610612756,2023-12-08,PHX vs. SAC,L,0.7,0.4796,0.3954,0.8557,116.10,...,1.974,19.04,14.2232,14.64,0.5493,0.6058,99.228,96.250,80.209,0.5458
23608,22301229,1610612754,2023-12-07,IND @ MIL,W,0.5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
23609,22301229,1610612749,2023-12-07,MIL vs. IND,L,0.8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
23610,22301230,1610612740,2023-12-07,NOP @ LAL,L,0.6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425
23611,22301230,1610612747,2023-12-07,LAL vs. NOP,W,0.7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255

In [25]:
df_stat_last_perf.to_csv('../dataset/team_stat_last_'+ nb_games +'.csv', index=False)

In [26]:
for game_id in list(set(df_stat_last_perf['gameId'].tolist())):
    df_game = df_stat_last_perf[df_stat_last_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L10,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23607,22301228,1610612758,2023-12-08,SAC @ PHX,W,0.6,0.4738,0.3759,0.7684,114.96,...,2.129,19.61,12.9317,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814
23608,22301229,1610612749,2023-12-07,MIL vs. IND,L,0.8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
23609,22301229,1610612754,2023-12-07,IND @ MIL,W,0.5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
23610,22301230,1610612747,2023-12-07,LAL vs. NOP,W,0.7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
23611,22301230,1610612740,2023-12-07,NOP @ LAL,L,0.6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [27]:
df_stat_last_perf.to_csv('../dataset/team_stat_last_'+ nb_games +'.csv', index=False)