In [14]:
import pandas as pd

In [15]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
25944,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
25945,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
25946,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
25947,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [16]:
df_stat_last_40_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L40', 'PCT_TIR_REUSSI_L40','PCT_3PTS_L40', 
                           'PCT_LANCER_FRANC_L40','estimatedOffensiveRating_L40', 'offensiveRating_L40',
                           'estimatedDefensiveRating_L40',
                           'defensiveRating_L40','estimatedNetRating_L40', 'netRating_L40', 'assistPercentage_L40',
                           'assistToTurnover_L40', 'assistRatio_L40','estimatedTeamTurnoverPercentage_L40', 'turnoverRatio_L40',
                           'effectiveFieldGoalPercentage_L40','trueShootingPercentage_L40', 'estimatedPace_L40', 'pace_L40',
                           'pacePer40_L40', 'PIE_L40'])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_40_games = team_stats.iloc[max(0, index - 40):index]
        df_last_40_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L40" : (df_last_40_games['WL'] == 'W').sum(),
                   "PCT_TIR_REUSSI_L40" : df_last_40_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L40" : df_last_40_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L40" : df_last_40_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L40" : df_last_40_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L40" : df_last_40_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L40" : df_last_40_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L40" : df_last_40_games['defensiveRating'].mean(),
                   "estimatedNetRating_L40" : df_last_40_games['estimatedNetRating'].mean(),
                   "netRating_L40" : df_last_40_games['netRating'].mean(),
                   "assistPercentage_L40" : df_last_40_games['assistPercentage'].mean(),
                   "assistToTurnover_L40" : df_last_40_games['assistToTurnover'].mean(),
                   "assistRatio_L40" : df_last_40_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L40" : df_last_40_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L40" : df_last_40_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L40" : df_last_40_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L40" : df_last_40_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L40" : df_last_40_games['estimatedPace'].mean(),
                   "pace_L40" : df_last_40_games['pace'].mean(),
                   "pacePer40_L40" : df_last_40_games['pacePer40'].mean(),
                   "PIE_L40" : df_last_40_games['PIE'].mean()}
        df_stat_last_40_perf.loc[len(df_stat_last_40_perf)] = new_row
        index += 1
df_stat_last_40_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L40,PCT_TIR_REUSSI_L40,PCT_3PTS_L40,PCT_LANCER_FRANC_L40,estimatedOffensiveRating_L40,...,assistToTurnover_L40,assistRatio_L40,estimatedTeamTurnoverPercentage_L40,turnoverRatio_L40,effectiveFieldGoalPercentage_L40,trueShootingPercentage_L40,estimatedPace_L40,pace_L40,pacePer40_L40,PIE_L40
0,21300012,1610612737,2013-10-30,ATL @ DAL,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300023,1610612737,2013-11-01,ATL vs. TOR,W,0,0.487000,0.333000,0.771000,105.400000,...,1.590000,19.900000,16.441000,16.3000,0.539000,0.596000,101.980000,103.500000,86.250000,0.467000
2,21300046,1610612737,2013-11-03,ATL @ LAL,L,1,0.477500,0.384000,0.708000,105.450000,...,1.720000,19.350000,14.946500,15.0000,0.535500,0.579500,99.190000,99.250000,82.710000,0.527000
3,21300059,1610612737,2013-11-05,ATL @ SAC,W,1,0.466333,0.392333,0.651333,103.166667,...,1.813333,19.066667,14.113333,14.1000,0.521667,0.555667,101.293333,101.333333,84.446667,0.510000
4,21300071,1610612737,2013-11-07,ATL @ DEN,L,2,0.470000,0.385250,0.671250,104.325000,...,1.825000,19.200000,14.177000,14.2250,0.524000,0.558750,100.305000,100.125000,83.440000,0.522250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300904,1610612748,2024-03-07,MIA @ DAL,L,23,0.461900,0.369925,0.810175,111.102500,...,2.223500,19.185000,13.160200,13.4000,0.534500,0.574975,98.603750,96.772000,80.643250,0.503500
25944,22300914,1610612748,2024-03-08,MIA @ OKC,L,23,0.463350,0.372175,0.809675,111.427500,...,2.254000,19.325000,13.027400,13.2650,0.536350,0.576675,98.523250,96.659500,80.549500,0.505650
25945,22300926,1610612748,2024-03-10,MIA vs. WAS,L,22,0.462900,0.370925,0.807875,111.035000,...,2.238000,19.227500,13.030600,13.2625,0.535150,0.574800,98.460750,96.684500,80.570500,0.503600
25946,22300949,1610612748,2024-03-13,MIA vs. DEN,L,21,0.462300,0.366000,0.800875,110.872500,...,2.245000,19.100000,12.782925,13.0075,0.533675,0.572700,98.465750,96.672000,80.560000,0.501775
25947,22300962,1610612748,2024-03-15,MIA @ DET,W,21,0.461350,0.360925,0.802425,110.400000,...,2.236000,19.002500,12.756475,12.9775,0.531175,0.570000,98.228750,96.459500,80.383000,0.501400

In [17]:
df_stat_last_40_perf.to_csv('../dataset/team_stat_last_40.csv', index=False)

In [18]:
df_stat_last_40_perf = df_stat_last_40_perf.sort_values(by='gameId')
df_stat_last_40_perf.reset_index(drop=True, inplace=True)
df_stat_last_40_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L40,PCT_TIR_REUSSI_L40,PCT_3PTS_L40,PCT_LANCER_FRANC_L40,estimatedOffensiveRating_L40,...,assistToTurnover_L40,assistRatio_L40,estimatedTeamTurnoverPercentage_L40,turnoverRatio_L40,effectiveFieldGoalPercentage_L40,trueShootingPercentage_L40,estimatedPace_L40,pace_L40,pacePer40_L40,PIE_L40
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612746,2013-10-29,LAC @ LAL,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,23,0.475150,0.363350,0.749525,115.8900,...,2.50525,19.5525,12.027375,12.1950,0.557275,0.589900,101.81925,100.24625,83.53875,0.493575
25944,22301229,1610612754,2023-12-07,IND @ MIL,W,20,0.501400,0.382275,0.785175,117.1750,...,2.39550,20.1000,12.776800,13.0950,0.576075,0.607525,105.57125,103.16200,85.96850,0.496175
25945,22301229,1610612749,2023-12-07,MIL vs. IND,L,28,0.499350,0.381350,0.766050,117.2375,...,2.07550,19.1550,13.317450,13.4550,0.582800,0.612025,103.97350,102.47950,85.39950,0.519975
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,26,0.487175,0.347000,0.768000,111.9800,...,1.98200,18.7525,13.842300,14.0575,0.548725,0.587575,102.20775,100.34975,83.62525,0.527625
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,23,0.485550,0.380600,0.789775,113.4400,...,2.01725,19.1500,13.705075,13.9275,0.551425,0.589200,101.23600,99.53825,82.94875,0.523350

In [19]:
df_stat_last_40_perf.to_csv('../dataset/team_stat_last_40.csv', index=False)

In [20]:
a = df_stat_last_40_perf[df_stat_last_40_perf['gameId'] == '21300018']
a

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L40,PCT_TIR_REUSSI_L40,PCT_3PTS_L40,PCT_LANCER_FRANC_L40,estimatedOffensiveRating_L40,...,assistToTurnover_L40,assistRatio_L40,estimatedTeamTurnoverPercentage_L40,turnoverRatio_L40,effectiveFieldGoalPercentage_L40,trueShootingPercentage_L40,estimatedPace_L40,pace_L40,pacePer40_L40,PIE_L40
34,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,93.9,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401
35,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,95.3,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589

In [21]:
a.reset_index(inplace=True)
a

,index,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L40,PCT_TIR_REUSSI_L40,PCT_3PTS_L40,PCT_LANCER_FRANC_L40,...,assistToTurnover_L40,assistRatio_L40,estimatedTeamTurnoverPercentage_L40,turnoverRatio_L40,effectiveFieldGoalPercentage_L40,trueShootingPercentage_L40,estimatedPace_L40,pace_L40,pacePer40_L40,PIE_L40
0,34,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401
1,35,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589

In [22]:
for game_id in list(set(df_stat_last_40_perf['gameId'].tolist())):
    df_game = df_stat_last_40_perf[df_stat_last_40_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_40_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_40_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_40_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L40,PCT_TIR_REUSSI_L40,PCT_3PTS_L40,PCT_LANCER_FRANC_L40,estimatedOffensiveRating_L40,...,assistToTurnover_L40,assistRatio_L40,estimatedTeamTurnoverPercentage_L40,turnoverRatio_L40,effectiveFieldGoalPercentage_L40,trueShootingPercentage_L40,estimatedPace_L40,pace_L40,pacePer40_L40,PIE_L40
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,23,0.475150,0.363350,0.749525,115.8900,...,2.50525,19.5525,12.027375,12.1950,0.557275,0.589900,101.81925,100.24625,83.53875,0.493575
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,28,0.499350,0.381350,0.766050,117.2375,...,2.07550,19.1550,13.317450,13.4550,0.582800,0.612025,103.97350,102.47950,85.39950,0.519975
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,20,0.501400,0.382275,0.785175,117.1750,...,2.39550,20.1000,12.776800,13.0950,0.576075,0.607525,105.57125,103.16200,85.96850,0.496175
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,26,0.487175,0.347000,0.768000,111.9800,...,1.98200,18.7525,13.842300,14.0575,0.548725,0.587575,102.20775,100.34975,83.62525,0.527625
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,23,0.485550,0.380600,0.789775,113.4400,...,2.01725,19.1500,13.705075,13.9275,0.551425,0.589200,101.23600,99.53825,82.94875,0.523350

In [23]:
df_stat_last_40_perf.to_csv('../dataset/team_stat_last_40.csv', index=False)
print(df_stat_last_40_perf.columns)

Index(['gameId', 'teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L40',
       'PCT_TIR_REUSSI_L40', 'PCT_3PTS_L40', 'PCT_LANCER_FRANC_L40',
       'estimatedOffensiveRating_L40', 'offensiveRating_L40',
       'estimatedDefensiveRating_L40', 'defensiveRating_L40',
       'estimatedNetRating_L40', 'netRating_L40', 'assistPercentage_L40',
       'assistToTurnover_L40', 'assistRatio_L40',
       'estimatedTeamTurnoverPercentage_L40', 'turnoverRatio_L40',
       'effectiveFieldGoalPercentage_L40', 'trueShootingPercentage_L40',
       'estimatedPace_L40', 'pace_L40', 'pacePer40_L40', 'PIE_L40'],
      dtype='object')

In [24]:
df_stat_last_40_perf['col'] = df_stat_last_40_perf.groupby('gameId').cumcount() + 1
df_stat_last_40_perf = df_stat_last_40_perf.pivot_table(index='gameId', columns=df_stat_last_40_perf.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L40',
       'PCT_TIR_REUSSI_L40', 'PCT_3PTS_L40', 'PCT_LANCER_FRANC_L40',
       'estimatedOffensiveRating_L40', 'offensiveRating_L40',
       'estimatedDefensiveRating_L40', 'defensiveRating_L40',
       'estimatedNetRating_L40', 'netRating_L40', 'assistPercentage_L40',
       'assistToTurnover_L40', 'assistRatio_L40',
       'estimatedTeamTurnoverPercentage_L40', 'turnoverRatio_L40',
       'effectiveFieldGoalPercentage_L40', 'trueShootingPercentage_L40',
       'estimatedPace_L40', 'pace_L40', 'pacePer40_L40', 'PIE_L40'], aggfunc='first')
df_stat_last_40_perf.columns = [f'col{col[1]}' for col in df_stat_last_40_perf.columns]

df_stat_last_40_perf
df_applati = df_stat_last_40_perf.reset_index()
df_applati

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.08000,NaN,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,10,18,0.337725,0.377300,0.781725,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,28,24,0.368950,0.373950,0.775000,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,23,23,0.372450,0.363350,0.825300,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,28,20,0.381350,0.382275,0.766050,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,26,23,0.347000,0.380600,0.768000,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275

In [25]:
print(['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L40','PCT_TIR_REUSSI_L40', 'PCT_3PTS_L40', 'PCT_LANCER_FRANC_L40','estimatedOffensiveRating_L40', 'offensiveRating_L40','estimatedDefensiveRating_L40', 'defensiveRating_L40','estimatedNetRating_L40', 'netRating_L40', 'assistPercentage_L40','assistToTurnover_L40', 'assistRatio_L40','estimatedTeamTurnoverPercentage_L40', 'turnoverRatio_L40','effectiveFieldGoalPercentage_L40', 'trueShootingPercentage_L40','estimatedPace_L40', 'pace_L40', 'pacePer40_L40'])
liste_nom_colonnes = df_applati.columns
liste_nom_colonnes

['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L40', 'PCT_TIR_REUSSI_L40', 'PCT_3PTS_L40', 'PCT_LANCER_FRANC_L40', 'estimatedOffensiveRating_L40', 'offensiveRating_L40', 'estimatedDefensiveRating_L40', 'defensiveRating_L40', 'estimatedNetRating_L40', 'netRating_L40', 'assistPercentage_L40', 'assistToTurnover_L40', 'assistRatio_L40', 'estimatedTeamTurnoverPercentage_L40', 'turnoverRatio_L40', 'effectiveFieldGoalPercentage_L40', 'trueShootingPercentage_L40', 'estimatedPace_L40', 'pace_L40', 'pacePer40_L40']

Index(['gameId', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2'],
      dtype='object')

In [26]:
print(len(df_applati.columns))
df_applati.columns = ['game_id','H_TEAM_ID', 'A_TEAM_ID', 'H_GAME_DATE', 'A_GAME_DATE', 'H_DUEL', 'A_DUEL', 'H_WL', 'A_WL', 'H_NB_WIN_L40', 'A_NB_WIN_L40', 'H_PCT_TIR_REUSSI_L40', 'A_PCT_TIR_REUSSI_L40', 'H_PCT_3PTS_L40', 'A_PCT_3PTS_L40', 'H_PCT_LANCER_FRANC_L40', 'A_PCT_LANCER_FRANC_L40', 'H_estimatedOffensiveRating_L40', 'A_estimatedOffensiveRating_L40', 'H_offensiveRating_L40', 'A_offensiveRating_L40', 'H_estimatedDefensiveRating_L40', 'A_estimatedDefensiveRating_L40', 'H_defensiveRating_L40', 'A_defensiveRating_L40', 'H_estimatedNetRating_L40', 'A_estimatedNetRating_L40', 'H_netRating_L40', 'A_netRating_L40', 'H_assistPercentage_L40', 'A_assistPercentage_L40', 'H_assistToTurnover_L40', 'A_assistToTurnover_L40', 'H_assistRatio_L40', 'A_assistRatio_L40', 'H_estimatedTeamTurnoverPercentage_L40', 'A_estimatedTeamTurnoverPercentage_L40', 'H_turnoverRatio_L40', 'A_turnoverRatio_L40', 'H_effectiveFieldGoalPercentage_L40', 'A_effectiveFieldGoalPercentage_L40', 'H_trueShootingPercentage_L40', 'A_trueShootingPercentage_L40', 'H_estimatedPace_L40', 'A_estimatedPace_L40', 'H_pace_L40', 'A_pace_L40', 'H_pacePer40_L40', 'A_pacePer40_L40', 'H_PIE_L40', 'A_PIE_L40']

df_applati

51

,game_id,H_TEAM_ID,A_TEAM_ID,H_GAME_DATE,A_GAME_DATE,H_DUEL,A_DUEL,H_WL,A_WL,H_NB_WIN_L40,...,H_trueShootingPercentage_L40,A_trueShootingPercentage_L40,H_estimatedPace_L40,A_estimatedPace_L40,H_pace_L40,A_pace_L40,H_pacePer40_L40,A_pacePer40_L40,H_PIE_L40,A_PIE_L40
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.550000,NaN,...,NaN,82.08000,NaN,98.50000,1610612755,1610612748,NaN,0.631000,NaN,20.2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,10,18,0.337725,0.377300,0.781725,...,83.36000,83.35325,100.03150,100.02275,1610612757,1610612742,0.546375,0.596350,15.0175,11.5550
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,28,24,0.368950,0.373950,0.775000,...,82.33025,81.46225,98.79675,97.75425,1610612738,1610612752,0.595900,0.580300,13.5625,13.5125
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,23,23,0.372450,0.363350,0.825300,...,82.09850,83.53875,98.51800,100.24625,1610612756,1610612758,0.589400,0.589900,13.6625,12.1950
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,28,20,0.381350,0.382275,0.766050,...,85.39950,85.96850,102.47950,103.16200,1610612749,1610612754,0.612025,0.607525,13.4550,13.0950
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,26,23,0.347000,0.380600,0.768000,...,83.62525,82.94875,100.34975,99.53825,1610612747,1610612740,0.587575,0.589200,14.0575,13.9275