In [1]:
import pandas as pd

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
25944,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
25945,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
25946,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
25947,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [3]:
df_stat_last_20_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L20', 'PCT_TIR_REUSSI_L20','PCT_3PTS_L20', 
                           'PCT_LANCER_FRANC_L20','estimatedOffensiveRating_L20', 'offensiveRating_L20',
                           'estimatedDefensiveRating_L20',
                           'defensiveRating_L20','estimatedNetRating_L20', 'netRating_L20', 'assistPercentage_L20',
                           'assistToTurnover_L20', 'assistRatio_L20','estimatedTeamTurnoverPercentage_L20', 'turnoverRatio_L20',
                           'effectiveFieldGoalPercentage_L20','trueShootingPercentage_L20', 'estimatedPace_L20', 'pace_L20',
                           'pacePer40_L20', 'PIE_L20'])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_20_games = team_stats.iloc[max(0, index - 20):index]
        df_last_20_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L20" : (df_last_20_games['WL'] == 'W').sum(),
                   "PCT_TIR_REUSSI_L20" : df_last_20_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L20" : df_last_20_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L20" : df_last_20_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L20" : df_last_20_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L20" : df_last_20_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L20" : df_last_20_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L20" : df_last_20_games['defensiveRating'].mean(),
                   "estimatedNetRating_L20" : df_last_20_games['estimatedNetRating'].mean(),
                   "netRating_L20" : df_last_20_games['netRating'].mean(),
                   "assistPercentage_L20" : df_last_20_games['assistPercentage'].mean(),
                   "assistToTurnover_L20" : df_last_20_games['assistToTurnover'].mean(),
                   "assistRatio_L20" : df_last_20_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L20" : df_last_20_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L20" : df_last_20_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L20" : df_last_20_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L20" : df_last_20_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L20" : df_last_20_games['estimatedPace'].mean(),
                   "pace_L20" : df_last_20_games['pace'].mean(),
                   "pacePer40_L20" : df_last_20_games['pacePer40'].mean(),
                   "PIE_L20" : df_last_20_games['PIE'].mean()}
        df_stat_last_20_perf.loc[len(df_stat_last_20_perf)] = new_row
        index += 1
df_stat_last_20_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L20,PCT_TIR_REUSSI_L20,PCT_3PTS_L20,PCT_LANCER_FRANC_L20,estimatedOffensiveRating_L20,...,assistToTurnover_L20,assistRatio_L20,estimatedTeamTurnoverPercentage_L20,turnoverRatio_L20,effectiveFieldGoalPercentage_L20,trueShootingPercentage_L20,estimatedPace_L20,pace_L20,pacePer40_L20,PIE_L20
0,21300007,1610612765,2013-10-30,DET vs. WAS,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300026,1610612765,2013-11-01,DET @ MEM,L,1,0.50000,0.375000,0.78800,113.500000,...,1.260000,17.700,19.09200,19.400,0.55800,0.611000,97.800000,98.000000,81.6700,0.587000
2,21300041,1610612765,2013-11-03,DET vs. BOS,W,1,0.48600,0.354000,0.74800,108.400000,...,1.155000,16.300,19.11000,19.600,0.53450,0.576500,96.165000,94.960000,79.1350,0.505000
3,21300053,1610612765,2013-11-05,DET vs. IND,L,2,0.47300,0.287333,0.69400,102.866667,...,1.023333,15.100,20.12700,20.600,0.51000,0.547667,95.783333,94.473333,78.7300,0.524667
4,21300078,1610612765,2013-11-08,DET vs. OKC,L,2,0.44950,0.265500,0.72050,99.900000,...,0.985000,13.900,18.84525,19.275,0.48450,0.526750,96.477500,95.480000,79.5675,0.484250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300889,1610612752,2024-03-05,NYK vs. ATL,L,12,0.46355,0.357950,0.80120,114.545000,...,2.137000,17.725,12.80205,13.165,0.53630,0.569600,96.017000,94.150000,78.4565,0.509250
25944,22300912,1610612752,2024-03-08,NYK vs. ORL,W,11,0.46010,0.356250,0.79525,114.345000,...,2.185000,17.865,12.61795,12.970,0.53310,0.564700,95.738000,93.725000,78.1025,0.503950
25945,22300927,1610612752,2024-03-10,NYK vs. PHI,L,11,0.45690,0.362550,0.79275,113.875000,...,2.186000,17.785,12.47230,12.830,0.53095,0.561850,95.048000,92.925000,77.4360,0.506250
25946,22300939,1610612752,2024-03-12,NYK vs. PHI,W,10,0.44990,0.356550,0.78290,112.295000,...,2.156000,17.725,12.89410,13.280,0.52385,0.554200,94.664000,92.675000,77.2280,0.502200
25947,22300960,1610612752,2024-03-14,NYK @ POR,W,10,0.44875,0.354300,0.78040,111.565000,...,2.149000,17.950,13.07490,13.480,0.52270,0.552650,94.417000,92.450000,77.0405,0.500450

In [4]:
df_stat_last_20_perf.to_csv('../dataset/team_stat_last_20.csv', index=False)

In [5]:
df_stat_last_20_perf = df_stat_last_20_perf.sort_values(by='gameId')
df_stat_last_20_perf.reset_index(drop=True, inplace=True)
df_stat_last_20_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L20,PCT_TIR_REUSSI_L20,PCT_3PTS_L20,PCT_LANCER_FRANC_L20,estimatedOffensiveRating_L20,...,assistToTurnover_L20,assistRatio_L20,estimatedTeamTurnoverPercentage_L20,turnoverRatio_L20,effectiveFieldGoalPercentage_L20,trueShootingPercentage_L20,estimatedPace_L20,pace_L20,pacePer40_L20,PIE_L20
0,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612746,2013-10-29,LAC @ LAL,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,11,0.46220,0.35120,0.74020,111.640,...,2.0595,19.190,13.34245,13.565,0.54345,0.57510,102.2440,100.555,83.7965,0.47590
25944,22301229,1610612754,2023-12-07,IND @ MIL,W,12,0.50955,0.39560,0.79430,119.950,...,2.5980,20.585,11.85740,12.265,0.59190,0.62130,107.2720,104.400,86.9995,0.50915
25945,22301229,1610612749,2023-12-07,MIL vs. IND,L,14,0.49980,0.38360,0.77305,117.830,...,2.0560,18.375,13.18170,13.410,0.58235,0.61465,103.8145,101.974,84.9780,0.51615
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,12,0.48650,0.33675,0.76650,109.490,...,1.8970,19.050,14.27760,14.500,0.54555,0.58340,102.5400,100.523,83.7695,0.51855
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,10,0.48330,0.36040,0.76325,114.255,...,2.0885,19.000,13.24720,13.420,0.54530,0.58375,101.9380,100.250,83.5420,0.50685

In [6]:
df_stat_last_20_perf.to_csv('../dataset/team_stat_last_20.csv', index=False)

In [7]:
a = df_stat_last_20_perf[df_stat_last_20_perf['gameId'] == '21300018']
a

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L20,PCT_TIR_REUSSI_L20,PCT_3PTS_L20,PCT_LANCER_FRANC_L20,estimatedOffensiveRating_L20,...,assistToTurnover_L20,assistRatio_L20,estimatedTeamTurnoverPercentage_L20,turnoverRatio_L20,effectiveFieldGoalPercentage_L20,trueShootingPercentage_L20,estimatedPace_L20,pace_L20,pacePer40_L20,PIE_L20
34,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,93.9,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401
35,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,95.3,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589

In [8]:
a.reset_index(inplace=True)
a

,index,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L20,PCT_TIR_REUSSI_L20,PCT_3PTS_L20,PCT_LANCER_FRANC_L20,...,assistToTurnover_L20,assistRatio_L20,estimatedTeamTurnoverPercentage_L20,turnoverRatio_L20,effectiveFieldGoalPercentage_L20,trueShootingPercentage_L20,estimatedPace_L20,pace_L20,pacePer40_L20,PIE_L20
0,34,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401
1,35,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589

In [9]:
for game_id in list(set(df_stat_last_20_perf['gameId'].tolist())):
    df_game = df_stat_last_20_perf[df_stat_last_20_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_20_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_20_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_20_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L20,PCT_TIR_REUSSI_L20,PCT_3PTS_L20,PCT_LANCER_FRANC_L20,estimatedOffensiveRating_L20,...,assistToTurnover_L20,assistRatio_L20,estimatedTeamTurnoverPercentage_L20,turnoverRatio_L20,effectiveFieldGoalPercentage_L20,trueShootingPercentage_L20,estimatedPace_L20,pace_L20,pacePer40_L20,PIE_L20
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,11,0.46220,0.35120,0.74020,111.640,...,2.0595,19.190,13.34245,13.565,0.54345,0.57510,102.2440,100.555,83.7965,0.47590
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,14,0.49980,0.38360,0.77305,117.830,...,2.0560,18.375,13.18170,13.410,0.58235,0.61465,103.8145,101.974,84.9780,0.51615
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,12,0.50955,0.39560,0.79430,119.950,...,2.5980,20.585,11.85740,12.265,0.59190,0.62130,107.2720,104.400,86.9995,0.50915
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,12,0.48650,0.33675,0.76650,109.490,...,1.8970,19.050,14.27760,14.500,0.54555,0.58340,102.5400,100.523,83.7695,0.51855
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,10,0.48330,0.36040,0.76325,114.255,...,2.0885,19.000,13.24720,13.420,0.54530,0.58375,101.9380,100.250,83.5420,0.50685

In [10]:
df_stat_last_20_perf.to_csv('../dataset/team_stat_last_20.csv', index=False)
print(df_stat_last_20_perf.columns)

Index(['gameId', 'teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L20',
       'PCT_TIR_REUSSI_L20', 'PCT_3PTS_L20', 'PCT_LANCER_FRANC_L20',
       'estimatedOffensiveRating_L20', 'offensiveRating_L20',
       'estimatedDefensiveRating_L20', 'defensiveRating_L20',
       'estimatedNetRating_L20', 'netRating_L20', 'assistPercentage_L20',
       'assistToTurnover_L20', 'assistRatio_L20',
       'estimatedTeamTurnoverPercentage_L20', 'turnoverRatio_L20',
       'effectiveFieldGoalPercentage_L20', 'trueShootingPercentage_L20',
       'estimatedPace_L20', 'pace_L20', 'pacePer40_L20', 'PIE_L20'],
      dtype='object')

In [11]:
df_stat_last_20_perf['col'] = df_stat_last_20_perf.groupby('gameId').cumcount() + 1
df_stat_last_20_perf = df_stat_last_20_perf.pivot_table(index='gameId', columns=df_stat_last_20_perf.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L20',
       'PCT_TIR_REUSSI_L20', 'PCT_3PTS_L20', 'PCT_LANCER_FRANC_L20',
       'estimatedOffensiveRating_L20', 'offensiveRating_L20',
       'estimatedDefensiveRating_L20', 'defensiveRating_L20',
       'estimatedNetRating_L20', 'netRating_L20', 'assistPercentage_L20',
       'assistToTurnover_L20', 'assistRatio_L20',
       'estimatedTeamTurnoverPercentage_L20', 'turnoverRatio_L20',
       'effectiveFieldGoalPercentage_L20', 'trueShootingPercentage_L20',
       'estimatedPace_L20', 'pace_L20', 'pacePer40_L20', 'PIE_L20'], aggfunc='first')
df_stat_last_20_perf.columns = [f'col{col[1]}' for col in df_stat_last_20_perf.columns]

df_stat_last_20_perf
df_applati = df_stat_last_20_perf.reset_index()
df_applati

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.0800,NaN,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,6,12,0.34245,0.3731,0.79475,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,15,12,0.36370,0.3713,0.78435,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,11,11,0.38865,0.3512,0.84340,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,14,12,0.38360,0.3956,0.77305,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,12,10,0.33675,0.3604,0.76650,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420

In [12]:
print(['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L20','PCT_TIR_REUSSI_L20', 'PCT_3PTS_L20', 'PCT_LANCER_FRANC_L20','estimatedOffensiveRating_L20', 'offensiveRating_L20','estimatedDefensiveRating_L20', 'defensiveRating_L20','estimatedNetRating_L20', 'netRating_L20', 'assistPercentage_L20','assistToTurnover_L20', 'assistRatio_L20','estimatedTeamTurnoverPercentage_L20', 'turnoverRatio_L20','effectiveFieldGoalPercentage_L20', 'trueShootingPercentage_L20','estimatedPace_L20', 'pace_L20', 'pacePer40_L20'])
liste_nom_colonnes = df_applati.columns
liste_nom_colonnes

['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L20', 'PCT_TIR_REUSSI_L20', 'PCT_3PTS_L20', 'PCT_LANCER_FRANC_L20', 'estimatedOffensiveRating_L20', 'offensiveRating_L20', 'estimatedDefensiveRating_L20', 'defensiveRating_L20', 'estimatedNetRating_L20', 'netRating_L20', 'assistPercentage_L20', 'assistToTurnover_L20', 'assistRatio_L20', 'estimatedTeamTurnoverPercentage_L20', 'turnoverRatio_L20', 'effectiveFieldGoalPercentage_L20', 'trueShootingPercentage_L20', 'estimatedPace_L20', 'pace_L20', 'pacePer40_L20']

Index(['gameId', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2'],
      dtype='object')

In [13]:
print(len(df_applati.columns))
df_applati.columns = ['game_id','H_TEAM_ID', 'A_TEAM_ID', 'H_GAME_DATE', 'A_GAME_DATE', 'H_DUEL', 'A_DUEL', 'H_WL', 'A_WL', 'H_NB_WIN_L20', 'A_NB_WIN_L20', 'H_PCT_TIR_REUSSI_L20', 'A_PCT_TIR_REUSSI_L20', 'H_PCT_3PTS_L20', 'A_PCT_3PTS_L20', 'H_PCT_LANCER_FRANC_L20', 'A_PCT_LANCER_FRANC_L20', 'H_estimatedOffensiveRating_L20', 'A_estimatedOffensiveRating_L20', 'H_offensiveRating_L20', 'A_offensiveRating_L20', 'H_estimatedDefensiveRating_L20', 'A_estimatedDefensiveRating_L20', 'H_defensiveRating_L20', 'A_defensiveRating_L20', 'H_estimatedNetRating_L20', 'A_estimatedNetRating_L20', 'H_netRating_L20', 'A_netRating_L20', 'H_assistPercentage_L20', 'A_assistPercentage_L20', 'H_assistToTurnover_L20', 'A_assistToTurnover_L20', 'H_assistRatio_L20', 'A_assistRatio_L20', 'H_estimatedTeamTurnoverPercentage_L20', 'A_estimatedTeamTurnoverPercentage_L20', 'H_turnoverRatio_L20', 'A_turnoverRatio_L20', 'H_effectiveFieldGoalPercentage_L20', 'A_effectiveFieldGoalPercentage_L20', 'H_trueShootingPercentage_L20', 'A_trueShootingPercentage_L20', 'H_estimatedPace_L20', 'A_estimatedPace_L20', 'H_pace_L20', 'A_pace_L20', 'H_pacePer40_L20', 'A_pacePer40_L20', 'H_PIE_L20', 'A_PIE_L20']

df_applati

51

,game_id,H_TEAM_ID,A_TEAM_ID,H_GAME_DATE,A_GAME_DATE,H_DUEL,A_DUEL,H_WL,A_WL,H_NB_WIN_L20,...,H_trueShootingPercentage_L20,A_trueShootingPercentage_L20,H_estimatedPace_L20,A_estimatedPace_L20,H_pace_L20,A_pace_L20,H_pacePer40_L20,A_pacePer40_L20,H_PIE_L20,A_PIE_L20
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.0800,NaN,98.500,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,6,12,0.34245,0.3731,0.79475,...,81.8870,84.0010,98.263,100.800,1610612757,1610612742,0.53640,0.58620,16.125,11.435
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,15,12,0.36370,0.3713,0.78435,...,82.3680,80.8130,98.842,96.975,1610612738,1610612752,0.59455,0.55760,14.125,13.545
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,11,11,0.38865,0.3512,0.84340,...,81.2795,83.7965,97.536,100.555,1610612756,1610612758,0.59945,0.57510,15.175,13.565
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,14,12,0.38360,0.3956,0.77305,...,84.9780,86.9995,101.974,104.400,1610612749,1610612754,0.61465,0.62130,13.410,12.265
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,12,10,0.33675,0.3604,0.76650,...,83.7695,83.5420,100.523,100.250,1610612747,1610612740,0.58340,0.58375,14.500,13.420