In [1]:
import pandas as pd

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
25944,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
25945,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
25946,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
25947,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [3]:
df_stat_last_50_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN_L50', 'PCT_TIR_REUSSI_L50','PCT_3PTS_L50', 
                           'PCT_LANCER_FRANC_L50','estimatedOffensiveRating_L50', 'offensiveRating_L50',
                           'estimatedDefensiveRating_L50',
                           'defensiveRating_L50','estimatedNetRating_L50', 'netRating_L50', 'assistPercentage_L50',
                           'assistToTurnover_L50', 'assistRatio_L50','estimatedTeamTurnoverPercentage_L50', 'turnoverRatio_L50',
                           'effectiveFieldGoalPercentage_L50','trueShootingPercentage_L50', 'estimatedPace_L50', 'pace_L50',
                           'pacePer40_L50', 'PIE_L50'])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_50_games = team_stats.iloc[max(0, index - 50):index]
        df_last_50_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN_L50" : (df_last_50_games['WL'] == 'W').sum(),
                   "PCT_TIR_REUSSI_L50" : df_last_50_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L50" : df_last_50_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L50" : df_last_50_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L50" : df_last_50_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L50" : df_last_50_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L50" : df_last_50_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L50" : df_last_50_games['defensiveRating'].mean(),
                   "estimatedNetRating_L50" : df_last_50_games['estimatedNetRating'].mean(),
                   "netRating_L50" : df_last_50_games['netRating'].mean(),
                   "assistPercentage_L50" : df_last_50_games['assistPercentage'].mean(),
                   "assistToTurnover_L50" : df_last_50_games['assistToTurnover'].mean(),
                   "assistRatio_L50" : df_last_50_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L50" : df_last_50_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L50" : df_last_50_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L50" : df_last_50_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L50" : df_last_50_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L50" : df_last_50_games['estimatedPace'].mean(),
                   "pace_L50" : df_last_50_games['pace'].mean(),
                   "pacePer40_L50" : df_last_50_games['pacePer40'].mean(),
                   "PIE_L50" : df_last_50_games['PIE'].mean()}
        df_stat_last_50_perf.loc[len(df_stat_last_50_perf)] = new_row
        index += 1
df_stat_last_50_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L50,PCT_TIR_REUSSI_L50,PCT_3PTS_L50,PCT_LANCER_FRANC_L50,estimatedOffensiveRating_L50,...,assistToTurnover_L50,assistRatio_L50,estimatedTeamTurnoverPercentage_L50,turnoverRatio_L50,effectiveFieldGoalPercentage_L50,trueShootingPercentage_L50,estimatedPace_L50,pace_L50,pacePer40_L50,PIE_L50
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422000,0.269000,0.783000,93.900,...,1.210000,17.000,18.79000,19.400000,0.464000,0.51000,100.4400,98.5000,82.0800,0.401000
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,0.415000,0.228500,0.839000,92.300,...,1.130000,16.600,19.90850,20.350000,0.446000,0.49800,96.3500,94.2500,78.5400,0.478000
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,0.427333,0.223667,0.857667,95.400,...,1.273333,17.400,19.13400,19.566667,0.453333,0.50300,97.7800,96.0000,80.0000,0.491333
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,1,0.409500,0.251000,0.856250,93.325,...,1.162500,16.225,19.24825,19.675000,0.437500,0.49500,96.4750,94.5000,78.7500,0.459500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300906,1610612743,2024-03-07,DEN vs. BOS,W,33,0.490340,0.373160,0.770420,115.334,...,2.553200,20.564,12.61332,12.852000,0.555580,0.58508,98.9834,97.4448,81.2040,0.518660
25944,22300922,1610612743,2024-03-09,DEN vs. UTA,W,34,0.490820,0.367300,0.774740,115.374,...,2.585400,20.604,12.50334,12.746000,0.554800,0.58478,99.0646,97.4748,81.2290,0.521900
25945,22300937,1610612743,2024-03-11,DEN vs. TOR,W,34,0.494880,0.371320,0.775760,116.086,...,2.599800,20.732,12.50392,12.750000,0.559880,0.58944,99.1282,97.4848,81.2372,0.523160
25946,22300949,1610612743,2024-03-13,DEN @ MIA,W,35,0.496360,0.369640,0.772740,116.116,...,2.631400,20.814,12.43546,12.682000,0.560800,0.58994,99.2278,97.5648,81.3040,0.525200
25947,22300965,1610612743,2024-03-15,DEN @ SAS,W,36,0.499320,0.371640,0.772300,116.638,...,2.656800,20.956,12.36250,12.596000,0.564340,0.59300,99.0358,97.4048,81.1706,0.529680

In [4]:
df_stat_last_50_perf.to_csv('../dataset/team_stat_last_50.csv', index=False)

In [5]:
df_stat_last_50_perf = df_stat_last_50_perf.sort_values(by='gameId')
df_stat_last_50_perf.reset_index(drop=True, inplace=True)
df_stat_last_50_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L50,PCT_TIR_REUSSI_L50,PCT_3PTS_L50,PCT_LANCER_FRANC_L50,estimatedOffensiveRating_L50,...,assistToTurnover_L50,assistRatio_L50,estimatedTeamTurnoverPercentage_L50,turnoverRatio_L50,effectiveFieldGoalPercentage_L50,trueShootingPercentage_L50,estimatedPace_L50,pace_L50,pacePer40_L50,PIE_L50
0,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612746,2013-10-29,LAC @ LAL,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,30,0.48414,0.36438,0.76488,117.228,...,2.4350,19.568,12.41416,12.568,0.56556,0.59998,101.8022,100.3704,83.6422,0.49620
25944,22301229,1610612754,2023-12-07,IND @ MIL,W,22,0.49492,0.37812,0.78486,115.828,...,2.3204,19.992,13.04992,13.370,0.57070,0.60210,104.4374,102.1724,85.1438,0.48850
25945,22301229,1610612749,2023-12-07,MIL vs. IND,L,37,0.49720,0.38364,0.75982,117.464,...,2.0992,19.088,13.10776,13.248,0.58256,0.61100,103.6644,102.1886,85.1570,0.52836
25946,22301230,1610612740,2023-12-07,NOP @ LAL,L,27,0.48370,0.37326,0.79022,113.054,...,2.0460,18.900,13.52190,13.716,0.54786,0.58610,100.7228,99.0906,82.5756,0.51686
25947,22301230,1610612747,2023-12-07,LAL vs. NOP,W,31,0.48416,0.35012,0.76808,111.588,...,1.9332,18.524,14.00494,14.202,0.54632,0.58526,102.7270,100.9598,84.1336,0.52394

In [6]:
df_stat_last_50_perf.to_csv('../dataset/team_stat_last_50.csv', index=False)

In [7]:
a = df_stat_last_50_perf[df_stat_last_50_perf['gameId'] == '21300018']
a

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L50,PCT_TIR_REUSSI_L50,PCT_3PTS_L50,PCT_LANCER_FRANC_L50,estimatedOffensiveRating_L50,...,assistToTurnover_L50,assistRatio_L50,estimatedTeamTurnoverPercentage_L50,turnoverRatio_L50,effectiveFieldGoalPercentage_L50,trueShootingPercentage_L50,estimatedPace_L50,pace_L50,pacePer40_L50,PIE_L50
34,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,95.3,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589
35,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,93.9,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401

In [8]:
a.reset_index(inplace=True)
a

,index,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L50,PCT_TIR_REUSSI_L50,PCT_3PTS_L50,PCT_LANCER_FRANC_L50,...,assistToTurnover_L50,assistRatio_L50,estimatedTeamTurnoverPercentage_L50,turnoverRatio_L50,effectiveFieldGoalPercentage_L50,trueShootingPercentage_L50,estimatedPace_L50,pace_L50,pacePer40_L50,PIE_L50
0,34,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589
1,35,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401

In [9]:
for game_id in list(set(df_stat_last_50_perf['gameId'].tolist())):
    df_game = df_stat_last_50_perf[df_stat_last_50_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_50_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_50_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_50_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN_L50,PCT_TIR_REUSSI_L50,PCT_3PTS_L50,PCT_LANCER_FRANC_L50,estimatedOffensiveRating_L50,...,assistToTurnover_L50,assistRatio_L50,estimatedTeamTurnoverPercentage_L50,turnoverRatio_L50,effectiveFieldGoalPercentage_L50,trueShootingPercentage_L50,estimatedPace_L50,pace_L50,pacePer40_L50,PIE_L50
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,30,0.48414,0.36438,0.76488,117.228,...,2.4350,19.568,12.41416,12.568,0.56556,0.59998,101.8022,100.3704,83.6422,0.49620
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,37,0.49720,0.38364,0.75982,117.464,...,2.0992,19.088,13.10776,13.248,0.58256,0.61100,103.6644,102.1886,85.1570,0.52836
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,22,0.49492,0.37812,0.78486,115.828,...,2.3204,19.992,13.04992,13.370,0.57070,0.60210,104.4374,102.1724,85.1438,0.48850
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,31,0.48416,0.35012,0.76808,111.588,...,1.9332,18.524,14.00494,14.202,0.54632,0.58526,102.7270,100.9598,84.1336,0.52394
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,27,0.48370,0.37326,0.79022,113.054,...,2.0460,18.900,13.52190,13.716,0.54786,0.58610,100.7228,99.0906,82.5756,0.51686

In [10]:
df_stat_last_50_perf.to_csv('../dataset/team_stat_last_50.csv', index=False)
print(df_stat_last_50_perf.columns)

Index(['gameId', 'teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L50',
       'PCT_TIR_REUSSI_L50', 'PCT_3PTS_L50', 'PCT_LANCER_FRANC_L50',
       'estimatedOffensiveRating_L50', 'offensiveRating_L50',
       'estimatedDefensiveRating_L50', 'defensiveRating_L50',
       'estimatedNetRating_L50', 'netRating_L50', 'assistPercentage_L50',
       'assistToTurnover_L50', 'assistRatio_L50',
       'estimatedTeamTurnoverPercentage_L50', 'turnoverRatio_L50',
       'effectiveFieldGoalPercentage_L50', 'trueShootingPercentage_L50',
       'estimatedPace_L50', 'pace_L50', 'pacePer40_L50', 'PIE_L50'],
      dtype='object')

In [11]:
df_stat_last_50_perf['col'] = df_stat_last_50_perf.groupby('gameId').cumcount() + 1
df_stat_last_50_perf = df_stat_last_50_perf.pivot_table(index='gameId', columns=df_stat_last_50_perf.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L50',
       'PCT_TIR_REUSSI_L50', 'PCT_3PTS_L50', 'PCT_LANCER_FRANC_L50',
       'estimatedOffensiveRating_L50', 'offensiveRating_L50',
       'estimatedDefensiveRating_L50', 'defensiveRating_L50',
       'estimatedNetRating_L50', 'netRating_L50', 'assistPercentage_L50',
       'assistToTurnover_L50', 'assistRatio_L50',
       'estimatedTeamTurnoverPercentage_L50', 'turnoverRatio_L50',
       'effectiveFieldGoalPercentage_L50', 'trueShootingPercentage_L50',
       'estimatedPace_L50', 'pace_L50', 'pacePer40_L50', 'PIE_L50'], aggfunc='first')
df_stat_last_50_perf.columns = [f'col{col[1]}' for col in df_stat_last_50_perf.columns]

df_stat_last_50_perf
df_applati = df_stat_last_50_perf.reset_index()
df_applati

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.55000,NaN,...,NaN,82.0800,NaN,98.5000,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,13,23,0.34174,0.38178,0.79922,...,83.2460,83.0770,99.8952,99.6916,1610612757,1610612742,0.55932,0.60036,14.692,11.834
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,35,32,0.37580,0.37354,0.77682,...,82.0624,81.1842,98.4752,97.4206,1610612738,1610612752,0.59778,0.58372,13.514,13.240
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,30,30,0.36622,0.36438,0.81394,...,82.2286,83.6422,98.6744,100.3704,1610612756,1610612758,0.58464,0.59998,13.630,12.568
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,37,22,0.38364,0.37812,0.75982,...,85.1570,85.1438,102.1886,102.1724,1610612749,1610612754,0.61100,0.60210,13.248,13.370
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,31,27,0.35012,0.37326,0.76808,...,84.1336,82.5756,100.9598,99.0906,1610612747,1610612740,0.58526,0.58610,14.202,13.716

In [12]:
print(['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L50','PCT_TIR_REUSSI_L50', 'PCT_3PTS_L50', 'PCT_LANCER_FRANC_L50','estimatedOffensiveRating_L50', 'offensiveRating_L50','estimatedDefensiveRating_L50', 'defensiveRating_L50','estimatedNetRating_L50', 'netRating_L50', 'assistPercentage_L50','assistToTurnover_L50', 'assistRatio_L50','estimatedTeamTurnoverPercentage_L50', 'turnoverRatio_L50','effectiveFieldGoalPercentage_L50', 'trueShootingPercentage_L50','estimatedPace_L50', 'pace_L50', 'pacePer40_L50'])
liste_nom_colonnes = df_applati.columns
liste_nom_colonnes

['GAME_DATE', 'DUEL', 'WL', 'NB_WIN_L50', 'PCT_TIR_REUSSI_L50', 'PCT_3PTS_L50', 'PCT_LANCER_FRANC_L50', 'estimatedOffensiveRating_L50', 'offensiveRating_L50', 'estimatedDefensiveRating_L50', 'defensiveRating_L50', 'estimatedNetRating_L50', 'netRating_L50', 'assistPercentage_L50', 'assistToTurnover_L50', 'assistRatio_L50', 'estimatedTeamTurnoverPercentage_L50', 'turnoverRatio_L50', 'effectiveFieldGoalPercentage_L50', 'trueShootingPercentage_L50', 'estimatedPace_L50', 'pace_L50', 'pacePer40_L50']

Index(['gameId', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2'],
      dtype='object')

In [13]:
print(len(df_applati.columns))
df_applati.columns = ['game_id','H_TEAM_ID', 'A_TEAM_ID', 'H_GAME_DATE', 'A_GAME_DATE', 'H_DUEL', 'A_DUEL', 'H_WL', 'A_WL', 'H_NB_WIN_L50', 'A_NB_WIN_L50', 'H_PCT_TIR_REUSSI_L50', 'A_PCT_TIR_REUSSI_L50', 'H_PCT_3PTS_L50', 'A_PCT_3PTS_L50', 'H_PCT_LANCER_FRANC_L50', 'A_PCT_LANCER_FRANC_L50', 'H_estimatedOffensiveRating_L50', 'A_estimatedOffensiveRating_L50', 'H_offensiveRating_L50', 'A_offensiveRating_L50', 'H_estimatedDefensiveRating_L50', 'A_estimatedDefensiveRating_L50', 'H_defensiveRating_L50', 'A_defensiveRating_L50', 'H_estimatedNetRating_L50', 'A_estimatedNetRating_L50', 'H_netRating_L50', 'A_netRating_L50', 'H_assistPercentage_L50', 'A_assistPercentage_L50', 'H_assistToTurnover_L50', 'A_assistToTurnover_L50', 'H_assistRatio_L50', 'A_assistRatio_L50', 'H_estimatedTeamTurnoverPercentage_L50', 'A_estimatedTeamTurnoverPercentage_L50', 'H_turnoverRatio_L50', 'A_turnoverRatio_L50', 'H_effectiveFieldGoalPercentage_L50', 'A_effectiveFieldGoalPercentage_L50', 'H_trueShootingPercentage_L50', 'A_trueShootingPercentage_L50', 'H_estimatedPace_L50', 'A_estimatedPace_L50', 'H_pace_L50', 'A_pace_L50', 'H_pacePer40_L50', 'A_pacePer40_L50', 'H_PIE_L50', 'A_PIE_L50']

df_applati

51

,game_id,H_TEAM_ID,A_TEAM_ID,H_GAME_DATE,A_GAME_DATE,H_DUEL,A_DUEL,H_WL,A_WL,H_NB_WIN_L50,...,H_trueShootingPercentage_L50,A_trueShootingPercentage_L50,H_estimatedPace_L50,A_estimatedPace_L50,H_pace_L50,A_pace_L50,H_pacePer40_L50,A_pacePer40_L50,H_PIE_L50,A_PIE_L50
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.55000,NaN,...,NaN,82.0800,NaN,98.5000,1610612755,1610612748,NaN,0.63100,NaN,20.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,13,23,0.34174,0.38178,0.79922,...,83.2460,83.0770,99.8952,99.6916,1610612757,1610612742,0.55932,0.60036,14.692,11.834
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,35,32,0.37580,0.37354,0.77682,...,82.0624,81.1842,98.4752,97.4206,1610612738,1610612752,0.59778,0.58372,13.514,13.240
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,30,30,0.36622,0.36438,0.81394,...,82.2286,83.6422,98.6744,100.3704,1610612756,1610612758,0.58464,0.59998,13.630,12.568
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,37,22,0.38364,0.37812,0.75982,...,85.1570,85.1438,102.1886,102.1724,1610612749,1610612754,0.61100,0.60210,13.248,13.370
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,31,27,0.35012,0.37326,0.76808,...,84.1336,82.5756,100.9598,99.0906,1610612747,1610612740,0.58526,0.58610,14.202,13.716