In [39]:
import pandas as pd

In [40]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
25944,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
25945,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
25946,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
25947,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [41]:
df_chicago = df_stat[df_stat['teamId'] == "1610612741"]
df_chicago.reset_index(drop=True, inplace=True)
df_chicago

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.50,82.08,98.0,0.401
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,1,1,0.500,240,31,...,21.3,0.428,0.486,1.0,0.199,92.26,90.00,75.00,89.0,0.555
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,2,0.333,240,42,...,18.0,0.468,0.513,1.0,0.199,100.64,99.50,82.92,100.0,0.518
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,3,0.250,240,26,...,20.0,0.390,0.471,1.0,0.198,92.56,90.00,75.00,90.0,0.364
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,2,3,0.400,240,38,...,22.6,0.549,0.584,1.0,0.196,94.50,93.00,77.50,93.0,0.756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,22300907,1610612741,2024-03-07,CHI @ GSW,W,31,32,0.492,240,46,...,13.6,0.621,0.644,1.0,0.198,105.72,103.50,86.25,103.0,0.508
856,22300917,1610612741,2024-03-09,CHI @ LAC,L,31,33,0.484,240,37,...,12.6,0.506,0.540,1.0,0.201,96.64,94.50,78.75,95.0,0.434
857,22300935,1610612741,2024-03-11,CHI vs. DAL,L,31,34,0.477,240,35,...,13.8,0.433,0.466,1.0,0.199,96.64,94.50,78.75,94.0,0.313
858,22300948,1610612741,2024-03-13,CHI @ IND,W,32,34,0.485,265,48,...,10.8,0.576,0.622,1.0,0.198,100.71,100.53,83.77,111.0,0.516
859,22300956,1610612741,2024-03-14,CHI vs. LAC,L,32,35,0.478,240,41,...,14.0,0.570,0.597,1.0,0.198,92.60,92.00,76.67,93.0,0.419

In [42]:
index = 11
df_last_10_games = df_chicago.iloc[max(0, index - 10):index]
df_last_10_games

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,1,1,0.500,240,31,...,21.3,0.428,0.486,1.0,0.199,92.26,90.0,75.00,89.0,0.555
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,2,0.333,240,42,...,18.0,0.468,0.513,1.0,0.199,100.64,99.5,82.92,100.0,0.518
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,3,0.250,240,26,...,20.0,0.390,0.471,1.0,0.198,92.56,90.0,75.00,90.0,0.364
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,2,3,0.400,240,38,...,22.6,0.549,0.584,1.0,0.196,94.50,93.0,77.50,93.0,0.756
5,21300102,1610612741,2013-11-11,CHI vs. CLE,W,3,3,0.500,240,34,...,12.5,0.434,0.508,1.0,0.201,92.12,88.0,73.33,88.0,0.640
6,21300126,1610612741,2013-11-15,CHI @ TOR,W,4,3,0.571,240,36,...,18.5,0.494,0.543,1.0,0.196,95.52,92.5,77.08,92.0,0.615
7,21300140,1610612741,2013-11-16,CHI vs. IND,W,5,3,0.625,240,40,...,16.7,0.576,0.614,1.0,0.195,95.94,90.5,75.42,90.0,0.610
8,21300151,1610612741,2013-11-18,CHI vs. CHA,W,6,3,0.667,240,27,...,17.2,0.400,0.485,1.0,0.203,95.34,92.5,77.08,93.0,0.564
9,21300175,1610612741,2013-11-21,CHI @ DEN,L,6,4,0.600,240,38,...,18.8,0.403,0.418,1.0,0.195,98.42,96.5,80.42,96.0,0.416
10,21300185,1610612741,2013-11-22,CHI @ POR,L,6,5,0.545,240,32,...,17.2,0.416,0.496,1.0,0.197,95.68,92.0,76.67,93.0,0.463

In [43]:
game_id = df_last_10_games['gameId'][10]
print(game_id)

21300185

In [44]:

nb_wins = (df_last_10_games['WL'] == 'W').sum()
print(nb_wins)
pct_tir = df_last_10_games['PCT_TIR_REUSSI'].mean()
print(pct_tir)
pct_3pt = df_last_10_games['PCT_3PTS'].mean()
print(pct_3pt)
pct_lf = df_last_10_games['PCT_LANCER_FRANC'].mean()
print(pct_lf)
e_offensive_rating = df_last_10_games['estimatedOffensiveRating'].mean()
print(e_offensive_rating)
offensive_rating = df_last_10_games['offensiveRating'].mean()
print(offensive_rating)
e_defensive_rating = df_last_10_games['estimatedDefensiveRating'].mean()
print(e_defensive_rating)
defensive_rating = df_last_10_games['defensiveRating'].mean()
print(defensive_rating)
e_net_rating = df_last_10_games['estimatedNetRating'].mean()
print(e_net_rating)
net_rating = df_last_10_games['netRating'].mean()
print(net_rating)
ast_pct = df_last_10_games['assistPercentage'].mean()
print(ast_pct)
ast_to_tov = df_last_10_games['assistToTurnover'].mean()
print(ast_to_tov)
ast_ratio = df_last_10_games['assistRatio'].mean()
print(ast_ratio)
e_tov_ratio = df_last_10_games['estimatedTeamTurnoverPercentage'].mean()
print(e_tov_ratio)
tov_ratio = df_last_10_games['turnoverRatio'].mean()
print(tov_ratio)
effective_field_goal_percentage = df_last_10_games['effectiveFieldGoalPercentage'].mean()
print(effective_field_goal_percentage)
true_shooting_percentage = df_last_10_games['trueShootingPercentage'].mean()
print(true_shooting_percentage)
e_pace = df_last_10_games['estimatedPace'].mean()
print(e_pace)
pace = df_last_10_games['pace'].mean()
print(pace)
pace_per_40 = df_last_10_games['pacePer40'].mean()
print(pace_per_40)
pie = df_last_10_games['PIE'].mean()
print(pie)

6
0.4244
0.3534
0.8279
98.25999999999999
101.02
92.86999999999999
96.04
5.360000000000001
4.96
0.604
1.274
16.060000000000002
17.8112
18.28
0.4558
0.5118
95.298
92.45
77.04199999999999
0.5501

In [45]:
df_chicago

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.50,82.08,98.0,0.401
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,1,1,0.500,240,31,...,21.3,0.428,0.486,1.0,0.199,92.26,90.00,75.00,89.0,0.555
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,2,0.333,240,42,...,18.0,0.468,0.513,1.0,0.199,100.64,99.50,82.92,100.0,0.518
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,3,0.250,240,26,...,20.0,0.390,0.471,1.0,0.198,92.56,90.00,75.00,90.0,0.364
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,2,3,0.400,240,38,...,22.6,0.549,0.584,1.0,0.196,94.50,93.00,77.50,93.0,0.756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,22300907,1610612741,2024-03-07,CHI @ GSW,W,31,32,0.492,240,46,...,13.6,0.621,0.644,1.0,0.198,105.72,103.50,86.25,103.0,0.508
856,22300917,1610612741,2024-03-09,CHI @ LAC,L,31,33,0.484,240,37,...,12.6,0.506,0.540,1.0,0.201,96.64,94.50,78.75,95.0,0.434
857,22300935,1610612741,2024-03-11,CHI vs. DAL,L,31,34,0.477,240,35,...,13.8,0.433,0.466,1.0,0.199,96.64,94.50,78.75,94.0,0.313
858,22300948,1610612741,2024-03-13,CHI @ IND,W,32,34,0.485,265,48,...,10.8,0.576,0.622,1.0,0.198,100.71,100.53,83.77,111.0,0.516
859,22300956,1610612741,2024-03-14,CHI vs. LAC,L,32,35,0.478,240,41,...,14.0,0.570,0.597,1.0,0.198,92.60,92.00,76.67,93.0,0.419

In [46]:
df_stat_last_10_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN', 'PCT_TIR_REUSSI_L10','PCT_3PTS_L10', 
                           'PCT_LANCER_FRANC_L10','estimatedOffensiveRating_L10', 'offensiveRating_L10',
                           'estimatedDefensiveRating_L10',
                           'defensiveRating_L10','estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10',
                           'assistToTurnover_L10', 'assistRatio_L10','estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10',
                           'effectiveFieldGoalPercentage_L10','trueShootingPercentage_L10', 'estimatedPace_L10', 'pace_L10',
                           'pacePer40_L10', 'PIE_L10'])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 0
    while index < len(team_stats):
        df_last_10_games = team_stats.iloc[max(0, index - 10):index]
        df_last_10_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN" : (df_last_10_games['WL'] == 'W').sum(),
                   "PCT_TIR_REUSSI_L10" : df_last_10_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L10" : df_last_10_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L10" : df_last_10_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L10" : df_last_10_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L10" : df_last_10_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L10" : df_last_10_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L10" : df_last_10_games['defensiveRating'].mean(),
                   "estimatedNetRating_L10" : df_last_10_games['estimatedNetRating'].mean(),
                   "netRating_L10" : df_last_10_games['netRating'].mean(),
                   "assistPercentage_L10" : df_last_10_games['assistPercentage'].mean(),
                   "assistToTurnover_L10" : df_last_10_games['assistToTurnover'].mean(),
                   "assistRatio_L10" : df_last_10_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L10" : df_last_10_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L10" : df_last_10_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L10" : df_last_10_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L10" : df_last_10_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L10" : df_last_10_games['estimatedPace'].mean(),
                   "pace_L10" : df_last_10_games['pace'].mean(),
                   "pacePer40_L10" : df_last_10_games['pacePer40'].mean(),
                   "PIE_L10" : df_last_10_games['PIE'].mean()}
        df_stat_last_10_perf.loc[len(df_stat_last_10_perf)] = new_row
        index += 1
df_stat_last_10_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300006,1610612761,2013-10-30,TOR vs. BOS,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300023,1610612761,2013-11-01,TOR @ ATL,L,1,0.442000,0.294000,0.5220,97.800000,...,0.830000,11.600000,18.923000,19.600,0.47100,0.48400,94.440000,92.000000,76.670,0.5160
2,21300037,1610612761,2013-11-02,TOR @ MIL,W,1,0.448500,0.299000,0.5465,98.300000,...,1.040000,12.000000,15.701000,16.100,0.48250,0.49400,95.420000,93.500000,77.920,0.4645
3,21300051,1610612761,2013-11-05,TOR vs. MIA,L,2,0.431333,0.300667,0.6100,100.033333,...,1.066667,12.833333,16.513667,16.500,0.46900,0.50000,95.886667,94.833333,79.030,0.4910
4,21300060,1610612761,2013-11-06,TOR @ CHA,L,2,0.431250,0.297000,0.6620,101.850000,...,1.050000,12.850000,16.621500,16.625,0.46975,0.51225,94.500000,93.125000,77.605,0.4710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300895,1610612739,2024-03-06,CLE @ ATL,L,5,0.469000,0.394700,0.6967,111.810000,...,2.663000,22.350000,12.575900,12.720,0.55580,0.58390,97.362000,96.124000,80.102,0.5125
25944,22300911,1610612739,2024-03-08,CLE vs. MIN,W,5,0.465000,0.382300,0.6932,109.540000,...,2.543000,22.060000,12.942900,13.120,0.55030,0.57750,97.458000,96.124000,80.102,0.5057
25945,22300930,1610612739,2024-03-10,CLE vs. BKN,L,5,0.460000,0.382300,0.6892,108.660000,...,2.363000,21.580000,13.310800,13.550,0.54430,0.57340,97.772000,95.812000,79.842,0.5060
25946,22300934,1610612739,2024-03-11,CLE vs. PHX,L,5,0.453000,0.380600,0.6734,107.990000,...,2.408000,21.270000,12.584600,12.800,0.53930,0.56610,97.684000,95.862000,79.884,0.4958
25947,22300951,1610612739,2024-03-13,CLE @ NOP,W,5,0.458100,0.383600,0.6899,109.890000,...,2.421000,21.620000,12.843900,13.020,0.54830,0.57440,97.308000,95.712000,79.759,0.4952

In [47]:
df_stat_last_10_perf.to_csv('../dataset/team_stat_last_10.csv', index=False)

In [48]:
df_stat_last_10_perf = df_stat_last_10_perf.sort_values(by='gameId')
df_stat_last_10_perf.reset_index(drop=True, inplace=True)
df_stat_last_10_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612746,2013-10-29,LAC @ LAL,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,6,0.4738,0.3759,0.7684,114.96,...,2.129,19.61,12.9317,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [49]:
df_stat_last_10_perf.to_csv('../dataset/team_stat_last_10.csv', index=False)

In [50]:
a = df_stat_last_10_perf[df_stat_last_10_perf['gameId'] == '21300018']
a

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
34,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,93.9,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401
35,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,95.3,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589

In [51]:
a.reset_index(inplace=True)
a

,index,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,34,21300018,1610612741,2013-10-31,CHI vs. NYK,W,0,0.422,0.269,0.783,...,1.21,17.0,18.790,19.4,0.464,0.510,100.44,98.5,82.08,0.401
1,35,21300018,1610612752,2013-10-31,NYK @ CHI,L,1,0.507,0.231,0.882,...,0.77,14.5,23.285,23.4,0.528,0.573,96.38,94.0,78.33,0.589

In [52]:
"""print('vs' in a['DUEL'].values[0])
print()
df_stat_last_10_perf.loc[a['index'].values[0]] = a.loc[1]
df_stat_last_10_perf.loc[a['index'].values[1]] = a.loc[0]
df_stat_last_10_perf"""

"print('vs' in a['DUEL'].values[0])\nprint()\ndf_stat_last_10_perf.loc[a['index'].values[0]] = a.loc[1]\ndf_stat_last_10_perf.loc[a['index'].values[1]] = a.loc[0]\ndf_stat_last_10_perf"

In [53]:
for game_id in list(set(df_stat_last_10_perf['gameId'].tolist())):
    df_game = df_stat_last_10_perf[df_stat_last_10_perf['gameId'] == game_id]
    df_game.reset_index(inplace=True)
    if '@' in df_game['DUEL'].values[0]:
        df_stat_last_10_perf.loc[df_game['index'].values[0]] = df_game.loc[1]
        df_stat_last_10_perf.loc[df_game['index'].values[1]] = df_game.loc[0]
        
df_stat_last_10_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300001,1610612754,2013-10-29,IND vs. ORL,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21300001,1610612753,2013-10-29,ORL @ IND,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21300003,1610612747,2013-10-29,LAL vs. LAC,W,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22301228,1610612758,2023-12-08,SAC @ PHX,W,6,0.4738,0.3759,0.7684,114.96,...,2.129,19.61,12.9317,13.14,0.5591,0.5941,103.950,102.400,85.334,0.4814
25944,22301229,1610612749,2023-12-07,MIL vs. IND,L,8,0.5201,0.3984,0.7737,122.88,...,2.454,19.75,12.1841,12.30,0.6027,0.6296,104.243,102.598,85.498,0.5446
25945,22301229,1610612754,2023-12-07,IND @ MIL,W,5,0.5218,0.3864,0.7809,121.79,...,2.735,20.45,11.1999,11.57,0.6012,0.6305,107.508,104.300,86.917,0.5054
25946,22301230,1610612747,2023-12-07,LAL vs. NOP,W,7,0.4767,0.3244,0.7606,108.47,...,1.895,19.35,14.3494,14.62,0.5325,0.5706,102.164,100.750,83.959,0.5255
25947,22301230,1610612740,2023-12-07,NOP @ LAL,L,6,0.5006,0.3545,0.7908,118.61,...,2.203,19.92,13.3914,13.51,0.5590,0.6015,100.766,98.950,82.459,0.5425

In [54]:
df_stat_last_10_perf.to_csv('../dataset/team_stat_last_10.csv', index=False)
print(df_stat_last_10_perf.columns)

Index(['gameId', 'teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN',
       'PCT_TIR_REUSSI_L10', 'PCT_3PTS_L10', 'PCT_LANCER_FRANC_L10',
       'estimatedOffensiveRating_L10', 'offensiveRating_L10',
       'estimatedDefensiveRating_L10', 'defensiveRating_L10',
       'estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10',
       'assistToTurnover_L10', 'assistRatio_L10',
       'estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10',
       'effectiveFieldGoalPercentage_L10', 'trueShootingPercentage_L10',
       'estimatedPace_L10', 'pace_L10', 'pacePer40_L10', 'PIE_L10'],
      dtype='object')

In [55]:
df_stat_last_10_perf['col'] = df_stat_last_10_perf.groupby('gameId').cumcount() + 1
df_stat_last_10_perf = df_stat_last_10_perf.pivot_table(index='gameId', columns=df_stat_last_10_perf.groupby('gameId').cumcount() + 1, values=['teamId', 'GAME_DATE', 'DUEL', 'WL', 'NB_WIN',
       'PCT_TIR_REUSSI_L10', 'PCT_3PTS_L10', 'PCT_LANCER_FRANC_L10',
       'estimatedOffensiveRating_L10', 'offensiveRating_L10',
       'estimatedDefensiveRating_L10', 'defensiveRating_L10',
       'estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10',
       'assistToTurnover_L10', 'assistRatio_L10',
       'estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10',
       'effectiveFieldGoalPercentage_L10', 'trueShootingPercentage_L10',
       'estimatedPace_L10', 'pace_L10', 'pacePer40_L10', 'PIE_L10'], aggfunc='first')
df_stat_last_10_perf.columns = [f'col{col[1]}' for col in df_stat_last_10_perf.columns]

df_stat_last_10_perf
df_applati = df_stat_last_10_perf.reset_index()
df_applati

,gameId,col1,col2,col1,col2,col1,col2,col1,col2,col1,...,col1,col2,col1,col2,col1,col2,col1,col2,col1,col2
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,3,4,0.3744,0.3463,0.7976,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,7,7,0.3545,0.3853,0.7753,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,7,6,0.3954,0.3759,0.8557,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,8,5,0.3984,0.3864,0.7737,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,7,6,0.3244,0.3545,0.7606,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51

In [56]:
print(['GAME_DATE', 'DUEL', 'WL', 'NB_WIN','PCT_TIR_REUSSI_L10', 'PCT_3PTS_L10', 'PCT_LANCER_FRANC_L10','estimatedOffensiveRating_L10', 'offensiveRating_L10','estimatedDefensiveRating_L10', 'defensiveRating_L10','estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10','assistToTurnover_L10', 'assistRatio_L10','estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10','effectiveFieldGoalPercentage_L10', 'trueShootingPercentage_L10','estimatedPace_L10', 'pace_L10', 'pacePer40_L10'])
liste_nom_colonnes = df_applati.columns
liste_nom_colonnes

['GAME_DATE', 'DUEL', 'WL', 'NB_WIN', 'PCT_TIR_REUSSI_L10', 'PCT_3PTS_L10', 'PCT_LANCER_FRANC_L10', 'estimatedOffensiveRating_L10', 'offensiveRating_L10', 'estimatedDefensiveRating_L10', 'defensiveRating_L10', 'estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10', 'assistToTurnover_L10', 'assistRatio_L10', 'estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10', 'effectiveFieldGoalPercentage_L10', 'trueShootingPercentage_L10', 'estimatedPace_L10', 'pace_L10', 'pacePer40_L10']

Index(['gameId', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2',
       'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2', 'col1',
       'col2', 'col1', 'col2', 'col1', 'col2', 'col1', 'col2'],
      dtype='object')

In [57]:
print(len(df_applati.columns))
df_applati.columns = ['game_id','H_TEAM_ID', 'A_TEAM_ID', 'H_GAME_DATE', 'A_GAME_DATE', 'H_DUEL', 'A_DUEL', 'H_WL', 'A_WL', 'H_NB_WIN', 'A_NB_WIN', 'H_PCT_TIR_REUSSI_L10', 'A_PCT_TIR_REUSSI_L10', 'H_PCT_3PTS_L10', 'A_PCT_3PTS_L10', 'H_PCT_LANCER_FRANC_L10', 'A_PCT_LANCER_FRANC_L10', 'H_estimatedOffensiveRating_L10', 'A_estimatedOffensiveRating_L10', 'H_offensiveRating_L10', 'A_offensiveRating_L10', 'H_estimatedDefensiveRating_L10', 'A_estimatedDefensiveRating_L10', 'H_defensiveRating_L10', 'A_defensiveRating_L10', 'H_estimatedNetRating_L10', 'A_estimatedNetRating_L10', 'H_netRating_L10', 'A_netRating_L10', 'H_assistPercentage_L10', 'A_assistPercentage_L10', 'H_assistToTurnover_L10', 'A_assistToTurnover_L10', 'H_assistRatio_L10', 'A_assistRatio_L10', 'H_estimatedTeamTurnoverPercentage_L10', 'A_estimatedTeamTurnoverPercentage_L10', 'H_turnoverRatio_L10', 'A_turnoverRatio_L10', 'H_effectiveFieldGoalPercentage_L10', 'A_effectiveFieldGoalPercentage_L10', 'H_trueShootingPercentage_L10', 'A_trueShootingPercentage_L10', 'H_estimatedPace_L10', 'A_estimatedPace_L10', 'H_pace_L10', 'A_pace_L10', 'H_pacePer40_L10', 'A_pacePer40_L10', 'H_PIE_L10', 'A_PIE_L10']

df_applati

51

,game_id,H_TEAM_ID,A_TEAM_ID,H_GAME_DATE,A_GAME_DATE,H_DUEL,A_DUEL,H_WL,A_WL,H_NB_WIN,...,H_trueShootingPercentage_L10,A_trueShootingPercentage_L10,H_estimatedPace_L10,A_estimatedPace_L10,H_pace_L10,A_pace_L10,H_pacePer40_L10,A_pacePer40_L10,H_PIE_L10,A_PIE_L10
0,21300001,IND vs. ORL,ORL @ IND,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612754,1610612753,NaN,NaN,NaN,NaN
1,21300002,MIA vs. CHI,CHI @ MIA,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612748,1610612741,NaN,NaN,NaN,NaN
2,21300003,LAL vs. LAC,LAC @ LAL,2013-10-29,2013-10-29,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612747,1610612746,NaN,NaN,NaN,NaN
3,21300004,CLE vs. BKN,BKN @ CLE,2013-10-30,2013-10-30,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1610612739,1610612751,NaN,NaN,NaN,NaN
4,21300005,PHI vs. MIA,MIA @ PHI,2013-10-30,2013-10-30,0,1,NaN,0.5500,NaN,...,NaN,82.080,NaN,98.50,1610612755,1610612748,NaN,0.6310,NaN,20.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12969,22301226,POR vs. DAL,DAL @ POR,2023-12-08,2023-12-08,3,4,0.3744,0.3463,0.7976,...,81.051,83.168,97.259,99.80,1610612757,1610612742,0.5395,0.5587,16.22,10.72
12970,22301227,BOS vs. NYK,NYK @ BOS,2023-12-08,2023-12-08,7,7,0.3545,0.3853,0.7753,...,82.192,80.624,98.631,96.75,1610612738,1610612752,0.5876,0.5792,15.05,13.69
12971,22301228,PHX vs. SAC,SAC @ PHX,2023-12-08,2023-12-08,7,6,0.3954,0.3759,0.8557,...,80.209,85.334,96.250,102.40,1610612756,1610612758,0.6058,0.5941,14.64,13.14
12972,22301229,MIL vs. IND,IND @ MIL,2023-12-07,2023-12-07,8,5,0.3984,0.3864,0.7737,...,85.498,86.917,102.598,104.30,1610612749,1610612754,0.6296,0.6305,12.30,11.57
12973,22301230,LAL vs. NOP,NOP @ LAL,2023-12-07,2023-12-07,7,6,0.3244,0.3545,0.7606,...,83.959,82.459,100.750,98.95,1610612747,1610612740,0.5706,0.6015,14.62,13.51